% Functions and Classes list for the imUtil.spec.extinction package
% Author : autogenerated (Jan 2025)
% imUtil.spec.extinction.allFunList - Functions and Classes list for the imUtil.spec.extinction package
% imUtil.spec.extinction.applyAtmosphericExtinction - Apply extinction to spectrum
 help imUtil.spec.extinction.allFunList