% Functions and Classes list for the imProc.astrometry package
% Author : autogenerated (May 2022)
% imProc.astrometry.addCoordinates2catalog - Add or update RA/Dec coordinates in catalogs in AstroImage/Astrocatalog
% imProc.astrometry.assessAstrometricQuality - Collect information regarding quality of astrometric solution and
% imProc.astrometry.astrometryCheck - Compare the astrometry of a catalog with a reference astrometric catalog.
% imProc.astrometry.astrometryCore - A core function for astrometry. Match pattern and fit transformation.
% imProc.astrometry.astrometryCropped - Execute astrometry on a section of a full image.
% imProc.astrometry.astrometryImage - 
% imProc.astrometry.astrometryRefine - Refine an astrometric solution of an AstroCatalog object
% imProc.astrometry.astrometrySubImages - Solve astrometry for sub images of a single contigious image
%       imProc.astrometry.fitWCS - Perform the Tran2D.fitAstrometricTran and prepare the WCS info
%     imProc.astrometry.unitTest - unitTest for +imProc.astrometry
 help imProc.astrometry.allFunList