function [ResultFit] = defResultFit(Nai, Origin)
    % Define and allocate memory for ResultFit structure array used by astrometry solvers
    % Input  : - Number of elements in the array.
    %          - Origin init. Default [] (empty cell).
    % Output : - An ResultFit structure array.
    % Author : Eran Ofek (2025 Nov) 
    % Example: ResFit=imProc.astrometry.defResultFit(1);

    arguments
        Nai
        Origin = [];
    end

    if isempty(Origin)
        Origin = cell(Nai,1);
    end
       
    ResultFit = struct('ImageCenterXY',cell(Nai,1),...
                    'Nsolutions',cell(Nai,1),...
                    'ResPattern',cell(Nai,1),...
                    'ErrorOnMean',cell(Nai,1),...
                    'BestInd',cell(Nai,1),...
                    'WCS',cell(Nai,1),...
                    'ParWCS',cell(Nai,1),...
                    'Tran',cell(Nai,1),...
                    'ResFit',cell(Nai,1),...
                    'Origin',Origin,...
                    'Success',cell(Nai,1));


end
