% Functions and Classes list for the celestial.pm package
% Author : autogenerated (Jan 2025)
%        celestial.pm.allFunList - Functions and Classes list for the celestial.pm package
% celestial.pm.fitLinearProperMotion - One line description
% celestial.pm.fitMultiProperMotion - Simultanoulsy (fast) fit proper motion and stationary model to observations
% celestial.pm.searchCatForKnownPM - Given a catalog of sources positions and times, and a specific
%          celestial.pm.unitTest - unitTest for celestial.pm
 help celestial.pm.allFunList