% Functions and Classes list for the celestial.pm package
% Author : autogenerated (Jun 2023)
%        celestial.pm.allFunList - Functions and Classes list for the celestial.pm package
% celestial.pm.fitMultiProperMotion - Simultanoulsy (fast) fit proper motion and stationary model to observations
% celestial.pm.searchCatForKnownPM - Given a catalog of sources positions and times, and a specific
%          celestial.pm.unitTest - Package Unit-Test
 help celestial.pm.allFunList