% Functions and Classes list for the imProc.sources package
% Author : autogenerated (May 2022)
% imProc.sources.classifySources - Classify sources found by findMeasureSources.
%    imProc.sources.cleanSources - Clean sources found by findMeasureSources (bad S/N and CR).
% imProc.sources.findMeasureSources - Basic sources finder and measurments on AstroImage object.
%     imProc.sources.findSources - Find sources (only) in AstroImage using imUtil.sources.findSources
%      imProc.sources.psfFitPhot - Execute PSF photometry on a list of coordinates and add the results
 help imProc.sources.allFunList