% Functions and Classes list for the celestial.galaxies package
% Author : autogenerated (Jan 2025)
% celestial.galaxies.isInsideLMC - Check if coordinates is within the LMC footprints.
% celestial.galaxies.isInsideSMC - Check if coordinates is within the SMC footprints.
 help celestial.galaxies.allFunList