% Functions and Classes list for the imUtil.spec.trace package
% Author : autogenerated (Jan 2025)
%   imUtil.spec.trace.allFunList - Functions and Classes list for the imUtil.spec.trace package
%     imUtil.spec.trace.collapse - Collapse a 2-D image, including pre and post filtering, and peak detection.
%     imUtil.spec.trace.fitTrace - Fit a trace position as a function of wavelength position.
% imUtil.spec.trace.image2cutouts1d - Cut line-stamps from an array, around some central (whole pixel) position.
% imUtil.spec.trace.linearizeTrace - Given an image containing a curved trace, and the trace function, generate a linearized version of the image
%     imUtil.spec.trace.moment1d - Calculate the 1st and 2nd 1-D moments on columns or rows of matrix
% imUtil.spec.trace.peakDetectionFilter1 - Detect 1-D local maxima in columns or rows using 1-D filtering.
% imUtil.spec.trace.traceByCollapse - Find, fit and linazrize traces from spectra in an image
 help imUtil.spec.trace.allFunList