% Functions and Classes list for the imProc.match package
% Author : autogenerated (Jun 2023)
%        imProc.match.allFunList - Functions and Classes list for the imProc.match package
%        imProc.match.coneSearch - cone search(s) on AstroCatalog/AstroImage object
% imProc.match.flagSrcWithNeighbors - Flag sources in AstroCatalog which have neighbors within a radius
%         imProc.match.inPolygon - Return sources inside polygon
% imProc.match.insertColFromMatched_matchIndices - Given two catalogs, matched them and insert some matched columns to the first catalog
% imProc.match.insertCol_matchIndices - Insert Dist/Nmatch columns to a single element AstroCatalog based on ResInd.
%             imProc.match.match - Match the content of two AstroCatalog objects.
% imProc.match.match2solarSystem - Match sources in AstroCatalog object to Solar System objects.
%          imProc.match.matchOld - Match two catalogs in AstroCatalog objects
% imProc.match.matchReturnIndices - Match two catalogs in AstroCatalog objects and return the matched indices.
%     imProc.match.match_catsHTM - Match an AstroCatalog object with catsHTM catalog and add columns to catalog.
% imProc.match.match_catsHTM_multiInsertFlag - 
% imProc.match.match_catsHTMmerged - Match an AstroCatalog with the catsHTM MergedCat.
%    imProc.match.matched2matrix - A matched AstroCatalog object into a matrix of epochs by index
%  imProc.match.matchedReturnCat - Match AsstroCatalogs and return array of matched catalogs.
%     imProc.match.mergeCatalogs - Merge catalogs of the same field into a single unified merged catalog
% imProc.match.returnMatched_catsHTM - Return a catsHTM catalog matched to an AstroCatalog object.
% imProc.match.unifiedSourcesCatalog - Match multiple catalogs and create a catalog of all unique (by position) sources.
%          imProc.match.unitTest - unitTest for +imProc.match
 help imProc.match.allFunList