function [Matched2, Ind1, Matched1, Ind2] = matchCat(Obj1, Obj2, Args)
    % Match catalogs by coordinates and return matched sub-catalogs.
    % Description: Match sources stored in AstroCatalog/AstroImage/
    %              AstroDiff/AstroZOGY objects and return catalogs
    %              containing only the matched sources.
    %              Matching is performed using imProc.match.matchInd.
    %              
    %              The output catalogs are generated by selecting rows from
    %              the input catalogs using the matched indices returned by
    %              imProc.match.matchInd.
    %
    % Input  : - Obj1 : An AstroCatalog/AstroImage/AstroDiff/AstroZOGY
    %                   object array. Each element must contain a source
    %                   catalog.
    %          - Obj2 : An AstroCatalog/AstroImage/AstroDiff/AstroZOGY
    %                   object array. Each element must contain a source
    %                   catalog.
    %                   If numel(Obj1)==numel(Obj2), catalogs are matched
    %                   element by element.
    %                   If one of the inputs is scalar, then that object is
    %                   matched against all elements of the other input.
    %          * ...,key,val,...
    %            'SearchRadius'      - Search radius. If IsSpherical is
    %                                  false, then this is in planar units
    %                                  (typically pixels). If IsSpherical
    %                                  is true, then this is in the angular
    %                                  units specified by
    %                                  SearchRadiusUnits.
    %                                  Default is 1.5.
    %            'SearchRadiusUnits' - Units of SearchRadius when
    %                                  IsSpherical=true.
    %                                  Default is 'arcsec'.
    %            'IsSpherical'       - Logical indicating whether to use
    %                                  spherical coordinates (true) or
    %                                  planar coordinates (false).
    %                                  Default is true.
    %            'Units'             - Optional override for the spherical
    %                                  coordinate units of both catalogs.
    %                                  For example: 'rad' or 'deg'.
    %                                  If empty, units are taken from the
    %                                  catalog metadata.
    %                                  Default is [].
    %            'ColSphere1'        - Two-element cell array containing the
    %                                  spherical coordinate column names in
    %                                  Obj1.
    %                                  Default is {'RA','Dec'}.
    %            'ColSphere2'        - Two-element cell array containing the
    %                                  spherical coordinate column names in
    %                                  Obj2.
    %                                  Default is {'RA','Dec'}.
    %            'ColPlanar1'        - Two-element cell array containing the
    %                                  planar coordinate column names in
    %                                  Obj1.
    %                                  Default is {'X','Y'}.
    %            'ColPlanar2'        - Two-element cell array containing the
    %                                  planar coordinate column names in
    %                                  Obj2.
    %                                  Default is {'X','Y'}.
    %            'Sort1'             - Sort catalog 1 before matching.
    %                                  Default is false.
    %            'Sort2'             - Sort catalog 2 before matching.
    %                                  Default is false.
    %            'SortCol'           - Column index in 'ColSphere#' or
    %                                  'ColPlanar#' by which to sort.
    %                                  Default is 2.
    %            'TestSort2'         - Test that catalog 2 is sorted as
    %                                  required by the MEX matcher.
    %                                  Default is false.
    %            'CreateNewObj'      - Logical indicating whether row
    %                                  selection should create a new object
    %                                  when building the matched output
    %                                  catalogs.
    %                                  Default is true.
    %            'OutType'           - Output object type. If empty, use the
    %                                  class of Obj1. Supported options are
    %                                  AstroImage and AstroCatalog families.
    %                                  Default is [].
    %
    % Output : - Matched2 : Object array of length max(numel(Obj1),
    %                       numel(Obj2)). Each element contains the catalog
    %                       extracted from Obj2, keeping only the rows that
    %                       match sources in the corresponding Obj1 catalog.
    %          - Ind1     : Structure array returned by matchInd for Obj1
    %                       matched against Obj2. Each element contains:
    %                       .Ind    - Indices of the matched sources in Obj2
    %                                 for each source in Obj1.
    %                       .Dist   - Distances to the matched sources.
    %                       .Nmatch - Number of matches within the search
    %                                 radius for each Obj1 source.
    %          - Matched1 : Same as Matched2, but in the reverse direction:
    %                       catalogs extracted from Obj1, keeping only rows
    %                       that match sources in Obj2.
    %                       Returned only if requested.
    %          - Ind2     : Structure array returned by matchInd for Obj2
    %                       matched against Obj1.
    %                       Returned only if requested.
    %
    % Notes  : - Matching is delegated to imProc.match.matchInd.
    %          - Unmatched rows are handled by selectRows according to the
    %            'IgnoreNaN' option.
    %          - The exact convention for unmatched indices and distances is
    %            inherited from imProc.match.matchInd and the underlying
    %            MEX matchers.
    %          - If one input is scalar and the other is an array, the
    %            scalar object is matched against all elements of the other
    %            input.
    %
    % Author : Eran Ofek (2026 Apr)
    % Example: [Matched2, Ind1] = imProc.match.matchCat(Obj1, Obj2);
    %          [Matched2, Ind1, Matched1, Ind2] = imProc.match.matchCat(Obj1, Obj2);

    arguments
        Obj1
        Obj2
       
        %-- Args of matchInd ---
        Args.SearchRadius      = 1.5;
        Args.SearchRadiusUnits = 'arcsec';
        Args.IsSpherical       = true;
        Args.Units             = []; % char array
        Args.ColSphere1        = {'RA','Dec'};
        Args.ColSphere2        = {'RA','Dec'};
        Args.ColPlanar1        = {'X','Y'};
        Args.ColPlanar2        = {'X','Y'};
        Args.Sort1             = false;
        Args.Sort2             = false;
        Args.SortCol           = 2;
        Args.TestSort2         = false;  % test that list 2 is sorted

        Args.CreateNewObj      = true;  % create a new deep copy of the object / don't change unless you understand what you are doing
        Args.OutType           = []; % if empty, select output type by class of Obj1

    end

    Nobj1 = numel(Obj1);
    Nobj2 = numel(Obj2);
    Nmax  = max(Nobj1, Nobj2);

    if isempty(Args.OutType)
        OutType = class(Obj1);
    else
        OutType = Args.OutType;
    end

    if nargout<3
        [Ind1] = imProc.match.matchInd(Obj1, Obj2, ...
                                        'SearchRadius',      Args.SearchRadius, ...
                                        'SearchRadiusUnits', Args.SearchRadiusUnits, ...
                                        'IsSpherical',       Args.IsSpherical, ...
                                        'Units',             Args.Units, ...
                                        'ColSphere1',        Args.ColSphere1, ...
                                        'ColSphere2',        Args.ColSphere2, ...
                                        'ColPlanar1',        Args.ColPlanar1, ...
                                        'ColPlanar2',        Args.ColPlanar2, ...
                                        'Sort1',             Args.Sort1, ...
                                        'Sort2',             Args.Sort2, ...
                                        'SortCol',           Args.SortCol, ...
                                        'TestSort2',         Args.TestSort2);

        CalcM1       = false;

    else
        [Ind1, Ind2] = imProc.match.matchInd(Obj1, Obj2, ...
                                        'SearchRadius',      Args.SearchRadius, ...
                                        'SearchRadiusUnits', Args.SearchRadiusUnits, ...
                                        'IsSpherical',       Args.IsSpherical, ...
                                        'Units',             Args.Units, ...
                                        'ColSphere1',        Args.ColSphere1, ...
                                        'ColSphere2',        Args.ColSphere2, ...
                                        'ColPlanar1',        Args.ColPlanar1, ...
                                        'ColPlanar2',        Args.ColPlanar2, ...
                                        'Sort1',             Args.Sort1, ...
                                        'Sort2',             Args.Sort2, ...
                                        'SortCol',           Args.SortCol, ...
                                        'TestSort2',         Args.TestSort2);

        CalcM1       = true;
    end

    switch lower(OutType)
        case {'astroimage', 'astrozogy', 'astrodiff'}
           Matched2 = AstroImage([Nmax, 1]);
           if CalcM1
               Matched1 = AstroImage([Nmax, 1]);
           end
        case {'astrocatalog', 'astrotable'}
            Matched2 = AstroCatalog([Nmax, 1]);
            if CalcM1
               Matched1 = AstroCatalog([Nmax, 1]);
           end
        case 'table'
            error('OutType table not supported');

        otherwise
            error('Unknown OutType option: %s',OutType);
    end


    for Imax=1:1:Nmax
        Iobj1 = min(Imax, Nobj1);
        Iobj2 = min(Imax, Nobj2);

        % get catalogs : AstroCatalog / AstroImage / ...
        
        Cat2  = Obj2(Iobj2).getCatData;

        Matched2(Imax).setCatData( Cat2.selectRows(Ind1(Iobj1).Ind, 'IgnoreNaN',true, 'CreateNewObj',Args.CreateNewObj) );
        
        if CalcM1
            Cat1  = Obj1(Iobj1).getCatData;
            Matched1(Imax).setCatData( Cat1.selectRows(Ind2(Iobj2).Ind, 'IgnoreNaN',true, 'CreateNewObj',Args.CreateNewObj) );
        end
        
    end

end
