% Functions and Classes list for the pipeline package
% Author : autogenerated (Jun 2023)
%            pipeline.allFunList - Functions and Classes list for the pipeline package
%              pipeline.unitTest - Package Unit-Test
%      pipeline.galex.allFunList - Functions and Classes list for the pipeline.galex package
%       pipeline.galex.procGALEX - 
%    pipeline.generic.allFunList - Functions and Classes list for the pipeline.generic package
% pipeline.generic.imagesSequence2LC - Generate light curves of stationary sources from a sequence of raw images
% pipeline.generic.multiRaw2procCoadd - Basic processing of a multiple raw image, of the same field, into a processed images and coadd image
%     pipeline.generic.procCoadd - Coadd a list of processed images, estimate background and find sources in the coadd images.
% pipeline.generic.procMergeCoadd - Given a list of processed images, merged their catalogs, coadd
% pipeline.generic.singleRaw2proc - Basic processing of a single raw image into a processed image
%      pipeline.generic.unitTest - Package Unit-Test
%       pipeline.last.allFunList - Functions and Classes list for the pipeline.last package
% pipeline.last.constructArchiveDir - Construct archive directory names for LAST local computers
%  pipeline.last.constructCamDir - Construct a camera data directory name on LAST computers
% pipeline.last.constructProjName - Construct full LAST ProjName for ImagePath file names
%    pipeline.last.forcedPhotAll - Execute forcedPhot on all images found in some directory structure.
% pipeline.last.lastSubEpochsPipeline - 
% pipeline.last.movingAsteroidCropLC - Analyze a full farme LAST images
%        pipeline.last.pipeDemon - 
%    pipeline.last.pointingModel - Calculate pointing model from a lsit of images and write it to a configuration file.
%     pipeline.last.prepDarkFlat - Look for dark images and combine when ready
% pipeline.last.prepDidymosMovie - 
%   pipeline.last.prepMasterDark - Look for new files and prepare master dark for LAST
%   pipeline.last.prepMasterFlat - Look for new files and prepare master flat for LAST
% pipeline.last.realTimeAsteroidLC1 - Analyze a full farme LAST images
%      pipeline.last.runPipeLAST - Script for running the LAST pipeline
% pipeline.last.singleFullImageReduction - Analyze a full farme LAST images
%         pipeline.last.unitTest - Package Unit-Test
% pipeline.lastAnalysis.allFunList - Functions and Classes list for the pipeline.lastAnalysis package
% pipeline.lastAnalysis.inspectAsteroidsPM - Inspect all asteroid candidates in  proc dirs
% pipeline.lastAnalysis.searchVarMerged - 
%   pipeline.ultrasat.allFunList - Functions and Classes list for the pipeline.ultrasat package
%     pipeline.ultrasat.unitTest - Package Unit-Test
%             pipeline.DemonLAST - ImagePath - A class for generating stand storing image/path names
 help pipeline.allFunList