% Functions and Classes list for the tools.class package
% Author : autogenerated (Jan 2025)
%         tools.class.char2int64 - convert an array of numerical values written as char to int64
%   tools.class.isempty_property - Check if a certain object property is empty in a matrix of objects
 help tools.class.allFunList