% Functions and Classes list for the VO.Chandra package
% Author : autogenerated (Jan 2025)
%            VO.Chandra.acis_psf - Read and interpolate the Chandra ACIS-S/ACIS-I PSF.
%          VO.Chandra.allFunList - Functions and Classes list for the VO.Chandra package
%     VO.Chandra.build_obsid_cat - Construct a catalog of all Chandra observations
% VO.Chandra.build_obsid_cat_old - Construct a catalog of all Chandra observations
%    VO.Chandra.ciao_extractspec - Prepare the ARF and MRF Chandra files required for X-ray spectroscopy.
%         VO.Chandra.getACIS_PSF - get a MARX-simulated Chandra ACIS PSF for a given ACIS chip: a 2D stamp or a full 5D object
%       VO.Chandra.getSrcPhotons - Get Chandra photons of a single source over all ObsIDs.
%   VO.Chandra.processChandraPSF - process the PSF fits files produced with MARX and make a .mat object
%    VO.Chandra.run_ciao_command - RUN CIAO command on single or multiple, or all Chandra directories
%            VO.Chandra.wget_all - wget all Chandra observations in cats.X.ChandraObs
%          VO.Chandra.wget_obsid - Get all the files associated with a Chandra ObsID
%      VO.Chandra.wget_obsid_old - Get all the files associated with a Chandra ObsID
 help VO.Chandra.allFunList