% Functions and Classes list for the ImUtil.X package
% Author : autogenerated (Jun 2023)
%    ImUtil.X.acis_search_flares - SHORT DESCRIPTION HERE
%            ImUtil.X.allFunList - Functions and Classes list for the ImUtil.X package
%                ImUtil.X.coo2xy - X-Ray event file J2000 equatorial coordinates to X/Y.
%     ImUtil.X.filter_energy_dep - Filter a Poisson-noise image with energy dependent PSF and background.
%         ImUtil.X.find_badtimes - Find bad times in X-ray event files by identyfing access of events.
%     ImUtil.X.poiss_f_threshold - Find the flux threshold for Poisson matched filter
%     ImUtil.X.read_chandra_acis - SHORT DESCRIPTION HERE
% ImUtil.X.read_chandra_acis_old - Read Chandra ACIS event files associated with a Chandra ObsID.
%                ImUtil.X.xy2coo - X-Ray event file X/Y to J2000 equatorial coordinates.
 help ImUtil.X.allFunList