% Functions and Classes list for the tools.array.mex.obsolete package
% Author : autogenerated (Jan 2025)
% tools.array.mex.obsolete.countVal - Given an N-D Array, count the number of elements that are exactly equal to the value in Val.
 help tools.array.mex.obsolete.allFunList