% Functions and Classes list for the timeSeries.filter package
% Author : autogenerated (Jan 2025)
%    timeSeries.filter.filterStd - Calculate the 1-D std filter on equally spaced time series
%  timeSeries.filter.fitFilter1D - Matched filter fitting of a 1-D time series with a template bank.
% timeSeries.filter.runMeanFilter - Apply a running mean top-hat filter to data and normalize results by std.
 help timeSeries.filter.allFunList