%==========================================================================
% Project     : ULTRASAT SOC
% Filename    : soc_slew_matlab.py
% Author      : Chen Tishler
% Created     : 02/11/2025
% Modified    : 04/11/2025
% Description : MATLAB service to calculate slew time between targets
%==========================================================================
%
% MATLAB R2023a is required.
%
% Build EXE file by running this batch from source folder:
% 
%       _build.bat
%
% Notes:
%    - mcc generates EXE file which is a self-extract ZIP, with all required source files.
%    - It is not possible to call addpath() in deployed application!
%    - snakeyaml-1.9.jar should be in the EXE folder.
%    - ASTROPACK_CONFIG_PATH environment must be set
%
% See: https://www.mathworks.com/help/compiler/create-and-install-a-standalone-application-from-matlab-code.html
% See: https://www.mathworks.com/help/compiler/mcc.html
% See: https://www.mathworks.com/help/compiler/isdeployed.html
%
% NOTE: To run in from within MATLAB, you have to change folder
%       to the folder of this file (i.e. app_slew/)
%==========================================================================

function soc_slew_matlab()
    % SlewCalc App - Main function

    global SOC_PATH;

    % Set logfile name
	fprintf('soc_slew_matlab started, V1.00 (04/11/2025)\n');
    LogFile.getSingleton('FileName', 'soc_slew_matlab');
            
    % Print some info
    fprintf('getPid: %d\n', tools.os.getPid());
    fprintf('getProcessName: %s\n', tools.os.getProcessName());
    fprintf('getCmdLine: %s\n', tools.os.getCmdLine());

    % Check if deployed (i.e. running as EXE file, generated by mcc, see _build.bat)
    if isdeployed
        fprintf('soc_slew_matlab: isdeployed = TRUE\n');
        locate_externapp = which(fullfile('soc_slew_matlab.exe'));
        fprintf('which: %s\n', locate_externapp);
    end    
    
    if ismcc
        fprintf('soc_slew_matlab: ismcc = TRUE\n');
    end           

    % Get the SOC_PATH environment variable, if not set, use default
    SOC_PATH = getenv('SOC_PATH');
    if isempty(SOC_PATH)
        if ispc
            SOC_PATH = 'c:/soc';
        else
            SOC_PATH = '/var/opt/soc';
        end
    end

    % Test that we can find file 'Gal_Sc.txt'
    if isdeployed
        fprintf('\n\n================================== Check started\n');
        FName = 'Gal_Sc.txt';

        % Before loadMap - Check which() and fileMapFind()
        fprintf('Checking: Before loadMap - calling which( %s ) :\n', FName);
        which(FName)
        MatFile = fileMapFind(FName, 'Assert', false);
        fprintf('Checking: Before loadMap - fileMapFind( %s ) - %s\n\n', FName, MatFile);

        % Load the saved FileMap object, it was created by calling FileMap
        % from **startup.m**, and used to map files to folders, because
        % MATLAB's addpath() does not work from deployd code.
        FMap = FileMap.getSingleton();
        FMap.StorageFileName = fullfile(SOC_PATH, 'slew', 'slew_matlab', 'AstroPackFileMap_1.mat');
        FMap.loadMap();    
        fprintf('\nCalling FileMap.addPathFolders ...\n');
        FMap.addPathFolders();    
        fprintf('\nCalling FileMap.scanFolders ...\n');
        FMap.scanFolders();

        % After loadMap - Check which() and fileMapFind()
        fprintf('\nChecking: AFTER loadMap - calling which( %s ) :\n', FName);
        which(FName)    
        MatFile = fileMapFind(FName, 'Assert', false);
        fprintf('Checking: AFTER loadMap - fileMapFind( %s ) - %s\n', FName, MatFile);

        % Check if we can find file 'AstFilterCat.mat'
        FName = 'AstFilterCat.mat';
        MatFile = fileMapFind(FName, 'Assert', false);
        fprintf('Checking: AFTER loadMap - fileMapFind( %s ) - %s\n', FName, MatFile);

        fprintf('\n\n================================== Check done\n\n\n');
    end

    % Create component to trigger Config loading
    fprintf('Creating Comp\n');
    Comp = Component();
    fprintf('Config.Path: %s\n', Comp.Config.Path);
    fprintf('Comp.Config.Data.MsgLogger.FileName: %s\n', Comp.Config.Data.MsgLogger.FileName);

    % Call UltrasatPerf() to force the mcc compiler linking this class and
    % its related sources. Otherwise we will get this error:
    %     09:50:58.133 [DBG] doProcessSnr: creating UltrasatPerf2GUI
    %     09:50:58.176 [DBG] UltrasatPerf2GUI: UltrasatPerf2GUI:load: c:\soc\snr\snr_matlab\P90_UP_test_60_ZP_Var_Cern_21.mat
    %     Warning: Variable 'UP' originally saved as a UltrasatPerf cannot be instantiated as an object and will be read in as a uint32.    
    fprintf('Calling: Perf = UltrasatPerf(Init, false);\n');    
    Perf = UltrasatPerf('Init', false);
    fprintf('UltrasatPerf done\n');
    
    %try
        %if ~isdeployed
            fprintf('Calling mainLoop\n');
            mainLoop();
            fprintf('Returned from mainLoop\n');
        %end
    %catch
        %fprintf('soc_slew_matlab exception\n');
    %end
    
    fprintf('soc_slew_matlab done\n');
end

%==========================================================================

function Result = mainLoop()
    % mainLoop - Blocking function
    global SOC_PATH;

    % Set the log level
    MsgLogger.setLogLevel(LogLevel.Info, 'type', 'file');
    MsgLogger.setLogLevel(LogLevel.Info, 'type', 'disp');            

    % Set the input path
    InputPath = fullfile(SOC_PATH, 'slew', 'input');

    % Log the start of the main loop
    io.msgLog(LogLevel.Info, '=========== Slew mainLoop started - Input folder: %s', strrep(InputPath, '\', '\\'));

    % Create the FileProcessor object
    fp = FileProcessor('InputPath', InputPath, 'InputMask', '*.json');
    fp.ProcessFileFunc = @fileProcessorCallback;
    fp.EnableDelete = true;
    fp.WatchdogFileName = 'soc_slew_matlab_watchdog.txt';
    fp.WatchdogInterval = 10;
    %fp.MaxRunTime = hours(8);

    % Input loop will call FileProcessorCallback (below) for each input
    % file found in the folder
    % Note: Blocking function
    fp.process('DelaySec', 0.1);
    
    io.msgStyle(LogLevel.Test, '@passed', 'Slew mainLoop passed');                          
    Result = true;
end

%------------------------------------------------------------------------

function Result = processItem(item)
    % Process item, return result
    % See ultrasat.git/python/prj/src/webapps/webapp_snr/rest_snr_server1.py
    
    % Input   : - item - struct Item with op, x, y, json_text fields
    %           * Pairs of ...,key,val,...
    %             The following keys are available:            			            
    %                      
    % Output  : struct ResponseMessage with message, result fields
    % Author  : Chen Tishler (2021)
    % Example : 
    %   item = struct('op', 'add', 'x', 1, 'y', 2);
    %   out = processItem(item);
    %   disp(out);
    % 
    
    % Prepare output struct, default values, will be used if exception is thrown
    out = struct;
    out.message = 'MATLAB: Exception in processItem';
    out.result = -1;   
    out.json_text = '';  
    
    try
        % Log the operation
        out.message = sprintf('MATLAB: op: %s', item.op);
        
        % Tester - simple calculator add/mul/sub/div        
        if strcmp(item.op, 'add')
            out.result = item.x + item.y;
        elseif strcmp(item.op, 'mul')
            out.result = item.x * item.y;
        elseif strcmp(item.op, 'sub')
            out.result = item.x - item.y;
        elseif strcmp(item.op, 'div')
            if item.y ~= 0
                out.result = item.x / item.y;
            else
                ME = MException('Slew:process', 'Division by zero');
                throw(ME);
            end

        % Call the Slew calculator, input is JSON text, output is struct            
        elseif strcmp(item.op, 'slew')            
            out = processSlewJson(item.json_text);
        elseif strcmp(item.op, 'slew_batch')            
            out = processSlewJsonBatch(item.json_text);            
        else
            strcpy(out.message, 'MATLAB: unknown op');
        end
    catch Ex
        out.message = sprintf('MATLAB: exception: %s', Ex.message);
    end
    
    Result = out;
end

%------------------------------------------------------------------------

function fileProcessorCallback(FileName)
    % FileProcessorCallback - Callback function for FileProcessor
    % Input   : - FileName - string with the name of the file to be processed
    % Output  : - None
    % Author  : Chen Tishler (2021)
    % Example : 
    %   fileProcessorCallback('input/item.json');
    % 
    
    % Log the start of the callback
    io.msgLog(LogLevel.Info, 'FileProcessorCallback started: %s', strrep(FileName, '\', '\\'));
      
    % Set the temporary and output file names
    TmpFileName = strcat(FileName, '.out.tmp');
    OutFileName = strcat(FileName, '.out');

    % Read the input JSON file
    try
        fid = fopen(FileName);
        raw = fread(fid, inf);
        str = char(raw');
        fclose(fid);
    catch Ex
        io.msgLog(LogLevel.Error, 'FileProcessorCallback: Error reading file %s: %s', FileName, Ex.message);
        out = struct;
        out.message = sprintf('MATLAB: Exception reading file %s: %s', FileName, Ex.message);
        out.result = -1;
        out.json_text = '';
        return;
    end
    
    % Parse JSON from string to struct
    try
        io.msgLog(LogLevel.Debug, 'JSON: %s', str);
        item = jsondecode(str);
    catch Ex
        io.msgLog(LogLevel.Error, 'FileProcessorCallback: Error parsing JSON from file %s: %s', FileName, Ex.message);
        out = struct;
        out.message = sprintf('MATLAB: Exception parsing JSON from file %s: %s', FileName, Ex.message);
        out.result = -1;
        out.json_text = '';
        return;
    end
   
    % Process the request
    try
        out = processItem(item);
    catch Ex
        io.msgLog(LogLevel.Error, 'FileProcessorCallback: Error calling processItem: %s', Ex.message);
        out = struct;
        out.message = sprintf('MATLAB: Exception calling processItem: %s', Ex.message);        
        out.result = -1;           
    end

    % Write output JSON file
    try
        io.msgLog(LogLevel.Debug, 'Out.message: %s, result: %d, json_text: %s', out.message, out.result, out.json_text);        
        out_json = jsonencode(out);
        fid = fopen(TmpFileName, 'wt');
        fprintf(fid, out_json);
        fclose(fid);
    catch Ex
        io.msgLog(LogLevel.Error, 'FileProcessorCallback: Error writing file %s: %s', TmpFileName, Ex.message);
        return;
    end

    % Rename final file to output extension
    try
        io.msgLog(LogLevel.Debug, 'Rename output %s -> %s', strrep(TmpFileName, '\', '\\'), strrep(OutFileName, '\', '\\'));
        movefile(TmpFileName, OutFileName);
    catch Ex
        io.msgLog(LogLevel.Error, 'FileProcessorCallback: Error renaming file %s -> %s: %s', strrep(TmpFileName, '\', '\\'), strrep(OutFileName, '\', '\\'), Ex.message);
        return;
    end

    % Final log
    io.msgLog(LogLevel.Info, 'FileProcessorCallback done: %s', strrep(FileName, '\', '\\'));
end
