CREATE TABLE last.proc_images
(
    `id_raw` Int64,
    `id_proc` Int64,
    `id_dark` Int64,
    `id_flat` Int64,
    `ra` Float64,
    `dec` Float64,
    `m_ra` Float32,
    `m_dec` Float32,
    `m_ha` Float32,
    `m_jra` Float32,
    `m_jdec` Float32,
    `m_jha` Float32,
    `m_ara` Float32,
    `m_adec` Float32,
    `m_aha` Float32,
    `m_adra` Float32,
    `m_addec` Float32,
    `m_adha` Float32,
    `airmass` Float32,
    `trk_ra` Float32,
    `trk_dec` Float32,
    `upix_partition` UInt64,
    `upix_low` UInt64,
    `upix_high` UInt64,
    `dateobs` DateTime64(3),
    `jd_start` Float64,
    `midjd` Float64,
    `lst` Float64,
    `exptime` Float32,
    `naxis1` Int16,
    `naxis2` Int16,
    `obslon` Float32,
    `obslat` Float32,
    `obsalt` Float32,
    `filter` String,
    `object` String,
    `fieldid` String,
    `counter` Int16,
    `binx` Float32,
    `biny` Float32,
    `nodenumb` Int16,
    `mountnum` Int8,
    `camnum` Int8,
    `ccdid` Int16,
    `cropid` Int16,
    `subdir` String,
    `server` String,
    `camtemp` Float32,
    `camcool` Float32,
    `origgain` Float32,
    `camgain` Float32,
    `camoffs` Float32,
    `saturval` Float32,
    `nonlin` Float32,
    `readnoi` Float32,
    `darkcur` Float32,
    `temp_in` Float32,
    `temp_out` Float32,
    `temp_mnt` Float32,
    `hum_in` Int8,
    `hum_out` Int8,
    `pressure` Float32,
    `cloud` Int8,
    `transper_z` Int8,
    `fwhm_dimm_z` Float32,
    `focus` Int32,
    `prvfocus` Int32,
    `pipever` String,
    `config_id` String,
    `origsec_xmin` Int16,
    `origsec_xmax` Int16,
    `origsec_ymin` Int16,
    `origsec_ymax` Int16,
    `origusec_xmin` Int16,
    `origusec_xmax` Int16,
    `origusec_ymin` Int16,
    `origusec_ymax` Int16,
    `uniqsec_xmin` Int16,
    `uniqsec_xmax` Int16,
    `uniqsec_ymin` Int16,
    `uniqsec_ymax` Int16,
    `meanbck` Float32,
    `medbck` Float32,
    `stdbck` Float32,
    `meanvar` Float32,
    `medvar` Float32,
    `bckmetho` String,
    `fwhm` Float32,
    `med_a` Float32,
    `med_b` Float32,
    `med_th` Float32,
    `nsrc` Int16,
    `ph_zp` Float32,
    `ph_col1` Float32,
    `ph_medc` Float32,
    `ph_rms` Float32,
    `ph_nsrc` Int32,
    `ph_magsy` String,
    `limmag` Float32,
    `backmag` Float32,
    `ph_magt` String,
    `ph_magte` String,
    `pt_1_1` Float32,
    `pt_rms` Float32,
    `pt_nsrc` Int16,
    `ast_nsrc` Int32,
    `ast_arms` Float32,
    `ast_errm` Float32,
    `ctype` String DEFAULT 'TPV',
    `crpix1` Float32,
    `crpix2` Float32,
    `crval1` Float32,
    `crval2` Float32,
    `cd1_1` Float32,
    `cd1_2` Float32,
    `cd2_1` Float32,
    `cd2_2` Float32,
    `ra1` Float32,
    `ra2` Float32,
    `ra3` Float32,
    `ra4` Float32,
    `dec1` Float32,
    `dec2` Float32,
    `dec3` Float32,
    `dec4` Float32,
    `rau1` Float32,
    `rau2` Float32,
    `rau3` Float32,
    `rau4` Float32,
    `decu1` Float32,
    `decu2` Float32,
    `decu3` Float32,
    `decu4` Float32,
    `pv1_0` Float32,
    `pv1_1` Float32,
    `pv1_2` Float32,
    `pv1_3` Float32,
    `pv1_4` Float32,
    `pv1_5` Float32,
    `pv1_6` Float32,
    `pv1_7` Float32,
    `pv1_8` Float32,
    `pv1_9` Float32,
    `pv1_10` Float32,
    `pv2_0` Float32,
    `pv2_1` Float32,
    `pv2_2` Float32,
    `pv2_3` Float32,
    `pv2_4` Float32,
    `pv2_5` Float32,
    `pv2_6` Float32,
    `pv2_7` Float32,
    `pv2_8` Float32,
    `pv2_9` Float32,
    `pv2_10` Float32,
    `optics_cln` Nullable(Float32) COMMENT 'date of last optics cleaning',
    INDEX idx_id_raw id_raw TYPE minmax GRANULARITY 16,
    INDEX idx_id_proc id_proc TYPE minmax GRANULARITY 16,
    INDEX idx_id_dark id_dark TYPE minmax GRANULARITY 16,
    INDEX idx_id_flat id_flat TYPE minmax GRANULARITY 16,
    INDEX idx_ra ra TYPE minmax GRANULARITY 16,
    INDEX idx_dec dec TYPE minmax GRANULARITY 16,
    INDEX idx_upix_low upix_low TYPE minmax GRANULARITY 16,
    INDEX idx_upix_high upix_high TYPE minmax GRANULARITY 16,
    INDEX idx_midjd midjd TYPE minmax GRANULARITY 16
)
ENGINE = MergeTree
PARTITION BY upix_partition
ORDER BY upix_low
SETTINGS storage_policy = 'pipeline_policy', index_granularity = 8192