CREATE TABLE last.visit_src
(
    `id_visit_src` Int64,
    `id_uniq_src` Int64,
    `id_cat_src` Int64,
    `id_visit_im` Int64,
    `upix_partition` UInt64,
    `upix_low` UInt64,
    `upix_high` UInt64,
    `is_forced` Bool,
    `jd` Float64,
    `bjd` Float64,
    `baryvel` Float64,
    `ra` Float64,
    `dec` Float64,
    `xpeak` Int16,
    `ypeak` Int16,
    `x` Float32,
    `y` Float32,
    `x1` Float32,
    `y1` Float32,
    `flags` UInt32,
    `x2` Float32,
    `y2` Float32,
    `xy` Float32,
    `sn` Float32,
    `sn_ext1` Nullable(Float32),
    `sn_ext2` Nullable(Float32),
    `sn_delta` Nullable(Float32),
    `sn_1` Float32,
    `sn_2` Float32,
    `sn_3` Float32,
    `sn_4` Float32,
    `sn_5` Float32,
    `flux_aper_1` Float32,
    `fluxerr_aper_1` Float32,
    `mag_aper_1` Float32,
    `magerr_aper_1` Float32,
    `flux_aper_2` Float32,
    `fluxerr_aper_2` Float32,
    `mag_aper_2` Float32,
    `magerr_aper_2` Float32,
    `flux_aper_3` Float32,
    `fluxerr_aper_3` Float32,
    `mag_aper_3` Float32,
    `magerr_aper_3` Float32,
    `flux_psf` Float32,
    `fluxerr_psf` Float32,
    `mag_psf` Float32,
    `magerr_psf` Float32,
    `back_im` Nullable(Float32),
    `var_im` Nullable(Float32),
    `back_annulus` Float32,
    `std_annulus` Float32,
    `mergedcat` UInt32,
    `distmp` Float32,
    `n_det` Float32,
    `nodenumb` Int32,
    `mountnum` Int32,
    `camnum` Int32,
    `cropid` Int32,
    `ingestion_time` Nullable(DateTime64(3)) DEFAULT now(),
    `ingestion_time_jd` Float64,



    `id` UInt128 MATERIALIZED bitOr(bitShiftLeft(CAST(id_visit_im, 'UInt128'), 64), CAST(id_visit_src, 'UInt128')),



    INDEX idx_id_visit_src id_visit_src TYPE minmax GRANULARITY 16,
    INDEX idx_id_uniq_src id_uniq_src TYPE minmax GRANULARITY 16,
    INDEX idx_id_cat_src id_cat_src TYPE minmax GRANULARITY 16,
    INDEX idx_id_visit_im id_visit_im TYPE minmax GRANULARITY 16,
    INDEX idx_upix_low upix_low TYPE minmax GRANULARITY 16,
    INDEX idx_upix_high upix_high TYPE minmax GRANULARITY 16,
    INDEX idx_is_forced is_forced TYPE minmax GRANULARITY 16,
    INDEX idx_jd jd TYPE minmax GRANULARITY 16,
    INDEX idx_ra ra TYPE minmax GRANULARITY 16,
    INDEX idx_dec dec TYPE minmax GRANULARITY 16,
    INDEX idx_sn sn TYPE minmax GRANULARITY 16,
    INDEX idx_mag_aper_3 mag_aper_3 TYPE minmax GRANULARITY 16,
    INDEX idx_mag_psf mag_psf TYPE minmax GRANULARITY 16
)
ENGINE = MergeTree
PARTITION BY upix_partition
ORDER BY upix_high
SETTINGS storage_policy = 'pipeline_policy', index_granularity = 8192