% Functions and Classes list for the tools.hist package
% Author : autogenerated (Jan 2025)
% tools.hist.histcounts2regular_mex - Fast 2D histogram in a regular grid (mex)
%            tools.hist.unitTest - unitTest for tools.hist
% tools.hist.mex.histcounts1regular_mex - 1D histogram of a single/double vector in a regular, equally spaced, grid (fast mex)
 help tools.hist.allFunList