% Functions and Classes list for the timeSeries.obsolete package
% Author : autogenerated (Jun 2023)
%   timeSeries.obsolete.Contents - 
% timeSeries.obsolete.allFunList - Functions and Classes list for the timeSeries.obsolete package
%        timeSeries.obsolete.arp - Fit autoregression model for evently spaced time series. OBSOLETE - use builtin tools
% timeSeries.obsolete.binFullOverlap - Bin light curve with finite ExpTime using only points fully covering
% timeSeries.obsolete.bin_by_eye - Bin data by define bins interactively. OBSOLETE - need to rewrite
% timeSeries.obsolete.calib_flux_lsq - Best fit zeropoints and mean magnitudes to a matrix of magnitudes.
% timeSeries.obsolete.calib_flux_sum - Normalize (calibrate) a matrix of fluxes using sum of flux in each epoch.
%    timeSeries.obsolete.cosbell - Cosine bell function (Obsolete: use timeseries.taper instead)
% timeSeries.obsolete.fitPolyFiniteExpTime - 
% timeSeries.obsolete.fit_polys_deltachi2 - Fit polynomials of various orders to a time series and calculate chi^2
%      timeSeries.obsolete.fmaxs - Find local maxima by diffrentiation
% timeSeries.obsolete.foldingStat - 
%     timeSeries.obsolete.glsper - Calculates The generalized Lomb-Scargle periodogram (Zechmeister 2009).
% timeSeries.obsolete.matched_filter - Matched filter for 1-D time series
% timeSeries.obsolete.mean_plweighted - Power-law weighted mean of a time series.
% timeSeries.obsolete.period_proper - SHORT DESCRIPTION HERE
% timeSeries.obsolete.phot_event_me - --------------------------------------------------------------------
% timeSeries.obsolete.plot_inspect_lc - plot and inspect light curve and power spectrum
% timeSeries.obsolete.plot_period_folder - ------------------------------------------------------------------------------
% timeSeries.obsolete.ps_whitening - --------------------------------------------------------------------------
% timeSeries.obsolete.removeFluxBeforeT0 - Given a LC, remove baseline flux, and any flux detected before t0.
% timeSeries.obsolete.rmsflux_select - Select points in an flux/mag vs. rms like diagram
% timeSeries.obsolete.simulated_elc - Simulated photons light curve
%    timeSeries.obsolete.specwin - Power spectrum window (use timeseries.period instead)
%      timeSeries.obsolete.taper - Generate a taper function
%   timeSeries.obsolete.unitTest - Package Unit-Test
 help timeSeries.obsolete.allFunList