% Functions and Classes list for the timeSeries.interp package
% Author : autogenerated (Jan 2025)
%   timeSeries.interp.allFunList - Functions and Classes list for the timeSeries.interp package
%     timeSeries.interp.interpGP - Interpolate a time series using Gaussian processes
%    timeSeries.interp.sf_interp - Interpolate a time-series using the structure-function-weighted method
% timeSeries.interp.uniformResample - Uniform resampling of a non-evenly spaced time series.
 help timeSeries.interp.allFunList