% Functions and Classes list for the timeSeries.stat package
% Author : autogenerated (Jan 2025)
%     timeSeries.stat.allFunList - Functions and Classes list for the timeSeries.stat package
%   timeSeries.stat.searchFlares - Search flares and eclipses in equally spaced time series
%       timeSeries.stat.stdfilt1 - Standart deviation filter
% timeSeries.stat.vonNeumannStat - Calculate the unbiased von Neumann statistics for a time series.
 help timeSeries.stat.allFunList