classdef MissionModels < soc.api.ModelFactoryBase
    % GetMissionModels - Factory for creating Mission model instances.
    
    methods (Static)
        function model = GetImagingTarget()
            % GetImagingTarget - Creates an instance of ModelBase with empty fields.
            
            % Define the data for the model with all fields set to []
            data = struct(...
                'pk', [], ...
                'target_id', [], ...
                'target_type', [], ...
                'status', [], ...
                'update_time', [], ...
                'ra', [], ...
                'decl', [], ...
                'roll', [], ...
                'start_time', [], ...
                'end_time', [], ...
                'exposure', [], ...
                'image_count', [], ...
                'tiles', [], ...
                'total_seconds', [], ...
                'history', [], ...
                'metadata', [] ...
            );

            % Create and return the model instance
            model = soc.api.ModelBase(data);
        end


        function model = GetApprovedTargetsParams(start_time, end_time)
            % GetApprovedTargetsParams - Creates an instance of ModelBase for approved targets query parameters.
            
            % Ensure datetime fields are converted to ISO 8601 format
            if nargin >= 1 && isa(start_time, 'datetime')
                start_time = datestr(start_time, 'yyyy-mm-ddTHH:MM:SS.FFFZ');
            end
            if nargin >= 2 && isa(end_time, 'datetime')
                end_time = datestr(end_time, 'yyyy-mm-ddTHH:MM:SS.FFFZ');
            end

            % Define the data for the model
            data = struct(...
                'start_time', start_time, ...
                'end_time', end_time ...
            );

            % Create and return the model instance
            model = soc.api.ModelBase(data);
        end
    end
end
