classdef MissionClient < soc.api.ClientBase
    % 
    
    properties
        User            % Logged-in user name
        SessionId       % Unique session Id, generated by the client
        SessionKey      %        
    end


    methods
        function obj = MissionClient(Args)
            arguments          
                Args.SubUrl = '/mission';  % planner_backend  
            end
            ArgsCell = namedargs2cell(Args);
            obj@soc.api.ClientBase(ArgsCell{:});  % Args);  % , 'SubUrl', '/mission');
        end        
        

        % -------------------------------------------------------------------

        function response = login(obj, UserName, Password)
            % 
            obj.msglog('login: user=%s, password=%s - @TODO', UserName, Password);
            return;  % DOTO

            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/login/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end

        function response = logout(obj)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/logout/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end        

        % -------------------------------------------------------------------

        function response = getApprovedTargets(obj, start_time, end_time)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/get_approved_targets/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end


        function response = validate(obj, Targets)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/validate/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end


        function response = submit(obj, Targets)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/submit/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end
        
        
        function response = getExposure(obj, table_name, healpix_indices, start_timestamp, end_timestamp, select_all)
            % Select rows from the Sky Exposure Tracker table.
            % Params:
            %   table_name: Name of the table to select from
            %   healpix_indices: Optional list of HEALPix indices
            %   start_timestamp: Optional start timestamp for filtering
            %   end_timestamp: Optional end timestamp for filtering
            %   select_all: Boolean indicating whether to use select_all
            if nargin < 6
                select_all = false;
            end
            params = soc.api.SkyExposureTrackerModels.SelectParams(table_name, healpix_indices, start_timestamp, end_timestamp, select_all);
            response = obj.postRequest('/get_exposure', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end

        
        % -------------------------------------------------------------------

        function response = getPlansList(obj, Args)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/get_plans_list/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end


        function response = loadPlan(obj, Args)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/load_plan/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end


        function response = savePlan(obj, Args)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/save_plan/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end


        function response = deletePlan(obj, Args)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/delete_plan/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end


        function response = getPlanStatus(obj, Args)
            % 
            params = soc.api.MissionModels.GetApprovedTargetsParams(start_time, end_time);
            response = obj.postRequest('/get_plan_status/', params.Data);
            response.ok = isfield(response, 'status') && strcmp(response.status, 'ok');
        end             

        % -------------------------------------------------------------------

    end
end

