% Functions and Classes list for the ultrasat package
% Author : autogenerated (May 2022)
%              ultrasat.Cerenkov - Calculate the Cerenkov spectrum generated in a lens
% ultrasat.GEO_object_visibility - SHORT DESCRIPTION HERE
% ultrasat.ULTRASAT_restricted_visibility - SHORT DESCRIPTION HERE
%            ultrasat.allFunList - Functions and Classes list for the ultrasat package
%             ultrasat.dEdX_calc - Calculate dE/dX as a function of energy
%            ultrasat.event_rate - Calculate event rate for ULTRASAT given event and host abs. mag.
% ultrasat.geostat_electrons_spec_flux - Return spectral model for electron flux in geostationary orbit
%      ultrasat.optic_comparison - 
%              ultrasat.unitTest - Package Unit-Test
%        ultrasat.wget_goes_data - wget GOES partcles flux data
%            ultrasat.zodiac_bck - Calculate the zodi calibrated spectrum and magnitude at a given position.
%          ultrasat.zodiac_bck_V - Get the Zodiac V light surface brightness as a function of coordinates
%       ultrasat.zodiac_spectrum - Get the Zodiac light spectrum
 help ultrasat.allFunList