% Functions and Classes list for the ultrasat package
% Author : autogenerated (Jan 2025)
%                 ultrasat.ADU2e - convert ULTRASAT ADU into the count number (electrons)
%              ultrasat.Cerenkov - Calculate the Cerenkov spectrum generated in a lens
% ultrasat.GEO_object_visibility - SHORT DESCRIPTION HERE
%         ultrasat.LCS_placement - 
% ultrasat.ULTRASAT_restricted_visibility - SHORT DESCRIPTION HERE
% ultrasat.ULTRASAT_visibility_maps - calculate and plot uninterrupted ULTRASAT visibilities for the whole sky
% ultrasat.ULTRASAT_visibility_maps_LCS - calculate and plot uninterrupted ULTRASAT visibilities for the whole sky
%            ultrasat.allFunList - Functions and Classes list for the ultrasat package
%      ultrasat.calibrationStars - provides a structure with calibration star spectra and coordinates
% ultrasat.convertGALEXdistribution - makes a .mat object containing ULTRASAT magnitudes
%               ultrasat.costTOO - this is a cost function of spherical region coverage with circles:
%             ultrasat.dEdX_calc - Calculate dE/dX as a function of energy
%                 ultrasat.e2ADU - convert ULTRASAT image count number (electrons) into the ADU output number
%            ultrasat.event_rate - Calculate event rate for ULTRASAT given event and host abs. mag.
%         ultrasat.extended2List - convert an extended source into a list of point-likes
% ultrasat.geostat_electrons_spec_flux - Return spectral model for electron flux in geostationary orbit
%       ultrasat.getULTRASAT_PSF - get a spectrum-weighted ULTRASAT PSF stamp from pre-built libraries
%                ultrasat.jitter - Blur an array of ULTRASAT PSFs due to the S/C jitter
%         ultrasat.measureLabPSF - measure PSF characteristics of an ULTRASAT detector image of a laboratory point source
%      ultrasat.optic_comparison - 
%         ultrasat.pointings4TOO - construct ULTRASAT pointings to fill a given sky polygon
% ultrasat.psf_information_content - characterize information content loss when using various ULTRASAT PSFs
%  ultrasat.scheduleAllSkySurvey - distribute AllSky observations for a given start time, grid of pointings, and a given set of constraints
%   ultrasat.simulateKeplerField - simulate an ULTRASAT image from of the Kepler field from the input star catalog
%      ultrasat.simulateOmegaCen - simulate an ULTRASAT image from of the Omega Cen field from the input star catalog
% ultrasat.simulate_ULTRASAT_image - Simulate an ULTRASAT image of a realistic distribution of sky sources
%      ultrasat.umergeTileImages - Make a 4-tile ULTRASAT image from 4 separate tile images
%              ultrasat.unitTest - Package Unit-Test
%                  ultrasat.usim - Make a simulated ULTRASAT image from a source catalog
%           ultrasat.weightedPSF - make a .mat library of spectrum-weighted ULTRASAT PSFs for a set of spectra and a range of radial distances
%      ultrasat.weightedPSFindex - 1. build an array of spectra for ULTRASAT PSF weighting or 2. find the index of a particular spectrum in this array
%        ultrasat.wget_goes_data - wget GOES partcles flux data
%            ultrasat.zodiac_bck - Calculate the zodi calibrated spectrum and magnitude at a given position.
%          ultrasat.zodiac_bck_V - Get the Zodiac V light surface brightness as a function of coordinates
%       ultrasat.zodiac_spectrum - Get the Zodiac light spectrum
% ultrasat.planner.collectAlertStatistics - 
%    ultrasat.planner.plannerToO - automatic planner of a ToO
%      ultrasat.planner.uplanner - 
% ultrasat.planner.gui.MainModule - ==========================================================================
% ultrasat.planner.plannerTools.ApprovedTargetSchedule - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.CalibrationObjects - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.CameraSetup - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.ExternalSurveyMaps - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.ExtinctionMaps - classdef ExtinctionMaps < PlannerToolBase
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.ObservedTargetsMap - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.ReferenceImages - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.RegionCoverage - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.SkyCatalogs - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.SlewCalculator - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.SnrCalculator - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.TargetScheduler - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.Validator - 
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.plannerTools.Visibility - classdef Visibility < PlannerToolBase
% ultrasat.planner.plannerTools.debug - 
% ultrasat.planner.plannerTools.unitTest - Result = true;
% ultrasat.planner.uplanner-2025-01-07 - 
%  ultrasat.planner.uplanner_def - classdef uplanner < Component
%        ultrasat.tools.calcSlew - Calculate the ULTRASAT slew time between two coordinates.
%    ultrasat.tools.expectedRoll - Calculate ULTRASAT's expected roll (aka position angle) for a given sky coordinates at time JD.  slew time between two coordinates.
%      ultrasat.tools.extinction - calculate averaged extinction in the ULTRASAT band for a list of coordinates
%   ultrasat.tools.getFOVcatalog - get an extract of GAIA catalog for the given ULTRASAT position
% ultrasat.tools.getFOVcatalogWD - get an extract of GAIA catalog for the given ULTRASAT position
%    ultrasat.tools.getFOVcircle - get approximate coordinates of the ULTRASAT FOV circle given its center
%   ultrasat.tools.getFOVcorners - get coordinates of the ULTRASAT FOV corners given its center and roll angle
%             ultrasat.SnrGuiIni - 
 help ultrasat.allFunList