% Functions and Classes list for the VO.SDSS.MaNGA package
% Author : autogenerated (May 2022)
%       VO.SDSS.MaNGA.wget_manga - wget SDSS/MaNGA spectral cube FITS files.
 help VO.SDSS.MaNGA.allFunList