% Functions and Classes list for the timeSeries.fit package
% Author : autogenerated (Jun 2023)
%      timeSeries.fit.allFunList - Functions and Classes list for the timeSeries.fit package
%       timeSeries.fit.fitPeriod - fit a light curve with an harmonic (sin/cos) series
%      timeSeries.fit.fitPolyHyp - Hypothesis testing between fitting polynomials of various degrees to
 help timeSeries.fit.allFunList