% Functions and Classes list for the timeSeries.fold package
% Author : autogenerated (Jun 2023)
%     timeSeries.fold.allFunList - Functions and Classes list for the timeSeries.fold package
%  timeSeries.fold.extract_phase - Extract observations take at some phase range
%        timeSeries.fold.folding - Folding a time series by some period
% timeSeries.fold.folding_solarsys - Folding a time series for a solar system object
 help timeSeries.fold.allFunList