% Functions and Classes list for the VO.CoRoT package
% Author : autogenerated (Jan 2025)
%            VO.CoRoT.allFunList - Functions and Classes list for the VO.CoRoT package
%       VO.CoRoT.read_corot_file - Read CoRoT file
%     VO.CoRoT.read_corot_master - Read CoRoT master file
 help VO.CoRoT.allFunList