% Functions and Classes list for the imUtil.calib package
% Author : autogenerated (Jan 2025)
%        imUtil.calib.allFunList - Functions and Classes list for the imUtil.calib package
% imUtil.calib.calibDesignMatrix - Build design matrix for relative photometric calibration
%  imUtil.calib.equaliseLineMean - equalise an image by compensating, line by line, the average of the line
% imUtil.calib.fitTransmissionZP - 
%      imUtil.calib.fit_overscan - fit the overscan region in an image and subtract
%      imUtil.calib.fit_rmsCurve - One line description
%        imUtil.calib.lsqRelPhot - Perform relative photometry calibration using the linear least square method.
% imUtil.calib.nonlinearityCorrection - Apply a flux non-linearity correction to a matrix image.
% imUtil.calib.pixel_flat_response - Fit the pixel response to light as a function of intensity in a cube of images
%      imUtil.calib.resid_vs_mag - Fit residuals vs. mag and flag good data (not outliers).
% imUtil.calib.simplePhotometricZP - Simple photometric ZP solver
%          imUtil.calib.unitTest - unitTest for the imUtil.calib package
 help imUtil.calib.allFunList