% Functions and Classes list for the tools.array package
% Author : autogenerated (Jun 2023)
%         tools.array.allFunList - Functions and Classes list for the tools.array package
%            tools.array.and_mat - Perform logical and operation between all the columns or rows of a matrix
%            tools.array.and_nan - Logical function "and" for NaNs.
%       tools.array.array_select - Select lines in an array which columns satisfay some criteria.
%        tools.array.assoc_range - Index of points in each bin.
%       tools.array.bitand_array - Perform a bitand operation along all elements in an array.
%        tools.array.bitor_array - Perform a bitor operation along all elements in an array.
%         tools.array.bitsetFlag - 
%        tools.array.blockmatrix - blockmatrix: reshape N-D matrix such that blocks of elements are adjacent
%          tools.array.bsx_nsize - bsx_nsize gets multiple of array sizes (i.e. result of the size function),
%           tools.array.bsx_size - bsx_size gets two arrays S1,S2 and calculates the size of the result
%        tools.array.check_range - Replace out of bound indices with bound indices.
%           tools.array.countVal - Given an N-D Array, count the number of elements
%         tools.array.delete_ind - Delete a column/s or row/s from a matrix.
%        tools.array.find_ranges - Indices of vector values found within one of several ranges.
%   tools.array.find_ranges_flag - Check if values are within some ranges.
%           tools.array.findmany - Find all values in a vector in another vector or matrix.
%       tools.array.flag2regions - Identify continous ranges of true values.
%        tools.array.hist2d_fast - A fast version of histcounts2 (without all the overheads)
%            tools.array.inRange - Check if values in array are within some ranges
%      tools.array.ind2sub_array - ind2sub_array Multiple subscripts from linear index.
%        tools.array.indexWindow - Return the in bound indices of a window in an array of some length.
%   tools.array.index_outofbound - Remove from vector of indices valu8es which are out of bounds.
%         tools.array.insert_ind - Insert a column/s or row/s to a specific position in a matrix.
%         tools.array.is_evenint - Check for each integer number in array if even.
%           tools.array.list2vec - Concatenate all vectors to a single vector.
%     tools.array.maskflag_check - --------------------------------------------------------------------------
%       tools.array.maskflag_set - --------------------------------------------------------------------------
%            tools.array.mat2vec - Convert matrix to vector. Use (:) instead.
%            tools.array.nan2val - Replace NaNs in an array with a specific values
%          tools.array.nangetind - Replace value with NaNs when index is out of bound.
%     tools.array.nearest_unflag - Nearest coordinate to an unflagged point.
%         tools.array.onesExcept - 
%             tools.array.or_nan - Logical function "or" for NaNs.
%            tools.array.replace - Replace values in specific range, or equal NaN, with another value.
%      tools.array.select_by_ind - Select lines by index, return NaN when index is NaN.
%      tools.array.sub2ind_array - sub2ind_array Linear index from multiple subscripts.
%       tools.array.sub2ind_fast - sub2ind fast version for 2D matrices
%          tools.array.sum_bitor - A bitor operation on all lines or rows and return a vector ofbit-wise or.
%               tools.array.trim - B = tools.array.trim(A, I1, I2, J1, J2)
%       tools.array.unique_count - Unique values and count the number of apperances of each value.
%           tools.array.unitTest - Package Unit-Test
%     tools.array.mex.allFunList - Functions and Classes list for the tools.array.mex package
% tools.array.mex.test_mex_bit_array32 - 
% tools.array.mex.test_mex_bit_array64 - 
 help tools.array.allFunList