/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int mexFunction();
int __fastcall sub_180001060(__int64 a1, __int64 a2, __int64 a3, _DWORD *a4, _DWORD *a5);
void __fastcall mexfilerequiredapiversion(_DWORD *a1, _DWORD *a2);
signed __int64 __fastcall sub_180001120(__int64 a1, int a2, __int64 a3);
signed __int64 __fastcall sub_180001170(__int64 a1, __int64 a2);
__int64 __fastcall sub_180001288(char a1);
__int64 __fastcall sub_18000130C(__int64 a1, int a2, __int64 a3);
__int64 sub_180001480();
signed __int64 __fastcall sub_18000152C(HMODULE a1, int a2);
void sub_180001550();
int sub_180001560();
void *sub_18000156C();
void *sub_180001574();
_QWORD *sub_18000157C();
char sub_180001598();
char sub_1800015D4();
bool sub_180001608();
char sub_180001620();
char sub_180001648();
int __fastcall sub_180001660(__int64 a1, int a2, __int64 a3, __int64 a4, unsigned int a5, __int64 a6);
void sub_1800016C0();
char sub_1800016F0();
char __fastcall sub_180001704(int a1);
char __fastcall sub_180001750(unsigned int a1);
bool __fastcall sub_1800017DC(__int64 a1);
__int64 __fastcall sub_180001874(char a1);
char __fastcall sub_180001898(__int64 a1, char a2);
void *sub_1800018C4();
void sub_1800018CC();
void __fastcall sub_1800018D4(unsigned int a1);
int __fastcall sub_180001A20(__int64 a1, __int64 a2, __int64 a3);
int __fastcall sub_180001A5C(__int64 a1, __int64 a2, __int64 a3);
__int64 sub_180001A9C();
signed __int64 sub_180001C40();
__int64 sub_180001C48();
// int vcomp_barrier(void); weak
// int __fastcall vcomp_for_static_end(_QWORD, _QWORD); weak
// int __fastcall vcomp_for_static_simple_init(_QWORD, _QWORD, _QWORD); weak
// int __fastcall vcomp_fork(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall _std_type_info_destroy_list(_QWORD); weak
// void *__cdecl memset(void *Dst, int Val, size_t Size);
// int __fastcall initterm(_QWORD, _QWORD); weak
// int __fastcall initterm_e(_QWORD, _QWORD); weak
// int __fastcall seh_filter_dll(_QWORD, _QWORD); weak
// int __fastcall configure_narrow_argv(_QWORD); weak
// int initialize_narrow_environment(void); weak
// int __fastcall initialize_onexit_table(_QWORD); weak
// int __fastcall execute_onexit_table(_QWORD); weak
// void __cdecl cexit();
// BOOL __stdcall IsProcessorFeaturePresent(DWORD ProcessorFeature);
char sub_180001CC8();
__int64 sub_180001CCC();
int __fastcall sub_180001CE0(_QWORD, _QWORD, _QWORD); // weak
__int64 __fastcall sub_180001D06(__int64 a1, __int64 a2);
__int64 __fastcall sub_180001D1D(__int64 a1, __int64 a2);
char sub_180001D36();
int __fastcall sub_180001D4A(unsigned int **a1, __int64 a2);
__int64 __fastcall sub_180001D80(_DWORD **a1);
// BOOL __stdcall IsDebuggerPresent();
// DWORD __stdcall GetCurrentProcessId();
// DWORD __stdcall GetCurrentThreadId();
// void __stdcall GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime);
// LPTOP_LEVEL_EXCEPTION_FILTER __stdcall SetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// LONG __stdcall UnhandledExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo);
// BOOL __stdcall QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount);
// PEXCEPTION_ROUTINE __stdcall RtlVirtualUnwind(DWORD HandlerType, DWORD64 ImageBase, DWORD64 ControlPc, PRUNTIME_FUNCTION FunctionEntry, PCONTEXT ContextRecord, PVOID *HandlerData, PDWORD64 EstablisherFrame, PKNONVOLATILE_CONTEXT_POINTERS ContextPointers);
// PRUNTIME_FUNCTION __stdcall RtlLookupFunctionEntry(DWORD64 ControlPc, PDWORD64 ImageBase, PUNWIND_HISTORY_TABLE HistoryTable);
// void __stdcall RtlCaptureContext(PCONTEXT ContextRecord);
// void __stdcall InitializeSListHead(PSLIST_HEADER ListHead);
// BOOL __stdcall DisableThreadLibraryCalls(HMODULE hLibModule);

//-------------------------------------------------------------------------
// Data declarations

char byte_180001285 = 'Ì'; // weak
char byte_1800017DA = 'Ì'; // weak
_UNKNOWN unk_180002128; // weak
_UNKNOWN unk_180002130; // weak
_UNKNOWN unk_180002138; // weak
_UNKNOWN unk_180002140; // weak
__int128 xmmword_180002180 = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFi64; // weak
_UNKNOWN unk_180002520; // weak
_UNKNOWN unk_180002530; // weak
__int64 qword_180003008 = -47936899621427i64; // weak
uintptr_t _security_cookie = 47936899621426ui64;
int dword_180003018 = 1; // weak
int dword_18000301C = 2; // weak
__int64 qword_180003020 = 8239i64; // weak
int dword_180003038 = 1; // weak
int dword_180003040 = 0; // weak
_UNKNOWN unk_180003050; // weak
_UNKNOWN unk_180003060; // weak
_UNKNOWN unk_180003068; // weak
int dword_180003070 = 0; // weak
__int64 qword_180003078 = 0i64; // weak
char byte_180003080 = '\0'; // weak
char byte_180003081 = '\0'; // weak
__int128 xmmword_180003088 = 0i64; // weak
__int64 qword_180003098 = 0i64; // weak
__int128 xmmword_1800030A0 = 0i64; // weak
__int64 qword_1800030B0 = 0i64; // weak
int dword_1800030B8 = 0; // weak
int dword_1800030C8 = 0; // weak
_UNKNOWN unk_1800030D0; // weak


//----- (0000000180001000) ----------------------------------------------------
int mexFunction()
{
  int v1; // [sp+40h] [bp-18h]@1
  __int64 v2; // [sp+48h] [bp-10h]@1

  v1 = 777;
  LODWORD(v2) = 16;
  return vcomp_fork(1i64, 5i64, sub_180001060, v2);
}
// 180001C72: using guessed type int __fastcall vcomp_fork(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000180001060) ----------------------------------------------------
int __fastcall sub_180001060(__int64 a1, __int64 a2, __int64 a3, _DWORD *a4, _DWORD *a5)
{
  int result; // eax@1
  __int64 v6; // rbx@1
  _DWORD *v7; // rdi@1
  __int64 v8; // rsi@1
  __int64 v9; // rbp@1
  _BYTE *v10; // rdx@2
  __int64 v11; // rcx@2
  __int64 v12; // rbx@3
  char *v13; // rax@3
  __int64 v14; // r9@3
  unsigned int v15; // er8@4
  int v16; // [sp+30h] [bp-18h]@2

  result = (signed int)a5;
  v6 = a2;
  v7 = a4;
  v8 = a3;
  v9 = a1;
  if ( *a5 > 0 )
  {
    vcomp_for_static_simple_init(0i64, (unsigned int)(*a5 - 1), 1i64);
    v11 = (unsigned int)v16;
    if ( (signed int)a5 <= v16 )
    {
      v12 = v6 - v8;
      v10 = (_BYTE *)((signed int)a5 + v9);
      v11 = (unsigned int)(v11 - (_DWORD)a5);
      v13 = (char *)(v8 + 4i64 * (signed int)a5);
      v14 = (unsigned int)(v11 + 1);
      do
      {
        v15 = *(_DWORD *)&v13[v12];
        *(_DWORD *)v13 = v15;
        if ( *v10 )
        {
          v11 = v15 | *v7;
          *(_DWORD *)v13 = v11;
        }
        ++v10;
        v13 += 4;
        --v14;
      }
      while ( v14 );
    }
    vcomp_for_static_end(v11, v10);
    result = vcomp_barrier();
  }
  return result;
}
// 180001C60: using guessed type int vcomp_barrier(void);
// 180001C66: using guessed type int __fastcall vcomp_for_static_end(_QWORD, _QWORD);
// 180001C6C: using guessed type int __fastcall vcomp_for_static_simple_init(_QWORD, _QWORD, _QWORD);

//----- (0000000180001110) ----------------------------------------------------
void __fastcall mexfilerequiredapiversion(_DWORD *a1, _DWORD *a2)
{
  *a1 = 131611;
  *a2 = 0;
}

//----- (0000000180001120) ----------------------------------------------------
signed __int64 __fastcall sub_180001120(__int64 a1, int a2, __int64 a3)
{
  int v3; // edx@2
  int v4; // edx@3
  signed __int64 result; // rax@5

  if ( a2 )
  {
    v3 = a2 - 1;
    if ( v3 )
    {
      v4 = v3 - 1;
      if ( v4 )
      {
        if ( v4 != 1 )
          return 1i64;
        LOBYTE(result) = sub_180001648();
      }
      else
      {
        LOBYTE(result) = sub_180001620();
      }
      result = (unsigned __int8)result;
    }
    else
    {
      result = sub_180001170(a1, a3);
    }
  }
  else
  {
    result = sub_180001288(a3 != 0);
  }
  return result;
}

//----- (0000000180001170) ----------------------------------------------------
signed __int64 __fastcall sub_180001170(__int64 a1, __int64 a2)
{
  __int64 v2; // rsi@1
  __int64 v3; // r14@1
  char v4; // bl@2
  char v5; // di@2
  __int64 v6; // rdx@3
  __int64 v7; // rcx@3
  __int64 v8; // r8@3
  __int64 *v9; // rax@8
  __int64 *v10; // rbx@8
  __int64 v11; // rax@10
  signed __int64 result; // rax@11

  v2 = a2;
  v3 = a1;
  if ( !sub_180001704(0) )
    goto LABEL_18;
  v4 = sub_180001598();
  v5 = 1;
  if ( dword_180003070 )
  {
    sub_1800018D4(7u);
    JUMPOUT(*(_QWORD *)&byte_180001285);
  }
  dword_180003070 = 1;
  if ( sub_180001608() )
  {
    sub_180001A20(v7, v6, v8);
    sub_180001550();
    sub_18000157C();
    if ( !initterm_e(&unk_180002138, &unk_180002140) )
    {
      if ( sub_1800015D4() )
      {
        initterm(&unk_180002128, &unk_180002130);
        dword_180003070 = 2;
        v5 = 0;
      }
    }
  }
  sub_180001874(v4);
  if ( v5 )
  {
LABEL_18:
    result = 0i64;
  }
  else
  {
    v9 = (__int64 *)sub_1800018C4();
    v10 = v9;
    if ( *v9 )
    {
      if ( sub_1800017DC((__int64)v9) )
      {
        v11 = *v10;
        sub_180001CE0(v3, 2i64, v2);
      }
    }
    ++dword_180003040;
    result = 1i64;
  }
  return result;
}
// 180001285: using guessed type char byte_180001285;
// 180001C92: using guessed type int __fastcall initterm(_QWORD, _QWORD);
// 180001C98: using guessed type int __fastcall initterm_e(_QWORD, _QWORD);
// 180001CE0: using guessed type int __fastcall sub_180001CE0(_QWORD, _QWORD, _QWORD);
// 180003040: using guessed type int dword_180003040;
// 180003070: using guessed type int dword_180003070;

//----- (0000000180001288) ----------------------------------------------------
__int64 __fastcall sub_180001288(char a1)
{
  char v1; // di@1
  __int64 result; // rax@2
  char v3; // bl@4
  __int64 v4; // rdx@5
  __int64 v5; // rcx@5
  __int64 v6; // r8@5
  __int64 v7; // rcx@5
  int v8; // ebx@5
  int v9; // edx@6
  __int64 v10; // rcx@6
  __int64 v11; // r8@6

  v1 = a1;
  if ( dword_180003040 > 0 )
  {
    --dword_180003040;
    v3 = sub_180001598();
    if ( dword_180003070 == 2 )
    {
      sub_1800016C0();
      sub_180001560();
      sub_180001A5C(v5, v4, v6);
      dword_180003070 = 0;
      sub_180001874(v3);
      LOBYTE(v7) = v1;
      v8 = sub_180001898(v7, 0) != 0 ? 1 : 0;
      sub_1800016F0();
      result = (unsigned int)v8;
    }
    else
    {
      sub_1800018D4(7u);
      __debugbreak();
      result = sub_18000130C(v10, v9, v11);
    }
  }
  else
  {
    result = 0i64;
  }
  return result;
}
// 180003040: using guessed type int dword_180003040;
// 180003070: using guessed type int dword_180003070;

//----- (000000018000130C) ----------------------------------------------------
__int64 __fastcall sub_18000130C(__int64 a1, int a2, __int64 a3)
{
  __int64 v3; // rsi@1
  int v4; // edi@1
  HMODULE v5; // r14@1
  __int64 result; // rax@3
  unsigned int v7; // ebx@5
  unsigned int v8; // eax@6

  v3 = a3;
  v4 = a2;
  v5 = (HMODULE)a1;
  if ( a2 || dword_180003040 > 0 )
  {
    if ( (unsigned int)(a2 - 1) > 1 || (v7 = sub_180001120(a1, a2, a3)) != 0 )
    {
      v8 = sub_18000152C(v5, v4);
      v7 = v8;
      if ( v4 == 1 && !v8 )
      {
        sub_18000152C(v5, 0);
        sub_180001288(v3 != 0);
      }
      if ( !v4 || v4 == 3 )
        v7 = (unsigned __int64)sub_180001120((__int64)v5, v4, v3) != 0;
    }
    result = v7;
  }
  else
  {
    result = 0i64;
  }
  return result;
}
// 180001CE0: using guessed type int __fastcall sub_180001CE0(_QWORD, _QWORD, _QWORD);
// 180003040: using guessed type int dword_180003040;

//----- (0000000180001480) ----------------------------------------------------
__int64 sub_180001480()
{
  signed __int64 v0; // rax@1
  __int64 result; // rax@5
  unsigned __int64 v2; // [sp+30h] [bp+10h]@2
  struct _FILETIME SystemTimeAsFileTime; // [sp+38h] [bp+18h]@2
  LARGE_INTEGER PerformanceCount; // [sp+40h] [bp+20h]@2

  v0 = _security_cookie;
  if ( _security_cookie == 47936899621426i64 )
  {
    SystemTimeAsFileTime = 0i64;
    GetSystemTimeAsFileTime(&SystemTimeAsFileTime);
    v2 = (unsigned __int64)SystemTimeAsFileTime;
    v2 ^= GetCurrentThreadId();
    v2 ^= GetCurrentProcessId();
    QueryPerformanceCounter(&PerformanceCount);
    v0 = ((unsigned __int64)&v2 ^ v2 ^ PerformanceCount.QuadPart ^ ((unsigned __int64)PerformanceCount.LowPart << 32)) & 0xFFFFFFFFFFFFi64;
    if ( v0 == 47936899621426i64 )
      v0 = 47936899621427i64;
    _security_cookie = v0;
  }
  result = ~v0;
  qword_180003008 = result;
  return result;
}
// 180003008: using guessed type __int64 qword_180003008;

//----- (000000018000152C) ----------------------------------------------------
signed __int64 __fastcall sub_18000152C(HMODULE a1, int a2)
{
  if ( a2 == 1 )
    DisableThreadLibraryCalls(a1);
  return 1i64;
}

//----- (0000000180001550) ----------------------------------------------------
void sub_180001550()
{
  InitializeSListHead((PSLIST_HEADER)&unk_180003050);
}

//----- (0000000180001560) ----------------------------------------------------
int sub_180001560()
{
  return _std_type_info_destroy_list(&unk_180003050);
}
// 180001C86: using guessed type int __fastcall _std_type_info_destroy_list(_QWORD);

//----- (000000018000156C) ----------------------------------------------------
void *sub_18000156C()
{
  return &unk_180003060;
}

//----- (0000000180001574) ----------------------------------------------------
void *sub_180001574()
{
  return &unk_180003068;
}

//----- (000000018000157C) ----------------------------------------------------
_QWORD *sub_18000157C()
{
  _QWORD *v0; // rax@1
  _QWORD *result; // rax@1

  v0 = sub_18000156C();
  *v0 |= 0x24ui64;
  result = sub_180001574();
  *result |= 2ui64;
  return result;
}

//----- (0000000180001598) ----------------------------------------------------
char sub_180001598()
{
  signed __int64 v0; // rcx@2
  signed __int64 v1; // rax@4

  if ( (unsigned int)sub_180001C48() )
  {
    v0 = *(_QWORD *)(*MK_FP(__GS__, 48i64) + 8i64);
    while ( 1 )
    {
      v1 = _InterlockedCompareExchange(&qword_180003078, v0, 0i64);
      if ( v1 == v0 )
        break;
      if ( v0 == v1 )
        return 1;
    }
  }
  return 0;
}
// 180003078: using guessed type __int64 qword_180003078;

//----- (00000001800015D4) ----------------------------------------------------
char sub_1800015D4()
{
  unsigned int v0; // eax@3

  if ( (unsigned int)sub_180001C48() )
  {
    sub_180001A9C();
  }
  else
  {
    v0 = sub_180001C40();
    if ( configure_narrow_argv(v0) )
      return 0;
    initialize_narrow_environment();
  }
  return 1;
}
// 180001CA4: using guessed type int __fastcall configure_narrow_argv(_QWORD);
// 180001CAA: using guessed type int initialize_narrow_environment(void);

//----- (0000000180001608) ----------------------------------------------------
bool sub_180001608()
{
  return sub_180001750(0) != 0;
}

//----- (0000000180001620) ----------------------------------------------------
char sub_180001620()
{
  if ( !sub_180001CC8() )
    return 0;
  if ( !sub_180001CC8() )
  {
    sub_180001CC8();
    return 0;
  }
  return 1;
}

//----- (0000000180001648) ----------------------------------------------------
char sub_180001648()
{
  sub_180001CC8();
  sub_180001CC8();
  return 1;
}

//----- (0000000180001660) ----------------------------------------------------
int __fastcall sub_180001660(__int64 a1, int a2, __int64 a3, __int64 a4, unsigned int a5, __int64 a6)
{
  __int64 v6; // rsi@1
  int v7; // ebx@1
  __int64 v8; // rbp@1

  v6 = a3;
  v7 = a2;
  v8 = a1;
  if ( !(unsigned int)sub_180001C48() && v7 == 1 )
    sub_180001CE0(v8, 0i64, v6);
  return seh_filter_dll(a5, a6);
}
// 180001C9E: using guessed type int __fastcall seh_filter_dll(_QWORD, _QWORD);
// 180001CE0: using guessed type int __fastcall sub_180001CE0(_QWORD, _QWORD, _QWORD);

//----- (00000001800016C0) ----------------------------------------------------
void sub_1800016C0()
{
  if ( (unsigned int)sub_180001C48() )
  {
    execute_onexit_table(&xmmword_180003088);
  }
  else if ( !(unsigned int)sub_180001CCC() )
  {
    cexit();
  }
}
// 180001CB6: using guessed type int __fastcall execute_onexit_table(_QWORD);
// 180003088: using guessed type __int128 xmmword_180003088;

//----- (00000001800016F0) ----------------------------------------------------
char sub_1800016F0()
{
  sub_180001CC8();
  return sub_180001CC8();
}

//----- (0000000180001704) ----------------------------------------------------
char __fastcall sub_180001704(int a1)
{
  char v1; // al@1

  v1 = byte_180003080;
  if ( !a1 )
    v1 = 1;
  byte_180003080 = v1;
  sub_180001A9C();
  if ( !sub_180001CC8() )
    return 0;
  if ( !sub_180001CC8() )
  {
    sub_180001CC8();
    return 0;
  }
  return 1;
}
// 180003080: using guessed type char byte_180003080;

//----- (0000000180001750) ----------------------------------------------------
char __fastcall sub_180001750(unsigned int a1)
{
  unsigned int v1; // ebx@1
  __m128i v3; // xmm0@8

  v1 = a1;
  if ( !byte_180003081 )
  {
    if ( a1 > 1 )
    {
      sub_1800018D4(5u);
      JUMPOUT(*(_QWORD *)&byte_1800017DA);
    }
    if ( !(unsigned int)sub_180001C48() || v1 )
    {
      v3 = _mm_load_si128((const __m128i *)&xmmword_180002180);
      _mm_storeu_si128((__m128i *)&xmmword_180003088, v3);
      qword_180003098 = -1i64;
      _mm_storeu_si128((__m128i *)&xmmword_1800030A0, v3);
      qword_1800030B0 = -1i64;
    }
    else if ( initialize_onexit_table(&xmmword_180003088) || initialize_onexit_table(&xmmword_1800030A0) )
    {
      return 0;
    }
    byte_180003081 = 1;
  }
  return 1;
}
// 1800017DA: using guessed type char;
// 180001CB0: using guessed type int __fastcall initialize_onexit_table(_QWORD);
// 180002180: using guessed type __int128 xmmword_180002180;
// 180003081: using guessed type char byte_180003081;
// 180003088: using guessed type __int128 xmmword_180003088;
// 180003098: using guessed type __int64 qword_180003098;
// 1800030A0: using guessed type __int128 xmmword_1800030A0;
// 1800030B0: using guessed type __int64 qword_1800030B0;

//----- (00000001800017DC) ----------------------------------------------------
bool __fastcall sub_1800017DC(__int64 a1)
{
  unsigned __int64 v1; // r8@4
  signed __int64 v2; // rdx@4
  signed __int64 v3; // r9@4
  unsigned __int64 v4; // rcx@6
  bool result; // al@11

  if ( v180000000 != 23117
    || *(_DWORD *)(v18000003C + 0x180000000i64) != 17744
    || *(_WORD *)(v18000003C + 0x180000018i64) != 523 )
  {
    result = 0;
  }
  else
  {
    v1 = a1 - 6442450944i64;
    v2 = *(_WORD *)(v18000003C + 0x180000014i64) + v18000003C + 6442450968i64;
    v3 = v2 + 40i64 * *(_WORD *)(v18000003C + 0x180000006i64);
    while ( v2 != v3 )
    {
      v4 = *(_DWORD *)(v2 + 12);
      if ( v1 >= v4 && v1 < (unsigned int)(v4 + *(_DWORD *)(v2 + 8)) )
        goto LABEL_10;
      v2 += 40i64;
    }
    v2 = 0i64;
LABEL_10:
    if ( v2 )
      result = *(_DWORD *)(v2 + 36) >= 0;
    else
      result = 0;
  }
  return result;
}

//----- (0000000180001874) ----------------------------------------------------
__int64 __fastcall sub_180001874(char a1)
{
  char v1; // bl@1
  __int64 result; // rax@1

  v1 = a1;
  result = sub_180001C48();
  _RDX = 0i64;
  if ( (_DWORD)result )
  {
    if ( !v1 )
      __asm { xchg    rdx, cs:qword_180003078 }
  }
  return result;
}
// 180003078: using guessed type __int64 qword_180003078;

//----- (0000000180001898) ----------------------------------------------------
char __fastcall sub_180001898(__int64 a1, char a2)
{
  if ( !byte_180003080 || !a2 )
  {
    sub_180001CC8();
    sub_180001CC8();
  }
  return 1;
}
// 180003080: using guessed type char byte_180003080;

//----- (00000001800018C4) ----------------------------------------------------
void *sub_1800018C4()
{
  return &unk_1800030D0;
}

//----- (00000001800018CC) ----------------------------------------------------
void sub_1800018CC()
{
  dword_1800030B8 = 0;
}
// 1800030B8: using guessed type int dword_1800030B8;

//----- (00000001800018D4) ----------------------------------------------------
void __fastcall sub_1800018D4(unsigned int a1)
{
  unsigned int v1; // ebx@1
  DWORD64 v2; // rbx@3
  struct _RUNTIME_FUNCTION *v3; // rax@3
  bool v4; // bl@5
  struct _EXCEPTION_POINTERS ExceptionInfo; // [sp+40h] [bp-C0h]@5
  int v6; // [sp+50h] [bp-B0h]@5
  int v7; // [sp+54h] [bp-ACh]@5
  DWORD64 v8; // [sp+60h] [bp-A0h]@5
  char Dst; // [sp+F0h] [bp-10h]@3
  __int64 *v10; // [sp+188h] [bp+88h]@5
  DWORD64 ControlPc; // [sp+1E8h] [bp+E8h]@3
  DWORD64 retaddr; // [sp+5C8h] [bp+4C8h]@5
  __int64 v13; // [sp+5D0h] [bp+4D0h]@5
  unsigned __int64 ImageBase; // [sp+5D8h] [bp+4D8h]@3
  unsigned __int64 v15; // [sp+5E0h] [bp+4E0h]@4
  PVOID v16; // [sp+5E8h] [bp+4E8h]@4

  v1 = a1;
  if ( IsProcessorFeaturePresent(0x17u) )
    __fastfail(v1);
  sub_1800018CC();
  memset(&Dst, 0, 0x4D0ui64);
  RtlCaptureContext((PCONTEXT)&Dst);
  v2 = ControlPc;
  v3 = RtlLookupFunctionEntry(ControlPc, &ImageBase, 0i64);
  if ( v3 )
    RtlVirtualUnwind(0, ImageBase, v2, v3, (PCONTEXT)&Dst, &v16, &v15, 0i64);
  ControlPc = retaddr;
  v10 = &v13;
  memset(&v6, 0, 0x98ui64);
  v8 = retaddr;
  v6 = 1073741845;
  v7 = 1;
  ExceptionInfo.ExceptionRecord = (PEXCEPTION_RECORD)&v6;
  v4 = IsDebuggerPresent() == 1;
  ExceptionInfo.ContextRecord = (PCONTEXT)&Dst;
  SetUnhandledExceptionFilter(0i64);
  if ( !UnhandledExceptionFilter(&ExceptionInfo) && !v4 )
    sub_1800018CC();
}

//----- (0000000180001A20) ----------------------------------------------------
int __fastcall sub_180001A20(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 *i; // rbx@1
  __int64 v4; // rax@2

  for ( i = (__int64 *)&unk_180002520; i < (__int64 *)&unk_180002520; ++i )
  {
    v4 = *i;
    if ( *i )
      LODWORD(v4) = sub_180001CE0(a1, a2, a3);
  }
  return v4;
}
// 180001CE0: using guessed type int __fastcall sub_180001CE0(_QWORD, _QWORD, _QWORD);

//----- (0000000180001A5C) ----------------------------------------------------
int __fastcall sub_180001A5C(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 *i; // rbx@1
  __int64 v4; // rax@2

  for ( i = (__int64 *)&unk_180002530; i < (__int64 *)&unk_180002530; ++i )
  {
    v4 = *i;
    if ( *i )
      LODWORD(v4) = sub_180001CE0(a1, a2, a3);
  }
  return v4;
}
// 180001CE0: using guessed type int __fastcall sub_180001CE0(_QWORD, _QWORD, _QWORD);

//----- (0000000180001A9C) ----------------------------------------------------
__int64 sub_180001A9C()
{
  int v5; // er11@1
  int v6; // er10@1
  signed int v7; // esi@1
  int v9; // er9@1
  int v14; // edi@1
  int v15; // eax@2
  unsigned __int64 v16; // rax@5
  signed __int64 v17; // rcx@6
  int v18; // er8@7
  signed __int64 v22; // rdx@15
  int v23; // eax@16

  _RAX = 0i64;
  __asm { cpuid }
  v5 = 0;
  v6 = _RDX;
  v7 = _RAX;
  _RAX = 1i64;
  v9 = _RCX ^ 0x6C65746E | _RBX ^ 0x756E6547;
  __asm { cpuid }
  v14 = _RCX;
  if ( v6 ^ 0x49656E69 | v9
    || (qword_180003020 = -1i64, v15 = _RAX & 0xFFF3FF0, v15 != 67264)
    && v15 != 132704
    && v15 != 132720
    && ((v16 = (unsigned int)(v15 - 198224), (unsigned int)v16 > 0x20) || (v17 = 4295032833i64, !_bittest64(&v17, v16))) )
  {
    v18 = dword_1800030C8;
  }
  else
  {
    v18 = dword_1800030C8 | 1;
    dword_1800030C8 |= 1u;
  }
  _RAX = 7i64;
  if ( v7 >= 7 )
  {
    __asm { cpuid }
    v5 = _RBX;
    if ( _bittest((const signed int *)&_RBX, 9u) )
      dword_1800030C8 = v18 | 2;
  }
  dword_180003018 = 1;
  dword_18000301C = 2;
  if ( _bittest(&v14, 0x14u) )
  {
    dword_180003018 = 2;
    dword_18000301C = 6;
    if ( _bittest(&v14, 0x1Bu) )
    {
      if ( _bittest(&v14, 0x1Cu) )
      {
        __asm { xgetbv }
        v22 = _RAX | (_RDX << 32);
        if ( (v22 & 6) == 6 )
        {
          v23 = dword_18000301C | 8;
          dword_180003018 = 3;
          dword_18000301C |= 8u;
          if ( v5 & 0x20 )
          {
            dword_180003018 = 5;
            dword_18000301C = v23 | 0x20;
            if ( (v5 & 0xD0030000) == -805109760 && (v22 & 0xE0) == -32 )
            {
              dword_18000301C |= 0x40u;
              dword_180003018 = 6;
            }
          }
        }
      }
    }
  }
  return 0i64;
}
// 180003018: using guessed type int dword_180003018;
// 18000301C: using guessed type int dword_18000301C;
// 180003020: using guessed type __int64 qword_180003020;
// 1800030C8: using guessed type int dword_1800030C8;

//----- (0000000180001C40) ----------------------------------------------------
signed __int64 sub_180001C40()
{
  return 1i64;
}

//----- (0000000180001C48) ----------------------------------------------------
__int64 sub_180001C48()
{
  return dword_180003038 != 0;
}
// 180003038: using guessed type int dword_180003038;

//----- (0000000180001CC8) ----------------------------------------------------
char sub_180001CC8()
{
  return 1;
}

//----- (0000000180001CCC) ----------------------------------------------------
__int64 sub_180001CCC()
{
  return 0i64;
}

//----- (0000000180001D06) ----------------------------------------------------
__int64 __fastcall sub_180001D06(__int64 a1, __int64 a2)
{
  return sub_180001874(*(_BYTE *)(a2 + 64));
}

//----- (0000000180001D1D) ----------------------------------------------------
__int64 __fastcall sub_180001D1D(__int64 a1, __int64 a2)
{
  return sub_180001874(*(_BYTE *)(a2 + 32));
}

//----- (0000000180001D36) ----------------------------------------------------
char sub_180001D36()
{
  return sub_1800016F0();
}

//----- (0000000180001D4A) ----------------------------------------------------
int __fastcall sub_180001D4A(unsigned int **a1, __int64 a2)
{
  return sub_180001660(
           *(_QWORD *)(a2 + 96),
           *(_DWORD *)(a2 + 104),
           *(_QWORD *)(a2 + 112),
           (__int64)sub_180001120,
           **a1,
           (__int64)a1);
}

//----- (0000000180001D80) ----------------------------------------------------
__int64 __fastcall sub_180001D80(_DWORD **a1)
{
  return **a1 == -1073741819;
}

// ALL OK, 42 function(s) have been successfully decompiled
