% Functions and Classes list for the VO.desi package
% Author : autogenerated (Jan 2025)
%            VO.desi.getSpecLink - get link to DESI spectra viewer given target ID or RA/Dec
%           VO.desi.wget_catalog - wget DESI catalog of spectra
 help VO.desi.allFunList