% Functions and Classes list for the imUtil.cut package
% Author : autogenerated (Jun 2023)
%          imUtil.cut.allFunList - Functions and Classes list for the imUtil.cut package
%       imUtil.cut.cutouts2image - Insert stamps in a cube into an image.
% imUtil.cut.find_within_radius_cell - Find points within a radius from a list of coordinates.
% imUtil.cut.find_within_radius_mat - Construct a cube of stamps around specific locations in a 2D image.
%         imUtil.cut.fun_cutouts - Apply a function thar returns a scalar to all cutouts in image around locations.
%             imUtil.cut.getLine - Get the values in image along a line or polygon defined by start and
%       imUtil.cut.image2cutouts - Given an image, make cutouts around selected coordinates.
%  imUtil.cut.partition_subimage - Partition image into sub images
%       imUtil.cut.subimage_grid - Partition image size into a grid of sub images
%     imUtil.cut.subimages2image - construct the full image from sub-images
%                imUtil.cut.trim - Trim an image or a cube using CCDSEC coordinates.
%      imUtil.cut.mex.allFunList - Functions and Classes list for the imUtil.cut.mex package
% imUtil.cut.mex.mexCutouts_unitTest - 
%      imUtil.cut.mex.mex_cutout - Usage: [cutouts, image_subtracted] = mex_cutout(image, positions, cut_size, pad_value=0, replace_value=0, debug_bit=0, use_memcpy=1);
%  imUtil.cut.image_partitioning - Partition a 2D image into sub images. OBSOLETE: use
%  imUtil.cut.subimage_boundries - Define boundries (ccdsec) for image subsections.
 help imUtil.cut.allFunList