% Functions and Classes list for the timeSeries.timeDelay package
% Author : autogenerated (Jun 2023)
%     timeSeries.timeDelay.A_hat - A_hat operator (Springer & Ofek 2021b)
% timeSeries.timeDelay.allFunList - Functions and Classes list for the timeSeries.timeDelay package
%   timeSeries.timeDelay.chi2_xF - Return the \chi^2 for fitting astrometric time delay in the time domain
% timeSeries.timeDelay.combined_Ft - Reconstruct the combined light curve from the original light curve
%   timeSeries.timeDelay.content - Content of the +TimeDelay package:
% timeSeries.timeDelay.dft_matrix - Return the discrete Fourier Transform matrix
% timeSeries.timeDelay.end_matching - Apply end-matching to a light curve such that first and last point have the same flux.
% timeSeries.timeDelay.end_matching_xt - Apply end-matching to a center-of-light position consistent with light curve
% timeSeries.timeDelay.equal_diagonals_matrix - Populate a vector along the diagonals of a matrix (Toplitz matrix)
%  timeSeries.timeDelay.fft_freq - Return the frequencies off fft with N points and Delta time step D.
% timeSeries.timeDelay.fit_astrometric_flux - Fit the 2 images astrometric-flux time delay model to observations
% timeSeries.timeDelay.fit_astrometric_flux_UnevenlySpaced - 
% timeSeries.timeDelay.fit_astrometric_flux_simple - Fit 2-D lensed images using the simple flux/astrometry method (no red noise)
%  timeSeries.timeDelay.fit_flux - Fit the 2 images time delay using the flux-only method
% timeSeries.timeDelay.fit_fluxBPL - Fit the power spectrum with broken power-law model
% timeSeries.timeDelay.fit_fluxBPL_TD - 
%    timeSeries.timeDelay.logdet - Calculate the log of the determinant of a matrix
%  timeSeries.timeDelay.logl_BPL - Calculate the log-likelihood for a broken power-law model
%    timeSeries.timeDelay.logl_F - Calculate the log-likelihood of F, Sigma_F, and Sigma_phi (flux only method)
%   timeSeries.timeDelay.logl_xF - Return the -logL of x,F - of the astrometric-flux time-delay method
% timeSeries.timeDelay.logl_x_given_F - Return the -logL of x | F - of the astrometric-flux time-delay method
% timeSeries.timeDelay.plots_for_paperI - Input  : - plot options:
% timeSeries.timeDelay.plots_for_paperII - PLot options:
% timeSeries.timeDelay.power_spectrum_sections - Calculate the power spectrum of unevenly spaced time series with gaps
% timeSeries.timeDelay.rand_lensed - Generate evenly spaced combined ligt curve and position of lensed quasar
% timeSeries.timeDelay.rand_lensed_uneq - unequally spaced lensed quasar light curves and center of light position
%  timeSeries.timeDelay.rand_psd - Generate a random vector with distribution following some power spectrum.
% timeSeries.timeDelay.reconstruct_ft - Reconstruct f(t) of a lensed quasar from the combined light and position
% timeSeries.timeDelay.sigma_phi - Calculate Sigma_phi and Sigma_F
% timeSeries.timeDelay.split2sections - Split a time series to sections in which the gaps have a maximum.
% timeSeries.timeDelay.witt_timedelay_formula - Calculate the time delay for isothermal elliptical potential (Witt formula)
 help timeSeries.timeDelay.allFunList