function [Flim, Slim_analytical, Status, x_binned, pdf_analytical_normalized] = poiss_threshold_analytical(bck, psf, Args)
% Analytical flux threshold for a Poisson matched filter, given a false-alarm prob.
% Description: Compute the flux threshold Fth given a PSF, background level and
%              false-alarm probability gamma, using the analytical scheme
%              instead of simulations. The null (background-only) distribution
%              of the matched-filter statistic
%                  S = sum_i n_i * log(1 + F*P_i/B)
%              is built exactly by enumerating every way in which up to 5
%              (or 6) background Poisson photons can land on the kernel pixels,
%              weighting each resulting value of S by its Poisson probability
%              (expressed as an expected count out of Nsim images). Sthresh is
%              the value of S whose upper-tail mass equals gamma; Fth is then
%              recovered by inverting the matched-filter normalisation, and the
%              procedure is iterated to a fixed point in F. This is a MATLAB
%              port of the X-sifter Python function of the same name.
% Input  : - bck : mean background level per pixel [counts]. Scalar > 0.
%          - psf : PSF stamp, a 2-D matrix P. NaNs are ignored.
%          * Arbitrary number of pairs of arguments: ...,keyword,value,...
%            where keyword are one of the followings:
%            'gamma'        - False-alarm probability: the probability that a
%                             source above the threshold was generated by the
%                             noise. No default (required).
%            'Sigma_guess'  - Gaussian sigma of the PSF, used only to set the
%                             first guess of the flux threshold via
%                             Flim0 = poissinv(1-gamma, 4*pi*Sigma^2*bck).
%                             No default (required).
%            'Nsim'         - Number of simulations, used to convert the
%                             analytical PMF into expected counts. No default
%                             (required).
%            'Stampsize'    - Used only in verbose printing. Default is [].
%            'step'         - Accepted for parity with the source; unused.
%                             Default is 1.
%            'ConvAccuracy' - Fixed-point tolerance on |Flim_new-Flim_old|.
%                             Default is 0.03.
%            'ConvMaxIter'  - Maximum number of fixed-point iterations.
%                             Default is 10.
%            'Verbose'      - Print progress. Default is true.
%            'unique_F'     - Accepted for parity with the source; unused.
%                             Default is false.
%            'bins_number'  - Number of bins for the returned PDF of S.
%                             Default is 200.
%            'six'          - Include the 6-photon terms. Default is false
%                             (as in the source for this routine).
%            'FixBug'       - Correct the latent bug by which the *returned*
%                             threshold variable was not zeroed/NaN-ed in the
%                             degenerate branch (see "Bug fix" below). Set to
%                             false to reproduce the original Python behaviour
%                             bit-for-bit. Default is true.
% Output : - Flim : Flux threshold Fth. NaN if it collapses to 0 (not converged).
%          - Slim_analytical : The threshold in units of the matched-filter
%            statistic S.
%          - Status : true if converged within ConvMaxIter, false otherwise.
%          - x_binned : Bin centres of the binned null PDF of S.
%          - pdf_analytical_normalized : Normalised null PDF of S on x_binned.
% Bug fix: In the original code the degenerate branch
%              if Slim_analytical == min(x_binned)
%                  Slim  = 0;   % assigns a variable that is NEVER returned
%                  Flim1 = 0;
%              end
%          sets a local 'Slim' rather than the returned 'Slim_analytical' (and
%          the later Flim==0 -> Slim=NaN guard has the same issue), so the
%          returned threshold is left stale while Flim becomes NaN. With
%          'FixBug'=true (default) the returned variable Slim_analytical is set
%          to NaN consistently with Flim; 'FixBug'=false reproduces the original.
% Author : Maayane T. Soumagnac (Python original, Nov 2025); Claude + Eran Ofek (MATLAB port  Jun 2026)
%    URL : https://github.com/maayane/X-sifter
% Example: yy = (-2:2).'; xx = (-2:2); [X,Y] = meshgrid(xx,yy);
%          P  = exp(-(X.^2+Y.^2)./(2*1.1^2)); P = P./sum(P(:));
%          [Flim,Slim,Status] = imUtil.poissNoise.poiss_threshold_analytical(0.05, P, 'gamma',0.01, 'Sigma_guess',1.1, 'Nsim',1e6, 'bins_number',50);

    arguments
        bck                       {mustBeNumeric, mustBeScalarOrEmpty}
        psf                       {mustBeNumeric}
        Args.gamma          = []; % required; validated below
        Args.Sigma_guess    = []; % required; validated below
        Args.Nsim           = []; % required; validated below
        Args.Stampsize      = [];
        Args.step           = 1;       % accepted for parity with source; unused
        Args.ConvAccuracy   = 0.03;
        Args.ConvMaxIter    = 10;
        Args.Verbose        = false;
        Args.unique_F       = false;   % accepted for parity with source; unused
        Args.bins_number    = 200;
        Args.six            = false;
        Args.FixBug         = true;
    end

    gamma       = Args.gamma;
    Sigma_guess = Args.Sigma_guess;
    Nsim        = Args.Nsim;
    bins_number = Args.bins_number;
    six         = Args.six;
    Verbose     = Args.Verbose;
    FixBug      = Args.FixBug;
    ConvAccuracy = Args.ConvAccuracy;
    ConvMaxIter  = Args.ConvMaxIter;
    step = Args.step; %#ok<NASGU> % parity: accepted, unused

    % ---- required parameters ----
    if isempty(gamma)
        error('gamma is required (false-alarm probability).');
    end
    if isempty(Sigma_guess)
        error('Sigma_guess is required (used for the initial flux guess).');
    end
    if isempty(Nsim)
        error('Nsim is required.');
    end

    if Verbose
        fprintf(['***** I am calculating the Threshold value, for the computed ' ...
                 'PSF, background and false-alarm *****\n']);
        fprintf('The size of the psf is %s, bck=%g\n', mat2str(Args.Stampsize), bck);
    end

    P = psf;   % MATLAB copies on assignment / modification, so this is a safe copy

    % ---------------- first guess for the flux threshold ----------------
    % Flimx = poisson.ppf(1-gamma, 4*pi*Sigma^2*bck); Flim = max(Flimx,1)
    Flimx = poissinv_local(1 - gamma, 4 * pi * Sigma_guess^2 * bck);
    Flim  = max(Flimx, 1);

    converge = false;
    iter = 0;
    Slim = NaN; %#ok<NASGU>  % the (unused-in-original) variable, kept for parity

    Slim_analytical = NaN;
    x_binned = [];
    pdf_analytical_normalized = [];
    Status = true;

    while ~converge
        iter = iter + 1;

        kernel = log(1 + Flim .* (P ./ bck));
        pixels = kernel(:);
        pixels = pixels(~isnan(pixels));
        len = numel(pixels);

        analytical_number = theoretical_number_images(bck, len, Nsim, six);
        values = sample_of_values_new(pixels, six);
        [vk, vc] = make_dictionary_of_number_of_occurences_new(values, analytical_number, six);

        % sort by value ascending (stable), matching df.sort_values('value')
        [vk, ord] = sort(vk);   % MATLAB sort is stable for real vectors
        vc = vc(ord);

        % NaN check on the keys (parity with the Python exception)
        if any(isnan(vk))
            error('There are nans in the values array, solve this before continuing');
        end

        [x_binned, pdf_analytical_normalized] = analytical_PDF(vk, vc, bins_number);

        Slim_analytical = analytical_Sthresh(vk, vc, Nsim, gamma);

        sum_pmf = nansum_local(log(1 + Flim .* (P ./ bck)));
        Flim1 = (Slim_analytical - bck * sum_pmf) / FluxNormFun(Flim, P, bck);

        if isnan(Flim1)
            error('Flim1 is nan, solve this before continuing or it will never converge');
        end

        if Slim_analytical == min(x_binned)
            if FixBug
                Slim_analytical = 0;   % FIX: zero the variable that is actually returned
            else
                Slim = 0;              %#ok<NASGU> % ORIGINAL latent bug (unused var)
            end
            Flim1 = 0;
        end

        converge = (abs(Flim1 - Flim) < ConvAccuracy) || (iter > ConvMaxIter);
        Flim = Flim1;

        if Verbose
            fprintf('iteration %d: Flim=%g\n', iter, Flim);
        end

        if iter > ConvMaxIter
            Status = false;
        else
            Status = true;
        end

        if Flim == 0
            Flim = NaN;
            Slim = NaN; %#ok<NASGU>
            if FixBug
                Slim_analytical = NaN; % FIX: also degenerate the returned threshold
            end
        end

        % imaginary-part guard (parity with the source)
        if imag(Flim) > 1e-3
            error('The imaginary part of Flim is suspiciously large');
        else
            Flim = real(Flim);
        end
    end

    if Verbose
        fprintf('converged?: %d\n', converge);
    end
    if imag(Slim_analytical) > 1e-3
        error('The imaginary part of Slim is suspiciously large');
    else
        Slim_analytical = real(Slim_analytical);
    end
end

% =====================================================================
% Helper: matched-filter flux normalisation (same as Eran's SF)
% =====================================================================
function s = FluxNormFun(Fth, PSF, Back)
    s = nansum_local(PSF .* log(1 + Fth .* (PSF ./ Back)));
end

% =====================================================================
% Helper: enumerate all attainable values of S for 1..5 (or 6) photons
% Returns a struct of column vectors, one field per partition pattern.
% Mirrors sample_of_values_new exactly, INCLUDING that the one-photon
% list keeps one entry per pixel (duplicates preserved).
% =====================================================================
function values = sample_of_values_new(pixels, six)
    pixels = pixels(:);
    pixels = pixels(~isnan(pixels));
    n = numel(pixels);
    idx = (1:n).';

    v1 = pixels;                                  % 1p  (one entry per pixel)

    c2 = nchoosek(idx, 2);                        % distinct unordered pairs
    v2_11 = pixels(c2(:,1)) + pixels(c2(:,2));
    v2_2  = 2 * v1;

    c3 = nchoosek(idx, 3);
    v3_111 = pixels(c3(:,1)) + pixels(c3(:,2)) + pixels(c3(:,3));
    v3_3   = 3 * v1;
    op2 = ordered_pairs(n);                       % ordered (i,j), i~=j
    v3_21  = 2 * pixels(op2(:,1)) + pixels(op2(:,2));

    c4 = nchoosek(idx, 4);
    v4_1111 = pixels(c4(:,1)) + pixels(c4(:,2)) + pixels(c4(:,3)) + pixels(c4(:,4));
    v4_4    = 4 * v1;
    v4_31   = pixels(op2(:,1)) + 3 * pixels(op2(:,2));
    v4_22   = 2 * pixels(c2(:,1)) + 2 * pixels(c2(:,2));
    v4_211  = pattern_two_plus_pair(pixels, c2, idx, 2);  % p_i + p_j + 2 p_k

    c5 = nchoosek(idx, 5);
    v5_11111 = pixels(c5(:,1)) + pixels(c5(:,2)) + pixels(c5(:,3)) + ...
               pixels(c5(:,4)) + pixels(c5(:,5));
    v5_5   = 5 * v1;
    v5_32  = 3 * pixels(op2(:,1)) + 2 * pixels(op2(:,2));
    v5_311 = pattern_three_plus_pair(pixels, c2, idx);    % 3 p_k + p_i + p_j
    v5_221 = pattern_twotwo_plus_one(pixels, c2, idx);    % 2 p_i + 2 p_j + p_k
    v5_2111= pattern_triple_plus_two(pixels, c3, idx);    % p_i+p_j+p_k + 2 p_l
    v5_41  = 4 * pixels(op2(:,1)) + pixels(op2(:,2));

    values = struct();
    values.p1      = v1;
    values.p2_1_1  = v2_11;
    values.p2_2    = v2_2;
    values.p3_1_1_1= v3_111;
    values.p3_3    = v3_3;
    values.p3_2_1  = v3_21;
    values.p4_1_1_1_1 = v4_1111;
    values.p4_4    = v4_4;
    values.p4_3_1  = v4_31;
    values.p4_2_2  = v4_22;
    values.p4_2_1_1= v4_211;
    values.p5_1_1_1_1_1 = v5_11111;
    values.p5_5    = v5_5;
    values.p5_4_1  = v5_41;
    values.p5_3_2  = v5_32;
    values.p5_3_1_1= v5_311;
    values.p5_2_2_1= v5_221;
    values.p5_2_1_1_1 = v5_2111;

    if six
        % (kept for completeness; six=false in the default path)
        c6 = nchoosek(idx, 6);
        v6_111111 = sum(reshape(pixels(c6.'), 6, []).', 2);
        values.p6_1_1_1_1_1_1 = v6_111111;
        values.p6_6   = 6 * v1;
        values.p6_4_2 = 4 * pixels(op2(:,1)) + 2 * pixels(op2(:,2));
        values.p6_3_3 = 3 * pixels(op2(:,1)) + 3 * pixels(op2(:,2));
        values.p6_5_1 = 5 * pixels(op2(:,1)) + pixels(op2(:,2));
        op4 = ordered_tuples(n, 4);
        values.p6_1_1_1_3 = pixels(op4(:,1)) + pixels(op4(:,2)) + pixels(op4(:,3)) + 3*pixels(op4(:,4));
        values.p6_1_1_2_2 = pixels(op4(:,1)) + pixels(op4(:,2)) + 2*pixels(op4(:,3)) + 2*pixels(op4(:,4));
        op5 = ordered_tuples(n, 5);
        values.p6_1_1_1_1_2 = pixels(op5(:,1)) + pixels(op5(:,2)) + pixels(op5(:,3)) + ...
                              pixels(op5(:,4)) + 2*pixels(op5(:,5));
    end
end

% --- pattern builders that mirror the nested-loop logic in the source ---

function out = pattern_two_plus_pair(pixels, c2, idx, mult)
    % for {i,j} unordered, for k ~= i,j :  pixels(i)+pixels(j)+mult*pixels(k)
    out = [];
    for r = 1:size(c2,1)
        i = c2(r,1); j = c2(r,2);
        k = idx(idx ~= i & idx ~= j);
        out = [out; pixels(i) + pixels(j) + mult * pixels(k)]; %#ok<AGROW>
    end
end

function out = pattern_three_plus_pair(pixels, c2, idx)
    % for {i,j} unordered, for k ~= i,j :  3*pixels(k)+pixels(i)+pixels(j)
    out = [];
    for r = 1:size(c2,1)
        i = c2(r,1); j = c2(r,2);
        k = idx(idx ~= i & idx ~= j);
        out = [out; 3 * pixels(k) + pixels(i) + pixels(j)]; %#ok<AGROW>
    end
end

function out = pattern_twotwo_plus_one(pixels, c2, idx)
    % for {i,j} unordered, for k ~= i,j :  2*pixels(i)+2*pixels(j)+pixels(k)
    out = [];
    for r = 1:size(c2,1)
        i = c2(r,1); j = c2(r,2);
        k = idx(idx ~= i & idx ~= j);
        out = [out; 2 * pixels(i) + 2 * pixels(j) + pixels(k)]; %#ok<AGROW>
    end
end

function out = pattern_triple_plus_two(pixels, c3, idx)
    % for {i,j,k} unordered, for l ~= i,j,k :  pixels(i)+pixels(j)+pixels(k)+2*pixels(l)
    out = [];
    for r = 1:size(c3,1)
        i = c3(r,1); j = c3(r,2); k = c3(r,3);
        l = idx(idx ~= i & idx ~= j & idx ~= k);
        out = [out; pixels(i) + pixels(j) + pixels(k) + 2 * pixels(l)]; %#ok<AGROW>
    end
end

function op = ordered_pairs(n)
    % all ordered (i,j) with i ~= j, in Python itertools.permutations order
    op = zeros(n*(n-1), 2);
    r = 0;
    for i = 1:n
        for j = 1:n
            if j ~= i
                r = r + 1;
                op(r,:) = [i, j];
            end
        end
    end
end

function ot = ordered_tuples(n, k)
    % all ordered k-tuples of distinct indices, in permutations() order
    P = perms_distinct(1:n, k);
    ot = P;
end

function P = perms_distinct(elements, k)
    % recursive generation of ordered k-permutations of distinct elements,
    % in the same lexicographic order as Python itertools.permutations
    if k == 0
        P = zeros(1,0);
        return;
    end
    P = [];
    for ii = 1:numel(elements)
        e = elements(ii);
        rest = elements([1:ii-1, ii+1:end]);
        sub = perms_distinct(rest, k-1);
        P = [P; repmat(e, size(sub,1), 1), sub]; %#ok<AGROW>
    end
end

% =====================================================================
% Helper: theoretical (Poisson) expected counts per partition pattern
% Mirrors theoretical_number_images (six handled but unused by default).
% Returns a struct of the *_individual_value fields plus n_zeros/n_nonzeros.
% =====================================================================
function a = theoretical_number_images(bck, len, Nsim, six) %#ok<INUSD>
    pf = @(k) poisspdf_local(k, bck);
    p0 = pf(0);

    p_zero  = p0 ^ len;
    p_one   = pf(1) * p0^(len-1);
    p_2_11  = pf(1)^2 * p0^(len-2);
    p_2_2   = pf(2)   * p0^(len-1);
    p_3_3   = pf(3)   * p0^(len-1);
    p_3_21  = pf(2)*pf(1) * p0^(len-2);
    p_3_111 = pf(1)^3 * p0^(len-3);
    p_4_1111= pf(1)^4 * p0^(len-4);
    p_4_31  = pf(1)*pf(3) * p0^(len-2);
    p_4_22  = pf(2)^2 * p0^(len-2);
    p_4_211 = pf(1)^2*pf(2) * p0^(len-3);
    p_4_4   = pf(4) * p0^(len-1);
    p_5_5   = pf(5) * p0^(len-1);
    p_5_32  = pf(3)*pf(2) * p0^(len-2);
    p_5_41  = pf(4)*pf(1) * p0^(len-2);
    p_5_311 = pf(3)*pf(1)^2 * p0^(len-3);
    p_5_221 = pf(2)^2*pf(1) * p0^(len-3);
    p_5_2111= pf(1)^3*pf(2) * p0^(len-4);
    p_5_11111 = pf(1)^5 * p0^(len-5);

    number_images_zero = p_zero * Nsim;

    a = struct();
    a.n_zeros = number_images_zero;
    % per-value expected counts (the *_individual_value fields)
    a.n_1p          = p_one    * Nsim;
    a.n_2p_1_1      = p_2_11   * Nsim;
    a.n_2p_2        = p_2_2    * Nsim;
    a.n_3p_1_1_1    = p_3_111  * Nsim;
    a.n_3p_3        = p_3_3    * Nsim;
    a.n_3p_2_1      = p_3_21   * Nsim;
    a.n_4p_1_1_1_1  = p_4_1111 * Nsim;
    a.n_4p_4        = p_4_4    * Nsim;
    a.n_4p_3_1      = p_4_31   * Nsim;
    a.n_4p_2_2      = p_4_22   * Nsim;
    a.n_4p_2_1_1    = p_4_211  * Nsim;
    a.n_5p_1_1_1_1_1= p_5_11111* Nsim;
    a.n_5p_5        = p_5_5    * Nsim;
    a.n_5p_3_2      = p_5_32   * Nsim;
    a.n_5p_4_1      = p_5_41   * Nsim;
    a.n_5p_3_1_1    = p_5_311  * Nsim;
    a.n_5p_2_2_1    = p_5_221  * Nsim;
    a.n_5p_2_1_1_1  = p_5_2111 * Nsim;
end

% =====================================================================
% Helper: accumulate expected counts keyed by the *value* of S.
% Mirrors make_dictionary_of_number_of_occurences_new: each list entry
% adds its pattern's per-value expected count to the running total for
% that exact value. Returns unique values vk and summed counts vc.
% =====================================================================
function [vk, vc] = make_dictionary_of_number_of_occurences_new(values, a, six)
    % Build parallel arrays of (value, per-entry weight) then sum by value.
    cats = {
        'p1','n_1p'; ...
        'p2_1_1','n_2p_1_1'; 'p2_2','n_2p_2'; ...
        'p3_1_1_1','n_3p_1_1_1'; 'p3_3','n_3p_3'; 'p3_2_1','n_3p_2_1'; ...
        'p4_1_1_1_1','n_4p_1_1_1_1'; 'p4_4','n_4p_4'; 'p4_3_1','n_4p_3_1'; ...
        'p4_2_2','n_4p_2_2'; 'p4_2_1_1','n_4p_2_1_1'; ...
        'p5_1_1_1_1_1','n_5p_1_1_1_1_1'; 'p5_5','n_5p_5'; ...
        'p5_4_1','n_5p_4_1'; 'p5_3_2','n_5p_3_2'; 'p5_3_1_1','n_5p_3_1_1'; ...
        'p5_2_2_1','n_5p_2_2_1'; 'p5_2_1_1_1','n_5p_2_1_1_1' };

    allv = [];
    allw = [];
    for r = 1:size(cats,1)
        vfield = cats{r,1};
        wfield = cats{r,2};
        vlist = values.(vfield);
        vlist = vlist(:);
        w = a.(wfield);
        allv = [allv; vlist];                 %#ok<AGROW>
        allw = [allw; w * ones(numel(vlist),1)]; %#ok<AGROW>
    end

    % Sum weights for identical values. Python dict keys on exact float
    % equality, so we group on exact equality here too (no tolerance).
    [vk, ~, ic] = unique(allv);   % ascending, exact equality
    vc = accumarray(ic, allw);
end

% =====================================================================
% Helper: binned PDF of S. Mirrors analytical_PDF (pandas cut + groupby,
% include_lowest=True, with the min edge forced to 0 if positive).
% =====================================================================
function [x_binned, pdf_norm] = analytical_PDF(vk, vc, num_bins)
    vk = vk(:); vc = vc(:);
    normalized_count = vc ./ sum(vc);

    min_edge = min(vk);
    if min_edge > 0
        min_edge = 0;   % force inclusion of 0
    end
    max_edge = max(vk);
    bin_edges = linspace(min_edge, max_edge, num_bins + 1);

    % pandas.cut with include_lowest=True: bins are (e0,e1],(e1,e2],...
    % but the very first bin is closed on the left, i.e. [e0,e1].
    % Assign each value to a bin index.
    nb = num_bins;
    binidx = zeros(numel(vk), 1);
    for t = 1:numel(vk)
        x = vk(t);
        % find the bin: largest edge strictly less than x, capped; handle
        % left-closed lowest bin and right-closed bins.
        if x <= bin_edges(1)
            % only valid if x == min_edge (include_lowest) — but min_edge may
            % be 0 while min(vk) > 0; values below e0 cannot occur because
            % e0 <= min(vk). So x == e0 lands in bin 1.
            b = 1;
        else
            % right-closed bins: x in (edge(b), edge(b+1)] -> bin b
            b = find(x <= bin_edges(2:end), 1, 'first');
            if isempty(b)
                b = nb;  % numerical edge case at the maximum
            end
        end
        binidx(t) = b;
    end

    % aggregate per bin: mean of value, sum of normalized_count
    sum_norm = accumarray(binidx, normalized_count, [nb, 1], @sum, 0);
    sum_val  = accumarray(binidx, vk,               [nb, 1], @sum, 0);
    cnt_in   = accumarray(binidx, 1,                [nb, 1], @sum, 0);

    mean_val = nan(nb, 1);
    nz = cnt_in > 0;
    mean_val(nz) = sum_val(nz) ./ cnt_in(nz);

    % .dropna(): drop empty bins (NaN mean)
    keep = ~isnan(mean_val);
    x_binned = mean_val(keep);
    pdf_norm = sum_norm(keep);

    x_binned = x_binned(:);
    pdf_norm = pdf_norm(:);
end

% =====================================================================
% Helper: analytical Sthresh via reverse cumulative sum of counts.
% Mirrors analytical_Sthresh: take the largest value whose upper-tail
% expected count (rev_cumsum) is still >= Nsim*gamma.
% =====================================================================
function Sthresh = analytical_Sthresh(vk, vc, Nsim, gamma)
    [vk, ord] = sort(vk);     % ascending
    vc = vc(ord);
    rev_cumsum = flipud(cumsum(flipud(vc(:))));
    mask = rev_cumsum >= Nsim * gamma;
    if ~any(mask)
        error('No row satisfies rev_cumsum >= Nsim*gamma. Check inputs or increase Nsim.');
    end
    idx = find(mask, 1, 'last');   % last (largest-value) index where tail >= Nsim*gamma
    Sthresh = vk(idx);
end

% =====================================================================
% Small numerical helpers (so the file works in base MATLAB and Octave
% without the Statistics Toolbox).
% =====================================================================
function s = nansum_local(x)
    x = x(:);
    s = sum(x(~isnan(x)));
end

function p = poisspdf_local(k, mu)
    % Poisson pmf without toolbox dependency
    p = exp(-mu) .* mu.^k ./ factorial(k);
end

function x = poissinv_local(q, mu)
    % Inverse Poisson CDF (smallest x with CDF(x) >= q), no toolbox needed.
    if q >= 1
        x = Inf; return;
    end
    if q <= 0
        x = 0; return;
    end
    x = 0;
    cdf = exp(-mu);   % P(X=0)
    term = cdf;
    while cdf < q
        x = x + 1;
        term = term * mu / x;   % P(X=x) from P(X=x-1)
        cdf = cdf + term;
        if x > 1e7
            break;
        end
    end
end