% Functions and Classes list for the lcUtil package
% Author : autogenerated (Jun 2023)
%              lcUtil.allFunList - Functions and Classes list for the lcUtil package
%             lcUtil.findOrphans - Select orphan sources from a MatchedSources object.
%        lcUtil.findOrphansClean - Select orphan sources from a MatchedSources object and clean them.
%               lcUtil.fitMotion - fit Proper motion in RA/Dec to coordinates in MatchedSources object.
%              lcUtil.fitPolyHyp - Hypothesis testing between fitting polynomials of various degrees to
%           lcUtil.matchedFilter - Matched filtering with template bank for equally spaced time series.
%             lcUtil.zp_external - 
%                  lcUtil.zp_lsq - Apply a relative photometry least square ZP solution to a light curve
%              lcUtil.zp_meddiff - Estimate light curve ZP based on a simple median of differences.
%              lcUtil.zp_sumFlux - 
 help lcUtil.allFunList