% Functions and Classes list for the astro.stars package
% Author : autogenerated (Jan 2025)
%         astro.stars.allFunList - Functions and Classes list for the astro.stars package
% astro.stars.ang_radius_from_color - Estimate angular radius and color temperature from a set of magnitudes
% astro.stars.ang_radius_from_temp - Calculate the angular size of a star given its mag, extinction and temp
%            astro.stars.equipot - Calculate the gravitational potential of a binary star on a grid.
% astro.stars.getClaret2020_LimbDarkeningWD - Get the Claret (2020) WD limb darkening coef.
%      astro.stars.limbDarkening - Return the limb darkening value as a function of mu and coef.
%    astro.stars.mass_radius_lum - Return the mass-radius-effective T, logg, Lum, for the main sequence
%       astro.stars.star_ang_rad - Calculate empirical angular radii of stars from magnitude and colors.
%  astro.stars.star_sptype_color - Spectral type to color
%        astro.stars.stellar_imf - The stellar initial mass function
%     astro.stars.stellar_tracks - Geneva stellar tracks as a function of time.
% astro.stars.tlogg2picklesClass - spectral class and luminosity class to be used with AstroSpec.specStarsPickles
%           astro.stars.unitTest - Package Unit-Test
 help astro.stars.allFunList