% Functions and Classes list for the imUtil.cat package
% Author : autogenerated (Jun 2023)
% imUtil.cat.affine2d_transformation - Applay a 2D affine transformation to [X,Y] coordinates
%          imUtil.cat.allFunList - Functions and Classes list for the imUtil.cat package
%     imUtil.cat.astrometric_cat - Get astrometric catalog, corrected for proper motion
%   imUtil.cat.dilute_cat_by_mag - Remove faint sources from a catalog to have a specific surface density
%      imUtil.cat.flag_overdense - Flag sources that are found in overdense (box shaped) regions
% imUtil.cat.flag_overdense_colrow - Flag sources that are found in overdense (box shaped) regions
%       imUtil.cat.match_sources - Match sources in two catalogs with the same coordinates systems.
%    imUtil.cat.match_sources_xy - Match sources between Cat and Ref catalogs using their X/Y (planar) coordinates.
%     imUtil.cat.surface_density - Estimate surface density in catalog, optionally using convex hull
 help imUtil.cat.allFunList