function [FoundAll,MostRecentFile,MostRecentRep] = searchNewFilesInDir(Dir, FileTemplate, ReplaceStr, ReplaceTo)
    % Check if file template exist in dir. Also check if additional files
    % generated by strrep on the original file exist.
    %       Note that if ReplaceStr and ReplaceTo are empty, then only the
    %       main file will be searched.
    % Input  : - Dir name.
    %          - File template.
    %          - An optional string. If this is given, then after the main
    %            file template search is done, look for this string in the
    %            template and replace it with the ReplaceTo argument. The new
    %            file name is also searched.
    %          - A celll array of ReplaceTo strings.
    % Output : - A logical indicating if the main file and replaced files
    %            were found.
    %          - The main file found.
    %          - A cell of the replaced name files found.
    % Author : Eran Ofek (Jan 2022)
    % Example: FoundAll =
    % [F]=io.files.searchNewFilesInDir('/data/euler/archive/LAST/2020/08/20/proc/8','LAST*_science_proc_Image_*.fits',{},{})
    % [F,RF,RRF]=io.files.searchNewFilesInDir('/data/euler/archive/LAST/2020/08/20/proc/8','LAST*_science_proc_Image_*.fits','_Image_',{'_Mask_'})
    
    
    
    arguments
        Dir
        FileTemplate       = '*_dark_raw_*Image_*';
        ReplaceStr         = {}; %'_Image_';
        ReplaceTo          = {}; %{'_Mask_'};
    end
    
    FullFileTemplate = sprintf('%s%s%s', Dir, filesep, FileTemplate);
    
    
    RepFile = strrep(FileTemplate, ReplaceStr, ReplaceTo);
    Nrep    = numel(RepFile);
    MostRecentRep  = {};
    MostRecentFile = {};
    
    Found    = false;
    FoundRep = false(1,Nrep);
    
    Files = io.files.dirSortedByDate(FullFileTemplate);
    if isempty(Files)
        % not found    
        Found = false;
    else
        MostRecentFile = Files(end).name;
        Found = true;
        
        % check for replacment strings
        
        for Irep=1:1:Nrep
            FullRepTemplate = sprintf('%s%s%s', Dir, filesep, RepFile{Irep});
            Files = io.files.dirSortedByDate(FullRepTemplate);
            if isempty(Files)
                % not found
                FoundRep(Irep) = false;
            else
                MostRecentRep{Irep} = Files(end).name;
                FoundRep(Irep) = true;
            end
        end
    end
    
    if Found && all(FoundRep)
        FoundAll = true;
    else
        FoundAll = false;
    end
    
end
