#!/bin/sh

  echo "Testing WCSLIB syntax checker for FITS WCS keyrecords (twcslint)"
  echo "----------------------------------------------------------------"
  ../utils/wcsware -l -p -v wcslint.fits
