% Functions and Classes list for the tools.os package
% Author : autogenerated (Jun 2023)
%            tools.os.allFunList - Functions and Classes list for the tools.os package
%                    tools.os.cd - Change dir function. If no arguments cd to home dir.
%               tools.os.cdmkdir - cd to directory - if not exist than create
%             tools.os.class_mlx - Open MLX file of class, which is expected in folder '/help/mlx/.../ClassName.mlx'
%  tools.os.copyJavaJarToTempDir - Copy Java .jar file to temporary folder and it to javaaddpath()
% tools.os.getAstroPackConfigPath - 
%  tools.os.getAstroPackDataPath - 
% tools.os.getAstroPackExternalPath - 
%      tools.os.getAstroPackPath - Return the AstroPack toolbox path
%            tools.os.getTempDir - 
%        tools.os.getTestDataDir - Return the path containing the test images used by the unitTest
%        tools.os.getTestWorkDir - 
%       tools.os.getUltrasatPath - 
%     tools.os.get_avx_supported - persistent avx;
%          tools.os.get_computer - Get computer name
%              tools.os.get_user - Get user name
%          tools.os.get_userhome - Get user home directory path
%               tools.os.islinux - 
%             tools.os.iswindows - 
%            tools.os.matlab_pid - Return the matlab PID and computer host name
%           tools.os.memoryLinux - Get the MATLAB memory and CPU usage (for Linux only).
%           tools.os.package_mlx - Open MLX file of class, which is expected in folder '/help/mlx/.../+Package.mlx'
%             tools.os.runPython - Run python with specified script
%           tools.os.system_list - Run the system command on a list of files.
%             tools.os.systemarg - Running the UNIX system command.
%              tools.os.unitTest - Package Unit-Test
%             tools.os.user_name - Get user name
%        tools.os.mex.allFunList - Functions and Classes list for the tools.os.mex package
 help tools.os.allFunList