% Functions and Classes list for the imProc.stack package
% Author : autogenerated (Jun 2023)
% imProc.stack.addImageRedistributePixels - Add Image1 to Image according to the pixel redistribution defined by the coordinate arrays X, Y with the signal distributed amoung 4 neighbouring pixels
%        imProc.stack.allFunList - Functions and Classes list for the imProc.stack package
%     imProc.stack.applyUnaryFun - Applay scalar-unary function (e.g., function that returns a scalar) on AstroImage
%             imProc.stack.coadd - Coadd images in AstroImage object including pre/post normalization
%   imProc.stack.coaddProperCore - Proper coaddition of images in AstroImage object
%      imProc.stack.divideFactor - Divide factor (constant) from AstroImage
%           imProc.stack.funCube - Apply function/s on a single cube
% imProc.stack.functionalResponse - Fit the pixel response to light as a function of intensity in a cube of images
%         imProc.stack.makeMovie - Display and create a movie file from images in AstroImage or cube.
%            imProc.stack.stitch - Make a mosaic sky image from a set of input image files or AstroImages
%    imProc.stack.subtractOffset - Remove offset (constant) from AstroImage
%          imProc.stack.unitTest - unitTest for the Stack class
 help imProc.stack.allFunList