function [Result, CoaddN, MidJD] = coadd_Proper(Obj, Args)
    % Proper coaddition (Zackay & Ofek 2017) of registered images stored in AstroImage object.
    %   The function works on registered images (e.g., using
    %   imProc.transIm.register).
    %   It coadds the images using the imUtil.properCoadd.combine_proper
    %   function, using the image cube, variance information, flux matching
    %   factors, and the PSF cube. The header is updated.
    % Input  : - An AstroImage/AstroZOGY/AstroDiff object.
    %          * ...,key,val,...
    %            'SubBack' - Subtract background prior to coaddition.
    %                   Default is true.
    %            'BackArgs' - A cell array of additional input arguments to
    %                   pass to the imProc.background.backVar function.
    %                   This function will be used if the Back property is
    %                   not populated, and also for background estimation of
    %                   the coadded image when 'AddBack' is true.
    %            'ScalarVar' - Logical indicating if to replace the
    %                   variance image of each input image by a scalar
    %                   variance estimated from the mean variance over the
    %                   image. If false, use the full variance cube.
    %                   Default is true.
    %            'CCDSEC' - CCDSEC region [Xmin Xmax Ymin Ymax] to extract
    %                   from each image prior to coaddition. If empty use
    %                   the full image. Default is [].
    %            'ZP' - Zero-point values or keyword/property from which to
    %                   derive the flux matching factors between images. If
    %                   empty then assume equal flux scaling for all images.
    %                   Default is [].
    %            'ZP0' - Reference zero point to which all images are
    %                   scaled when 'ZP' is provided. Default is 25.
    %            'AddBack' - Estimate and populate the background of the
    %                   coadded image. Default is true.
    %            'AddMask' - Coadd the mask images into the output mask
    %                   image using bitwise OR. Default is true.
    %            'BitCoaddUseMex' - Use MEX implementation in
    %                   tools.array.bitor_array when available.
    %                   Default is true.
    %            'HeaderCopy1' - Copy header template from the first image.
    %                   Default is true.
    %            'NewHeader' - Optional header object/content to use as the
    %                   basis for the output header. Default is [].
    %            'UpdateTimes' - Update time-related header keywords in the
    %                   output header. Default is true.
    %            'SumExpTime' - Sum the exposure times into the output
    %                   header. Default is true.
    %            'UpdateImagePathKeys' - Update path/name related header
    %                   keywords in the output header. Default is true.
    %            'StackMethod' - String describing the stack method to
    %                   write to the header. If empty, the function uses its
    %                   internal method label.
    %            'KeyExpTime' - Header keyword containing the exposure
    %                   time. Default is 'EXPTIME'.
    %            'PreAllocCube' - Optional preallocated cube to use in
    %                   imProc.image.images2cube. Default is [].
    % Output : - An AstroImage object containing the proper coadd image,
    %            PSF image, mask image and optional background.
    %          - (CoaddN) Number of input images used in the coadd.
    %          - Exposure time weighted mean of mid times of the coadd
    %            exposures (also written to header).
    % Notes   : - If 'SubBack' is true and some images do not have the Back
    %            property populated, then the function estimates the
    %            background using imProc.background.backVar.
    %          - If 'ScalarVar' is true, then the variance used in the
    %            proper coaddition is the mean variance of each image,
    %            rather than the full variance image.
    %          - If 'ZP' is provided, then images are flux matched before
    %            coaddition using imProc.stack.getFluxMatch.
    %          - The PSF cube is generated using imProc.psf.psf2cube and
    %            is passed to imUtil.properCoadd.combine_proper.
    %          - The output mask is generated by bitwise OR of all input
    %            masks.
    %          - The output header is generated using
    %            imProc.stack.coaddHeader.
    % Author : Eran Ofek (Apr 2026)
    % Example: % Proper coadd all images in Obj after background subtraction:
    %          Result = imProc.stack.coadd_Proper(Obj);
    %          % Proper coadd a CCDSEC region:
    %          Result = imProc.stack.coadd_Proper(Obj, 'CCDSEC',...
    %                   [100 500 200 700]);
    %          % Proper coadd while using zero-point based flux matching:
    %          Result = imProc.stack.coadd_Proper(Obj, 'ZP', 'ZP', ...
    %                   'ZP0', 25);

    arguments
        Obj   % AstroImage, AstroDiff, AstroZOGY
        Args.SubBack         = true;
        Args.BackArgs        = {};
        Args.FinalBackArgs   = {'Method',@imUtil.background.modeVar_Hist};
        Args.ScalarVar       = true;
        Args.CCDSEC          = [];
        Args.ZP              = 'PH_ZP';  % if empty use equal flux matching
        Args.ZP0             = 25;
        
        %--- coadd ---
        Args.AddBack         = true;

        %--- Mask ---
        Args.AddMask         = true;
        Args.BitCoaddUseMex  = true;
        Args.KeyNaN          = 'NaN';
        Args.KeyCoaddLess    = 'CoaddLessImages';
        Args.FracCoaddLess   = 0.6; 

        %--- Header ---
        Args.HeaderCopy1 logical                    = true;
        Args.NewHeader                              = [];
        Args.UpdateTimes(1,1) logical               = true;
        Args.SumExpTime(1,1) logical                = true;
        Args.UpdateImagePathKeys logical            = true;
        Args.StackMethod                            = '';
        Args.KeyExpTime                             = 'EXPTIME';

        %--- aux ---
        Args.PreAllocCube    = [];

    end
    StackMethod = 'proper';
    
    Nim = numel(Obj);
    DimIndex  = 3;
    % is background needed?
    if Args.SubBack
        % Get background
        Flag = Obj.isemptyProperty('Back');
        Obj(Flag) = imProc.background.backVar(Obj(Flag), Args.BackArgs{:});
    
        [ImageCube, BackCube, VarCube, MaskCube] = imProc.image.images2cube(Obj, 'CCDSEC',Args.CCDSEC, 'DimIndex',DimIndex,...
                                                                                 'DataProp',{'ImageData','BackData', 'VarData', 'MaskData'},...
                                                                                 'DataPropIn','Data',...
                                                                                 'Cube',Args.PreAllocCube);
        ImageCube = ImageCube - BackCube; % subtract background
    else
        % no background subtraction is needed
        [ImageCube, VarCube, MaskCube] = imProc.image.images2cube(Obj, 'CCDSEC',Args.CCDSEC, 'DimIndex',DimIndex,...
                                                                                 'DataProp',{'ImageData', 'VarData', 'MaskData'},...
                                                                                 'DataPropIn','Data',...
                                                                                 'Cube',Args.PreAllocCube);
        BackCube = [];
    end

    % convert Var cube to scalar per pimage
    if Args.ScalarVar
        Var = squeeze(mean(VarCube,[1 2], 'omitnan'));
    else
        Var = VarCube;
    end
    if ~strcmp(class(ImageCube), class(Var))
        Var = cast(Var, 'like',ImageCube);
    end

    % flux matching parameters
    if isempty(Args.ZP)
        % Equal flux matching
        FluxMatch = ones(Nim,1);
        ZP0       = NaN;
    else
        [FluxMatch,ZP0] = imProc.stack.getFluxMatch(Obj, 'ZP',Args.ZP, 'ZP0',Args.ZP0);
    end
    % make sure Flux match has the same units as the images
    FluxMatch = cast(FluxMatch, 'like',ImageCube);

    % create AstroImage for results
    Result = AstroImage;

    % coadd
    CubePSF   = imProc.psf.psf2cube(Obj);
    
    PixNaN = isnan(ImageCube);
    CoaddN = sum(~PixNaN,3);
    % for proper coaddition - replace all NaNs with background level.
    if Args.SubBack
        % background supoosed to be 0
        ImageCube(PixNaN) = 0; % replace NaN with 0
    else
        error('SubBack false is not supported');
    end

    [Result.ImageData.Data, Result.PSFData.Data] = imUtil.properCoadd.combine_proper(ImageCube, CubePSF, 'F',FluxMatch, 'Var',Var, 'Norm',true);
    Result.ImageData.Data = real(Result.ImageData.Data);
    

    if Args.AddBack
        [Result.BackData.Data, Result.VarData.Data] = imUtil.background.backVar(Result.ImageData.Data, Args.FinalBackArgs{:});
    end

    % coadd mask
    if Args.AddMask
        Result.MaskData.Dict  = Obj(1).MaskData.Dict; % copy dictionary (pointer)
        Result.MaskData.Data  = squeeze(tools.array.bitor_array(MaskCube, DimIndex, Args.BitCoaddUseMex));
    
        % update Mask to NaN for pixels in which CoaddN<Nim
        Result.MaskData.maskSet(CoaddN<Nim, Args.KeyNaN);
        % Update CoaddLessImages
        Result.MaskData.maskSet( CoaddN<(Args.FracCoaddLess.*Nim), Args.KeyCoaddLess);
       

    end

    % Update header:
    [Result.HeaderData, MidJD] = imProc.stack.coaddHeader(Obj, 'HeaderCopy1', Args.HeaderCopy1,...
                                                      'NewHeader',Args.NewHeader,...
                                                      'UpdateTimes',Args.UpdateTimes,...
                                                      'SumExpTime',Args.SumExpTime,...
                                                      'UpdateImagePathKeys',Args.UpdateImagePathKeys,...
                                                      'StackMethod',StackMethod,...
                                                      'CoaddN',CoaddN,...
                                                      'KeyExpTime',Args.KeyExpTime);


end
