{% set name = "smop" %}
{% set version = "0.41" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "594188a25dc346e27fdd5507a6a0a3cced1cc3defaf02d7e236e41e8714558d4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - smop = smop.main:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - ply
    - numpy
    - scipy
    - networkx
  run:
    - python
    - ply
    - numpy
    - scipy
    - networkx

test:
  imports:
    - smop
  commands:
    - smop --help

about:
  home: https://github.com/victorlei/smop
  license: MIT
  license_family: MIT
  license_file: ''
  summary: Matlab to Python converter
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
