% Functions and Classes list for the telescope.Optics package
% Author : autogenerated (Jun 2023)
%          telescope.Optics.airy - Calculate the monochromatic Airy function (circular diffraction)
%    telescope.Optics.allFunList - Functions and Classes list for the telescope.Optics package
% telescope.Optics.genAveragePSF - Generate an average PSF from multiple speckle images
% telescope.Optics.genAveragePSFn - Generate a multiple-stars PSF from multiple speckle images
%    telescope.Optics.noll_index - Return the Zernike index from the Noll index.
% telescope.Optics.phase_complex - Return the phase of complex numbers.
% telescope.Optics.refraction_index - Return the refraction index as a function of wavelength
% telescope.Optics.telescope_support - Construct an image of a telescope entrance pupil (support).
%      telescope.Optics.unitTest - Package Unit-Test
% telescope.Optics.wavefront2image - Construct an image from the wavefront
% telescope.Optics.zer_cj_variance - The expectency of std of the atmospheric Zernike coefficients.
%    telescope.Optics.zernike_xy - A driver function for the external zerfun.m function.
% telescope.Optics.zerwavefront2image - Wavefront from Zernike polynomials and calculate the image plane.
% telescope.Optics.zerwavefront2image_indiv - Wavefront from individual Zernike polynomials and calculate the image.
 help telescope.Optics.allFunList