% Functions and Classes list for the imUtil.util.fit package
% Author : autogenerated (May 2022)
%     imUtil.util.fit.allFunList - Functions and Classes list for the imUtil.util.fit package
%       imUtil.util.fit.circ_fit - Fit a circle to a set of 2D coordinates on a plane or the sphere
%      imUtil.util.fit.linfit_sc - Linear fitting with weights and sigma clipping
%       imUtil.util.fit.unitTest - Package Unit-Test
 help imUtil.util.fit.allFunList