% Functions and Classes list for the imUtil.spec.extract package
% Author : autogenerated (Jan 2025)
% imUtil.spec.extract.allFunList - Functions and Classes list for the imUtil.spec.extract package
%   imUtil.spec.extract.aperPhot - Given a linear spectrum in a 2D image, extract flux in aperture from each wavelength.
%    imUtil.spec.extract.backStd - Calculate the std of the background in a 2D spectral image.
% imUtil.spec.extract.fitBackground - Fit background to a 2D spectral image
%   imUtil.spec.extract.fitPSF1d - Given a linear spectrum in a 2D image, fit the flux of a line-PSF to each wavelength.
% imUtil.spec.extract.measurePSF - Measure line-PSF in spectral image
 help imUtil.spec.extract.allFunList