% Functions and Classes list for the celestial.map package
% Author : autogenerated (May 2022)
%         celestial.map.amapproj - Old map projection function (not supported)
% celestial.map.plot_monthly_smap - Plot a monthly sky map
%        celestial.map.plot_smap - Given a star catalog plot star map
%      celestial.map.prep_dss_fc - -----------------------------------------------------------------------------
%         celestial.map.unitTest - Package Unit-Test
%       celestial.map.usnob1_map - Plot a finding chart using a local copy of the USNO-B2.0
 help celestial.map.allFunList