% Functions and Classes list for the plot package
% Author : autogenerated (Jun 2023)
%                plot.allFunList - Functions and Classes list for the plot package
%                    plot.axis01 - Plot an axis with grid on X=0 and Y=0 only.
%             plot.cell_contourc - --------------------------------------------------------------------------
%            plot.contour_levels - Break a contour map into seperate contour levels.
%        plot.contour_percentile - Contour plot in which the contours are percentiles of the matrix sum.
%            plot.coo2normalized - Convert plot coordinates to normalized coordinates (between 0 to 1)
%                 plot.date_axis - Add date upper axis.
%         plot.distBetweenPoints - Interactively calculate distances between points on 2D plot
%                plot.draw_iline - Draw line interactively.
%                   plot.errorxy - Plot graphs with error bars in both axes.
%                  plot.errorxy1 - 
%           plot.generate_colors - Generate equally spaced N colors from a given color map.
%                       plot.gno - Get the nearest object handle
%                     plot.graph - Plot second column as a function first column.
%              plot.histCumLabel - Plot an histogram (using histogram) with cumulative fraction label in the upper axis.
%               plot.hist_ofplot - calculate histograms of the X and Y axis of the data in current figure.
%               plot.hist_stairs - Plot an histogram using stairs plot.
%              plot.insert_image - Insert an image to a matlab figure in a given position.
%                      plot.invy - Invert the y-axis of the current axis.
%                   plot.loghist - Plot an histogram in log space.
%                 plot.loglogneg - A loglog plot in which negative values are ploted at -log(abs(val))
%                plot.multi_axis - Create additional x or y axis related by function existing axes.
%              plot.noncont_axis - -------------------------------------------------------------------
%                plot.patch_band - --------------------------------------------------------------------------
%                  plot.plot3bar - -----------------------------------------------------------------------
%              plot.plot_compass - -----------------------------------------------------------------------
%               plot.plot_corner - ----------------------------------------------------------------------------
%                   plot.plot_cs - --------------------------------------------------------------------------
%              plot.plot_ellipse - --------------------------------------------------------------------------
%             plot.plot_find_ind - ---------------------------------------------------------------------------
%              plot.plot_findind - ---------------------------------------------------------------------------
%                   plot.plot_hr - --------------------------------------------------------------------
%                  plot.plot_int - ------------------------------------------------------------------------------
%                 plot.plot_int1 - ------------------------------------------------------------------------------
%          plot.plot_invchildren - --------------------------------------------------------------------------
%             plot.plot_lineprof - -----------------------------------------------------------------------------
%        plot.plot_polygonselect - --------------------------------------------------------------------------
%                   plot.plot_rm - ------------------------------------------------------------------------
%                plot.plot_scale - -------------------------------------------------------------------
%        plot.plot_select_points - --------------------------------------------------------------------------
%                 plot.plot_slit - -----------------------------------------------------------------------
%            plot.plot_speclines - --------------------------------------------------------------------------
%                  plot.plotline - ------------------------------------------------------------------------------
%                   plot.quiver1 - --------------------------------------------------------------------------
%                   plot.splabel - --------------------------------------------------------------------
%          plot.stairsCumulative - Cumulative stairs plot of a vector.
%                  plot.subplot1 - An improved subplot function.
%                 plot.subplot1c - ------------------------------------------------------------------------------
%                   plot.textrel - --------------------------------------------------------------------------
%                  plot.unitTest - Package Unit-Test
%               plot.value2color - --------------------------------------------------------------------------
 help plot.allFunList