% Functions and Classes list for the tools.string package
% Author : autogenerated (Jun 2023)
%        tools.string.allFunList - Functions and Classes list for the tools.string package
% tools.string.construct_fullpath - Construct a full path string to a program name, given its name
% tools.string.construct_keyval_string - --------------------------------------------------------------------------
%      tools.string.find_strcmpi - --------------------------------------------------------------------------
%           tools.string.islower - return true is char array is lower case
%         tools.string.read_date - ------------------------------------------------------------------------------
% tools.string.read_str_formatted - Read a string which is formatted by specidc column positions
%          tools.string.spacedel - recursively delete all spaces from a string.
%         tools.string.spacetrim - Recursively replace any occurance of two spaces with a single space.
%  tools.string.str2double_check - --------------------------------------------------------------------------
%       tools.string.str2num_nan - --------------------------------------------------------------------------
%     tools.string.str_duplicate - Duplicate a string multiple times.
%       tools.string.strcmp_cell - --------------------------------------------------------------------------
%  tools.string.strdouble2double - Convert string, double or any data type to double.
%   tools.string.stringSearchFun - Return a function handle for a string search (i.e., strcmp, strcmpi, regexp, regexpi
%     tools.string.strlines2cell - break the string into a cell array in which each cell contains a line.
%          tools.string.unitTest - Package Unit-Test
%           tools.string.unsplit - unsplit a cell array of strings.
 help tools.string.allFunList