% Functions and Classes list for the imUtil.patternMatch package
% Author : autogenerated (Jun 2023)
% imUtil.patternMatch.allFunList - Functions and Classes list for the imUtil.patternMatch package
% imUtil.patternMatch.find_rot_pairs - Find the best rotation required to match two catalogs using dist-rot hist
% imUtil.patternMatch.find_scalerot_pairs - Find rotation and scale required to match two catalogs using logdist-rot hist
% imUtil.patternMatch.find_shift_pairs - find best X/Y shift between two catalogs from all pairs differences
% imUtil.patternMatch.find_shift_xc_bincat - find best X/Y shift between two catalogs from xcorr binned catalogs
% imUtil.patternMatch.fit_astrometric_tran - Fit astrometric transformation
% imUtil.patternMatch.fit_astrometry - 
%     imUtil.patternMatch.hist2d - calculate the 2-D histogram of 2-D data set.
% imUtil.patternMatch.match_scale_rot_shift - Affine transformation matching of the coordinate systems of two catalogs
% imUtil.patternMatch.matched_cat_residuals - Calculate the astrometric residuals and errors between two matched catalogs
% imUtil.patternMatch.pairOrientationMatching - 
% imUtil.patternMatch.prep_cat_for_astrometry - Clean two catalogs and equalize their surface density
% imUtil.patternMatch.refine_fit - Match sources in two catalogs and fit a positional transformation
% imUtil.patternMatch.select_maxima - Select some maxima out of list by some criteria
%   imUtil.patternMatch.unitTest - Package Unit-Test
 help imUtil.patternMatch.allFunList