create table public.raw_images
(
    pk          bigint generated always as identity
        primary key,
    filename    varchar(256),
    xxhash      varchar(80),
    ra          double precision default 0,
    dec         double precision default 0,
    jd          double precision default 0,
    mount       smallint         default 0,
    camnum      smallint         default 0,
    imtype      varchar(80),
    bitpix      smallint         default 0,
    naxis1      smallint         default 0,
    naxis2      smallint         default 0,
    object      varchar          default ''::character varying,
    expmode     varchar(80)      default ''::character varying,
    counter     integer          default 0,
    exptime     real             default 0,
    gain        real             default 0,
    readnoi     real             default 0,
    darkcur     real             default 0,
    saturval    real             default 0,
    nonlin      real             default 0,
    binx        smallint         default 0,
    biny        smallint         default 0,
    camname     varchar(80)      default ''::character varying,
    camtemp     real             default 0,
    camcool     real             default 0,
    cammode     smallint         default 0,
    camgain     smallint         default 0,
    camoffs     smallint         default 0,
    projname    varchar(256)     default ''::character varying,
    obslon      real             default 0,
    obslat      real             default 0,
    obsalt      real             default 0,
    lst         real             default 0,
    date_obs    varchar(80)      default ''::character varying,
    m_ra        double precision default 0,
    m_dec       double precision default 0,
    m_ha        double precision default 0,
    m_jra       double precision default 0,
    m_jdec      double precision default 0,
    m_jha       double precision default 0,
    ha          double precision default 0,
    equinox     real             default 0,
    m_az        real             default 0,
    m_alt       real             default 0,
    az          real             default 0,
    alt         real             default 0,
    airmass     real             default 0,
    trk_ra      real             default 0,
    trk_dec     real             default 0,
    mnttemp     real             default 0,
    focus       real             default 0,
    prvfocus    real             default 0,
    procstat    varchar(256)     default ''::character varying,
    procversion smallint         default 0
);
