% Functions and Classes list for the TimeDelay package
% Author : autogenerated (May 2022)
%                TimeDelay.A_hat - A_hat operator (Springer & Ofek 2021b)
%           TimeDelay.allFunList - Functions and Classes list for the TimeDelay package
%              TimeDelay.chi2_xF - Return the \chi^2 for fitting astrometric time delay in the time domain
%          TimeDelay.combined_Ft - Reconstruct the combined light curve from the original light curve
%              TimeDelay.content - Content of the +TimeDelay package:
%           TimeDelay.dft_matrix - Return the discrete Fourier Transform matrix
%         TimeDelay.end_matching - Apply end-matching to a light curve such that first and last point have the same flux.
%      TimeDelay.end_matching_xt - Apply end-matching to a center-of-light position consistent with light curve
% TimeDelay.equal_diagonals_matrix - Populate a vector along the diagonals of a matrix (Toplitz matrix)
%             TimeDelay.fft_freq - Return the frequencies off fft with N points and Delta time step D.
% TimeDelay.fit_astrometric_flux - Fit the 2 images astrometric-flux time delay model to observations
% TimeDelay.fit_astrometric_flux_UnevenlySpaced - 
% TimeDelay.fit_astrometric_flux_simple - Fit 2-D lensed images using the simple flux/astrometry method (no red noise)
%             TimeDelay.fit_flux - Fit the 2 images time delay using the flux-only method
%          TimeDelay.fit_fluxBPL - Fit the power spectrum with broken power-law model
%               TimeDelay.logdet - Calculate the log of the determinant of a matrix
%             TimeDelay.logl_BPL - Calculate the log-likelihood for a broken power-law model
%               TimeDelay.logl_F - Calculate the log-likelihood of F, Sigma_F, and Sigma_phi (flux only method)
%              TimeDelay.logl_xF - Return the -logL of x,F - of the astrometric-flux time-delay method
%       TimeDelay.logl_x_given_F - Return the -logL of x | F - of the astrometric-flux time-delay method
%     TimeDelay.plots_for_paperI - Input  : - plot options:
%    TimeDelay.plots_for_paperII - PLot options:
% TimeDelay.power_spectrum_sections - Calculate the power spectrum of unevenly spaced time series with gaps
%          TimeDelay.rand_lensed - Generate evenly spaced combined ligt curve and position of lensed quasar
%     TimeDelay.rand_lensed_uneq - unequally spaced lensed quasar light curves and center of light position
%             TimeDelay.rand_psd - Generate a random vector with distribution following some power spectrum.
%       TimeDelay.reconstruct_ft - Reconstruct f(t) of a lensed quasar from the combined light and position
%            TimeDelay.sigma_phi - Calculate Sigma_phi and Sigma_F
%       TimeDelay.split2sections - Split a time series to sections in which the gaps have a maximum.
% TimeDelay.witt_timedelay_formula - Calculate the time delay for isothermal elliptical potential (Witt formula)
 help TimeDelay.allFunList