% Functions and Classes list for the imUtil.headerCell package
% Author : autogenerated (Jun 2023)
%   imUtil.headerCell.allFunList - Functions and Classes list for the imUtil.headerCell package
% imUtil.headerCell.cellhead2struct - convert a 3-column cell array containing header into a structure.
%    imUtil.headerCell.deleteKey - delete lines with specific keys
%     imUtil.headerCell.getByKey - get keyword value from an header in a cell format
%    imUtil.headerCell.getIndKey - get a cell array in which each cell contains the indices of the found keys in the cell-header.
% imUtil.headerCell.getValBySynonym - Return the first key/val in the list of synonyms that appears in the cell-header.
%    imUtil.headerCell.insertKey - Insert key/val into a header in cell array format
%   imUtil.headerCell.replaceKey - Replace an cell-header keywords and values, or add if doesn't exist
% imUtil.headerCell.replace_illegal_char - replace illegal characters in keyword names (e.g. '-').
%    imUtil.headerCell.uniqueKey - Remove non-unique keywords from a cell header
% imUtil.headerCell.updateCellFromStruct - update cell header by adding elements in struct not in header
 help imUtil.headerCell.allFunList