% Functions and Classes list for the imProc.cat package
% Author : autogenerated (Jun 2023)
%            imProc.cat.affine2d - Apply affine transformation to AstroCatalog, or catalog in AstroImage
%          imProc.cat.allFunList - Functions and Classes list for the imProc.cat package
%   imProc.cat.applyProperMotion - Apply proper motion and parallax to sources in AstroCatalog object
% imProc.cat.filterForAstrometry - Given two catalogs, match their surface density and filter sources.
%     imProc.cat.findSourceInCat - find a single source by coordinates in a list of AstroCatalog of FITS tables.
% imProc.cat.fitPeakMultipleColumns - Given N columns with some property (e.g., S/N) fit a parabola
% imProc.cat.getAstrometricCatalog - Get Astrometric catalog from local/external database
%         imProc.cat.insertAzAlt - Calculate and insert Az, Alt, AirMass, ParAng columns to AstroCatalog object
%      imProc.cat.insertImageVal - Insert Image values at specific positions into an AstroCatalog
% imProc.cat.searchExternalCatOrphans - Search for orphans using MergedCat external catalog information
%            imProc.cat.unitTest - unitTest for imProc.cat
 help imProc.cat.allFunList