function [MS] = catalog2MatchedSources(AC, Args)
    % Build MatchedSources from matched AstroCatalog objects
    %   Combine AstroCatalog object containing multiple catalogs (e.g.,
    %   epochs) into a singe MatchedSources object.
    %   If 'MasterInd' is provided (generated by imUtil.match.mex.matchCatalogs
    %   or imUtil.match.mex.matchCatalogsXY). Then MasterInd assume to
    %   contain column per epoch/catalog, and row per unique star.
    %   MasterInd contains the cross indices requires in order to match the
    %   catalogs, such that the MatchedSources object will contain [Epoch X
    %   UniqueSources].
    % Input  : - An AstroCatalog or AstroImage object.
    %          * ...,key,val,... 
    %            'MasterInd' - An [Nunique X Nobj] matrix, containing the index of the unique
    %                   source in the corresponding epoch. If the source doesn't
    %                   appear then a NaN appear in the matrix.
    %                   If empty, then require that all catalogs have the
    %                   same number of rows.
    %                   Default is [].
    %            'Col' - A cell array of column names to extract from the
    %                   AstroCatalog object. The Data structure (in the
    %                   MatchedSources object) will have a field per column
    %                   name.
    %                   Default is {'RA','Dec','X','Y','FLAGS','MAG_APER_3','MAGERR_APER_3','MAG_PSF','MAGERR_PSF'};
    %            'CopyJD' - A logical indicating if to copy the JD from he
    %                   AstroCatalog into the MatchedSources object.
    %                   Default is true.
    % Output : - A MatchedSources object.
    % Author : Eran Ofek (2026 Apr) 
    % See also: imProc.match.unify
    % Example: MS=imProc.cat.catalog2MatchedSources(AC, 'MasterInd',MasterInd);

    arguments
        AC
        Args.MasterInd         = [];
        Args.Col               = {'RA','Dec','X','Y','FLAGS','MAG_APER_3','MAGERR_APER_3','MAG_PSF','MAGERR_PSF'};
        Args.CopyJD            = true;
    end

    % check MasterInd / or catalogs size
    Nobj = numel(AC);  % number of epochs
    NrowCat = AC.sizeCatalog;
    if isempty(Args.MasterInd)
        if all(NrowCat(1)==NrowCat)
            % All catalogs have the same number of rows - assumed they are
            % matched

            % valid case
        else
            error('MasterInd is not provided and the catalogs have different number of rows - use unify');
        end
        NrowFinal = NrowCat(1);
    else
        if size(Args.MasterInd,2) ~= Nobj
            error('MasterInd must have the same number of columns as the number of catalogs');
        end
        NrowFinal = size(Args.MasterInd, 1);
    end
    % NrowFinal is the number of sources

    % Init MatchedSources Data property:
    
    Ncol = numel(Args.Col);
    % CellSt = cell(1, Ncol.*2);
    % CellSt(1:2:end-1) = Args.Col;
    % [CellSt{2:2:end}] = deal(nan(Nobj, NrowFinal));
    % Data = struct(CellSt{:});
    % more efficient way:
    Data = cell2struct(repmat({nan(Nobj, NrowFinal)}, 1, numel(Args.Col)), Args.Col, 2);


    MS = MatchedSources();

    for Iobj=1:1:Nobj
        Cat    = AC(Iobj).getCatData;
        ColVal = Cat.getCol(Args.Col);

        if isempty(Args.MasterInd)
            for Icol=1:1:Ncol
                Data.(Args.Col{Icol})(Iobj,:) = ColVal(:,Icol).';
            end
        else
            Ind = Args.MasterInd(:,Iobj);
            I1  = ~isnan(Ind);
            I2  = Ind(I1);

            for Icol=1:1:Ncol
                Data.(Args.Col{Icol})(Iobj,I1) = ColVal(I2, Icol).';
            end

        end

    end
    MS.Data = Data;
    if Args.CopyJD
        MS.JD   = AC.julday;
    end

end
