# Amazon Web Services
#
# Notes:
#
# Use http://www.yamllint.com/
#

# General settings
Account:

    email       : ultrasatdev@gmail.com
    domain      : http://ultrasatdev.org/
    


Sqs:

    
    