
Negative         : [0  ,       'Negative']
PSFChi2          : [1  ,       'PSFChi2']
Saturated        : [2  ,       'Saturated']
BadPixelHard     : [3  ,       'BadPixelHard']
BadPixelSoft     : [4  ,       'BadPixelSoft']
SNR              : [5  ,       'SNR']
StarMatch        : [6  ,       'StarMatch']
MPMatch          : [7  ,       'MPMatch']
Ringing          : [8  ,       'Ringing']
Overdensity      : [9  ,       'Overdensity']
PeakDist         : [10 ,       'PeakDist']
LIMMAG           : [11 ,       'LIMMAG']
PVDist           : [12 ,       'PVDist']
Translient       : [13 ,       'Translient']
Scorr            : [14 ,       'Scorr']
PSFShape         : [15 ,       'PSFShape']
Streak           : [16 ,       'Streak']
