
GAIA_DRE3        : [0,  'GAIA-EDR3']
unWISE           : [1,  'unWISE (Schlafly et al. 2019)']
tMASS            : [2,  '2MASS (Skrutskie et al. 2006)']
GLADE            : [3,  'GLADE']
PGC              : [4,  'PGC galaxy catalog (Paturel et al. 1989)']
SDSS_DR10        : [5,  'SDSS-DR10 sources']
PS1_DR1          : [6,  'PS1-DR1']
DECaLS_DR4       : [7,  'DECaLS-DR4']
GALEX            : [8,  'GALEX']
FIRST            : [9,  'FIRST']
NVSS             : [10, 'NVSS']
VLASSep1         : [11, 'VLASS epoch 1 (Lacy et al. 2020)']
LAMOST_DR4       : [12, 'LAMOST-DR4']
NED              : [13, 'NED']
SpecSDSS_DR14    : [14, 'SDSS spectroscopy DR14']
ROSAT_FSC        : [15, 'ROSAT faint source catalog']
XMM              : [16, 'XMM']
ztfDR1var        : [17, 'Variable sources ZTF-DR1']
WD               : [18, 'WD']
QSO              : [19, 'QSO']
GAIADR3_ext      : [20, 'GAIA-DR3 extragalactic (GAIA coolaboration et al. 2022)']