
Saturated        : [0  ,       'Pixel is saturated']
LowRN            : [1  ,       'Pixel noise is low (Var<median(Var).*0.05) (probably dead)']
HighRN           : [2  ,       'Pixel noise is high (Var>10*median(Var)) (noisy pixel)']
DarkHighVal      : [3  ,       'Pixel bias/dark value is high (>2*Mean)']
DarkLowVal       : [4  ,       'Pixel bias/dark value is low (<0.2*Mean)']
BiasFlaring      : [5  ,       'Pixel is possibly flaring (>20 sigma)']
NaN              : [6  ,       'Pixel is NaN due to illegal arithmatics']
FlatHighStd      : [7  ,       'Flat Std/sqrt(N) is high (Std/sqrt(N)>0.01)']
FlatLowVal       : [8  ,       'Flat normalized value is low (<0.1)']
LowQE            : [9  ,       'Pixel with low QE (<0.5 from the nominal)']
Interpolated     : [10 ,       'Pixel with interpolated value']
Hole             : [11 ,       'Hole (anti-star)']
Spike            : [12 ,       'Diffraction spike']
CR_DeltaHT       : [13 ,       'CR identified using HT to delta function']
CR_Laplacian     : [14 ,       'CR identified using laplacian filter']
CR_Streak        : [15 ,       'CR streak']
Ghost            : [16 ,       'Ghost']
Persistent       : [17 ,       'Persistent charge']
Xtalk            : [18 ,       'Cross talk']
Streak           : [19 ,       'Streak']
ColumnLow        : [20 ,       'Bad column low values']
ColumnHigh       : [21 ,       'Bad column high values']
NearEdge         : [22 ,       'Near image edge']
NonLinear        : [23 ,       'Non linear']
Bleeding         : [24 ,       'Possible bleeding/blooming']
Overlap          : [25 ,       'In overlap region']
SrcNoiseDominated: [26 ,       'S/N is source dominated (Val-Back)>Back']
GainHigh         : [27 ,       'In duel gain-detectors: Gain is high']
CoaddLessImages  : [28 ,       'Number of images in coadd is less than X percent']
SrcDetected      : [29 ,       'Source detected (all pixels within 1xFWHM radius from detected source)']