NO_BKG           : [0,       'No image background and variance']
NO_SRC           : [1,       'No sources in image']
NO_PSF           : [2,       'No PSF for image']
NO_ASTR          : [3,       'No astrometric solution for image']
NO_PHOTCAL       : [4,       'No photometric calibration for image']
NO_MERGE         : [5,       'No merged mat catalog']
NO_COADD         : [6,       'No visit coadd image']
NO_RELZP         : [7,       'No relative photometric zero point for the sub image group']
NOT_GOOD         : [8,       'Image not used for the coadd and the matched sources']
FEW_SRC          : [9,       'Fewer sources than the coaddition threshold (MinNstars)']
HIGH_BKGRAD      : [10,      'Background gradient over the epoch above the threshold (MaxFracGrad)']
