
Saturated        = [0]         // Pixel is saturated
LowRN            = [1]         // Pixel noise is low (<0.05*RN) [probably dead]
HighRN           = [2]         // Pixel noise is high (>10*RN) [noisy pixel]
DarkHighVal      = [3]         // Pixel bias/dark value is high (>2*Mean)
DarkLowVal       = [4]         // Pixel bias/dark value is low (<0.2*Mean)
BiasFlaring      = [5]         // Pixel is possibly flaring
NaN              = [6]         // Pixel is NaN due to illegal arithmatics
FlatHighStd      = [7]         // Flat Std/sqrt(N) is high [Std/sqrt(N)>0.01]
FlatLowVal       = [8]         // Flat normalized value is low [<0.1]
LowQE            = [9]         // Pixel with low QE (<0.5 from the nominal)
Hole             = [10]        // Hole (anti-star)
Spike            = [11]        // Diffraction spike
CR_DeltaHT       = [12]        // CR identified using HT to delta function
CR_Laplacian     = [13]        // CR identified using laplacian filter
CR_Streak        = [14]        // CR streak
CRsub_DeltaHT    = [15]        // CR identified using HT to delta function, after subtraction
CRsub_Laplacian  = [16]        // CR identified using laplacian filter, after subtraction
CRsub_Streak     = [17]        // CR streak, after subtraction
Ghost            = [18]        // Ghost
Persistent       = [19]        // Persistent charge
Xtalk            = [20]        // Cross talk
Streak           = [21]        // Streak
ColumnLow        = [22]        // Bad column low values
ColumnHigh       = [23]        // Bad column high values
NearEdge         = [24]        // Near image edge
NonLinear        = [25]        // Non linear
Bleeding         = [26]        // Possible bleeding/blooming
Overlap          = [27]        // In overlap region
SN100            = [28]        // S/N in pix> 100
SN30             = [29]        // S/N in pix> 30
SN_SrcDominated  = [30]        // S/N is source dominated (Val-Back)>Back
GainHigh         = [31]        // In duel gain-detectors: Gain is high