
Negative         : [0  ,       'Negative']
PSFChi2          : [1  ,       'PSFChi2']
Saturated        : [2  ,       'Saturated']
BadPixelHard     : [3  ,       'BadPixelHard']
BadPixelSoft     : [4  ,       'BadPixelSoft']
SNR              : [5  ,       'SNR']
StarMatch        : [6  ,       'StarMatch']
MPMatch          : [7  ,       'MPMatch']
Ringing          : [8  ,       'Ringing']
Overdensity      : [9  ,       'Overdensity']
NPSFShape        : [10 ,       'NPSFShape']
LIMMAG           : [11 ,       'LIMMAG']
PVDist           : [12 ,       'PVDist']
Translient       : [13 ,       'Translient']
Scorr            : [14 ,       'Scorr']
DPSFShape        : [15 ,       'DPSFShape']
Streak           : [16 ,       'Streak']
CRDelta          : [17 ,       'CRDelta']
Variable         : [18 ,       'Variable']
NuclearNoise     : [19 ,       'NuclearNoise']
SubVisit         : [20 ,       'SubVisit']