
Saturated        = [0]         // Pixel is saturated
BiasStdLow       = [1]         // Pixel noise is low (<0.05*RN) [probably dead]
BiasStdHigh      = [2]         // Pixel noise is high (>10*RN) [noisy pixel]
BiasHighVal      = [3]         // Pixel bias value is high (>2*Mean)
BiasLowVal       = [4]         // Pixel bias value is low (<0.2*Mean)
BiasFlaring      = [5]         // Pixel is possibly flaring
NaN              = [6]         // Pixel is NaN due to illegal arithmatics
FlatHighStd      = [7]         // Flat Std/sqrt(N) is high [Std/sqrt(N)>0.01]
FlatLowVal       = [8]         // Flat normalized value is low [<0.1]
Hole             = [9]         // Hole (anti-star)
Spike            = [10]        // Diffraction spike
CR_DeltaHT       = [11]        // CR identified using HT to delta function
CR_Laplacian     = [12]        // CR identified using laplacian filter
CR_Streak        = [13]        // CR streak
CRsub_DeltaHT    = [14]        // CR identified using HT to delta function, after subtraction
CRsub_Laplacian  = [15]        // CR identified using laplacian filter, after subtraction
CRsub_Streak     = [16]        // CR streak, after subtraction
Ghost            = [17]        // Ghost
Streak           = [18]        // Streak
ColumnLow        = [19]        // Bad column low values
ColumnHigh       = [20]        // Bad column high values
NearEdge         = [21]        // Near image edge
NonLinear        = [22]        // Non linear
Overlap          = [23]        // In overlap region
SN100            = [25]        // S/N in pix> 100
SN30             = [26]        // S/N in pix> 30
SN_SrcDominated  = [27]        // S/N is source dominated (Val-Back)>Back