# Database Configuration File
#
# Notes:
#   1. Key names should match DbConnection's properties names 
#      (i.e. there is DbConnection.Host)
#
#
#


# DbConnection, used by db.DbConnection.m
DbConnection:

    # Default values, override by adding values to per-database section under Items below
    Default:
        Host            : 'gauss'           # Host name or IP address
        DriverName      : 'postgres'        # Driver name
        UserName        : 'admin'           # Login user
        Password        : 'Passw0rd'        # Login password
        Port            : 5432              # Port number, 5432 for PostgresV13, 5433 for PostgresV14


    # Default values, override by adding values to per-database section under Items below
    DefaultV13_Win:
        Host            : 'localhost'       # Host name or IP address
        DriverName      : 'postgres'        # Driver name
        UserName        : 'postgres'        # Login user
        Password        : 'pass'            # Login password
        Port            : 5432              # Port number
        

# Databases, items names are used by DbConnection
DbConnections:

    #
    UnitTest:
        DatabaseName    : 'unittest'        # Database name
        
        # User defined data, used it test
        DoubleFields    : 'fdouble1,fdouble2,fdouble3,fdouble4,fdouble5,fdouble6,fdouble7,fdouble8,fdouble9,fdouble10'

    #
    Pipeline:
        DatabaseName    : 'pipeline'        # Database name

    #
    Last:
        DatabaseName    : 'last'            # Database name

    #
    Observations:
        DatabaseName    : 'observations'    # Database name

    #
    Soc:
        DatabaseName    : 'observations'    # Database name

