
AttitudeTweak         : [0  ,       'Attitude Tweak']
SafeMode              : [1  ,       'Safe Mode']
CoarsePoint           : [2  ,       'Spacecraft is in Coarse Point']
EarthPoint            : [3  ,       'Spacecraft is in Earth Point']
Argabrithening        : [4  ,       'Argabrightening event']
WheelDesaturation     : [5  ,       'Reaction Wheel desaturation Event']
CosmicRayAperture     : [6  ,       'Cosmic Ray in Optimal Aperture pixel']
AnomalyExlude         : [7  ,       'Manual Exclude. The cadence was excluded because of an anomaly']
CadenceDiscontinuity  : [8  ,       'Discontinuity corrected between this cadence and the following one.']
ImpulsiveOutlier      : [9  ,       'Impulsive outlier removed before cotrending.']
CosmicRayCollateral   : [10 ,       'Cosmic ray detected on collateral pixel row or column.']
Straylight            : [11 ,       'Straylight from Earth or Moon in camera FOV (predicted).']
ScatteredLightExclude : [12 ,       'Scattered Light Exclude (spoc-4.0.5 and later).']
PlanetSearchExclude   : [13 ,       'Planet Search Exclude (spoc-4.0.5 and later).']
BadCalExclude         : [14 ,       'Bad Calibration Exclude (spoc-4.0.14 and later).']
InsufficientTargets   : [15 ,       'Insufficient Targets for Error Correction Exclude (spoc-4.0.14 and later).']
