


EXPTIME : ['AEXPTIME', 'EXPTIME','EXPOSURE']
IMTYPE  : ['IMTYPE', 'TYPE', 'IMGTYPE','IMAGETYP','IMGTYP','FILETYPE']
READNOI : ['READNOI', 'RRDNOISE', EADNOIS', 'RN', 'RON']
GAIN    : ['GAIN']
OBSLON  : ['OBSLON', 'LON','GEOLON','GEODLON','LONG','LONG-OBS']
OBSLAT  : ['OBSLAT', 'LAT','GEOLAT','GEODLAT','LAT-OBS']
OBSALT  : ['OBSALT','HEIGHT','ELEVAT','OBSEL','ALTIT','ALT-OBS']
DATEOBS : ['DATEOBS','DATE-OBS','UTC-OBS','DATE']
TIMEOBS : ['TIMEOBS','TIME-OBS']
FILTER  : ['FILTER','FILT','FILTER1']
SATURVAL: ['SATURVAL','SATURAT','SATLEVEL','SATVAL']
CAMTEMP : ['CAMTEMP','CAMERAT','TEMPCAM','TEMP_CAM','CAM_TEMP']
TIMEZONE: ['TIMEZONE']
PROJNAME: ['PROJNAME','INSTRUME']
SENSTEMP: ['SENSTEMP','CCD-TEMP']
DICHROIC: ['DICHROIC']
SLIT    : ['SLIT','APERTURE','SLITWIDT']
PARANG  : ['PARANG','PARALLAC']
ARCS    : ['ARCS','LAMPS']
GRATING : ['GRATING']
ANGLE   : ['ANGLE','GRANGLE']
BINX    : ['BINX']
BINY    : ['BINY']
