


EXPTIME : ['AEXPTIME', 'EXPTIME','EXPOSURE']
IMTYPE  : ['IMTYPE', 'IMGTYPE','IMAGETYP','IMGTYP','FILETYPE']
READNOI : ['READNOI', 'READNOIS','RN']
GAIN    : ['GAIN']
OBSLON  : ['OBSLON', 'LON','GEOLON','GEODLON','LONG']
OBSLAT  : ['OBSLAT', 'LAT','GEOLAT','GEODLAT']
DATEOBS : ['DATEOBS','DATE-OBS','UTC-OBS','DATE']
TIMEOBS : ['TIMEOBS','TIME-OBS']
FILTER  : ['FILTER','FILT','FILTER1']
SATURVAL: ['SATURVAL','SATURAT','SATLEVEL','SATVAL']
CAMTEMP : ['CAMTEMP','CAMERAT','TEMPCAM','TEMP_CAM','CAM_TEMP']
