


EXPTIME : ['AEXPTIME', 'EXPTIME','EXPOSURE']
IMTYPE  : ['IMTYPE', 'IMGTYPE','IMAGETYP','IMGTYP']
READNOI : ['READNOI', 'READNOIS','RN']
OBSLON  : ['OBSLON', 'LON','GEOLON','GEODLON','LONG']
OBSLAT  : ['OBSLAT', 'LAT','GEOLAT','GEODLAT']
DATEOBS : ['DATEOBS','DATE-OBS']
FILTER  : ['FILTER','FILT','FILTER1']
SATURVAL: ['SATURVAL','SATURAT','SATLEVEL','SATVAL']

