InstallationLocation : '~/matlab/data'
# The following are cell arrays of entry per dataset
DataName             : 'PicklesStellarSpec'
SubDir               : 'spec/PicklesStellarSpec'
URL                  : ['https://euler1.weizmann.ac.il/archive/AstroPack/data/spec/PicklesStellarSpec.tar']
Size                 : 8
SearchFile           : ''
Description          : 'Pickles Stellar Spectra Templates'
