# ULTRASAT Planner - Used by files in these folders:
# 
#    matlab/astro/+ultrasat/+api/
#    matlab/astro/+ultrasat/+planner/
#    matlab/astro/+ultrasat/+planner/+gui/
#

PlannerApi:
    # client / local
    mode: client
    
    # URL of simple_file_server.py, currently should be run on host 'socsrv' 
    # server_url: "http://localhost:8090"
    server_url: "http://socsrv:8090"
    
    # Path of files on local file system, to be used as stand-alone
    local_db_path: ""
    
    