ZENITHAL  : ['TAN', 'TPV', 'TAN-SIP', 'SIN', 'NCP', 'AZP', 'SZP', 'STG', 'ARC', 'ZPN', 'ZEA', 'AIR']
CYLINDRICAL : ['CYP','CEA','CAR','MER']
PSEUDOCYLINDRICAL : ['SFL','PAR','MOL','AIT']
CONIC : ['COP','COE','COD','COO']
POLYCONIC : ['BON','PCO']
QUADCUBE : ['TSC','CSC','QSC']
