TYPE  : []
PROJECT  : []
INST  : []
EXPTIME  : []
STARTTIME  : []
SCALE  : []
LIMMAG_DETECTION  : []
FILTER  : []
NAXIS  : []
NAXIS1  : []
NAXIS2  : []
BINX  : []
BINY  : []
TEMP_OUT  : []
WIND_DIR  : []
WIND_SPEED  : []
HUMID_OUT  : []
PRESSURE  : []
LIGHT  : []
SENSOR_TEMP  : []
OBJRA  : []
OBJDEC  : []
TELRA  : []
TELDEC  : []
OBJECT  : []
OBSRA  : []
OBSDEC  : []
FIELDROT  : []
RA  : []
DEC  : []
FIELD_ID  : []
HA  : []
LST  : []
ALT  : []
AZ  : []
AIRMASS  : []
MOONAZ  : []
MOONALT  : []
MOONILL  : []
MOONDIST  : []
SUNAZ  : []
SUNALT  : []
OBSLONG  : []
OBSLAT  : []
OBSEL  : []
    
