% Functions and Classes list for the astro.supernova package
% Author : autogenerated (Jun 2023)
%     astro.supernova.allFunList - Functions and Classes list for the astro.supernova package
% astro.supernova.filterVariableFun - NOT DEBUGED
%    astro.supernova.fit_sn_rise - Fit rise-time of SN light curve
% astro.supernova.interacting_sn_prop - Calculate the properties of CSM-ejecta interacting SN
% astro.supernova.kilonova_multizone - Calculate the Waxman et al. analytic multizone kilonova model
% astro.supernova.mildrel_synchrotron - SHORT DESCRIPTION HERE
% astro.supernova.nickel56_decay - Energy production of Nickel56->Cobalt->Iron
% astro.supernova.sn_cooling_msw - --------------------------------------------------------------------------
% astro.supernova.sn_cooling_rw_my - Shock cooling light curve (Rabinak & Waxman 2011)
%  astro.supernova.sn_cooling_sw - --------------------------------------------------------------------------
% astro.supernova.sync_mildly_relativistic - Synchrotron emission from mildly relativistic ejecta interacting with ISM
%    astro.supernova.synchrotron - SHORT DESCRIPTION HERE
%       astro.supernova.unitTest - Package Unit-Test
%   astro.supernova.SOPRANOS.PDF - calculate Probabiliy Distribution Function (PDF) for a given SW17 shock cooling model
% astro.supernova.SOPRANOS.SOPRANOS_GUI - SOPRANOS_GUI MATLAB code for SOPRANOS_GUI.fig
% astro.supernova.SOPRANOS.allFunList - Functions and Classes list for the astro.supernova.SOPRANOS package
% astro.supernova.SOPRANOS.calcGrid - Calculate chi2/dof grid
% astro.supernova.SOPRANOS.cubicZeros - this functions solves the cubic equation of the form:
% astro.supernova.SOPRANOS.findMaximum - Find numerically the maximum likelihood
% astro.supernova.SOPRANOS.load_GALEX - load GALEX data from the GALEX/PTF experiment
% astro.supernova.SOPRANOS.plotGrid - Plot the likelihood grid calculated by calcGrid
% astro.supernova.SOPRANOS.prepareSNdata - Prepare Observation data and ancillary data for a SN
% astro.supernova.SOPRANOS.prepare_LCs - Prepare Model light curves for interpolation
% astro.supernova.SOPRANOS.readPTFout - read PTF out file
% astro.supernova.SOPRANOS.readUVOTascii - readUVOTascii Import UVOT subtracted data from an ascii file.
% astro.supernova.SOPRANOS.readZTF - read ZTF data file as exported from ZTF marshal
% astro.supernova.SOPRANOS.readZTFtxt - read ZTF text file
% astro.supernova.SOPRANOS.unitTest - Package Unit-Test
% astro.supernova.SOPRANOS.ztfBands - Split the table into different bands and read the filter Obj
% astro.supernova.SOPRANOS.ztfBandsTxt - Split the table into different bands and read the filter Obj
 help astro.supernova.allFunList