% Functions and Classes list for the tools.math.fun package
% Author : autogenerated (May 2023)
%      tools.math.fun.allFunList - Functions and Classes list for the tools.math.fun package
%    tools.math.fun.chebyshevFun - Generate an anonymous function for Chebyshev polynomials (using
%          tools.math.fun.sincos - Insert a column/s or row/s to a specific position in a matrix.
 help tools.math.fun.allFunList