% Functions and Classes list for the tools.math.fun package
% Author : autogenerated (May 2022)
%    tools.math.fun.chebyshevFun - Generate an anonymous function for Chebyshev polynomials (using
 help tools.math.fun.allFunList