% Functions and Classes list for the tools.find.mex package
% Author : autogenerated (Jan 2025)
%       tools.find.mex.findEqual - Find values in an array (fast mex version of find)
% tools.find.mex.findLargerFirst - Find the index of the first element in an array which is larger then some value (fast mex).
% tools.find.mex.findSmallerFirst - Find the index of the first element in an array which is smaller then some value (fast mex).
 help tools.find.mex.allFunList