% Functions and Classes list for the VO.search package
% Author : autogenerated (Jun 2023)
%           VO.search.allFunList - Functions and Classes list for the VO.search package
%        VO.search.astcat_search - Search an astronomical catalog formatted in HDF5/HTM/zones format
%             VO.search.cat_cone - Cone search a local or online catalog.
%    VO.search.catalog_interface - An interface auxilary to the catalogs in the data directory
%              VO.search.get_cat - Search selected astronomical catalogs
%         VO.search.htmcat_names - Get names of all HDF5/HTM catalogs in the /data/catsHTM/ directory.
%        VO.search.htmcat_search - Cone earch on local HDF5/HTM catalog (OBSOLETE).
%           VO.search.match_cats - Match two spherical coordinates catalogs sorted by declination
%        VO.search.match_cats_pl - Match two planer coordinates catalogs sorted by Y
%        VO.search.prep_data_dir - Prepare interface functions for the catalogs in the data directory
% VO.search.proper_motion_sdss_ps1 - SHORT DESCRIPTION HERE
%           VO.search.search_cat - Given a catalog with Long,Lat coordinates position, search for lines near a list of reference positions.
%        VO.search.search_htmcat - Search a local HTM/HDF5 catalog
%      VO.search.search_mhtm_cat - Search master HTM catalog
% VO.search.search_sortedY_multi - Search a single X/Y in a catalog sorted by Y (planar geometry)
%     VO.search.search_sortedlat - Search a single long/lat in a catalog sorted by latitude
% VO.search.search_sortedlat_multi - Search a single long/lat in a catalog sorted by latitude
% VO.search.search_sortedlat_multiNearest - Search a single long/lat in a catalog sorted by latitude
%    VO.search.search_sortedlong - Search a single long/lat in a catalog sorted by longitude
%           VO.search.simbad_url - Generate a SIMBAD URL for coordinates
 help VO.search.allFunList