% Functions and Classes list for the tools.cell package
% Author : autogenerated (Jun 2023)
%          tools.cell.allFunList - Functions and Classes list for the tools.cell package
%         tools.cell.cell2_equal - Check if two cell array have an identical content
%        tools.cell.cell2mat_nan - Convert numeric cell to matrix. Replace empty cells with NaNs.
%   tools.cell.cellNumericSuffix - Add a range of numeric suffix to a string and put result in a cell array.
%          tools.cell.cell_equal - Compare the content of a cell array to its first cell.
%    tools.cell.cell_find_groups - Find all cell lines with identical values, and return indices of groups.
%         tools.cell.cell_insert - Insert elements within a cell array.
%        tools.cell.cell_sprintf - sprintf on content in cell array
% tools.cell.cellstr2num_dictionary - Given a cell array of strings, repace unique strings by numeric index
%      tools.cell.cellstr_prefix - Add a prefix to all the strings in a char array.
%       tools.cell.group_cellstr - Find and group distinct values in a cell array.
%            tools.cell.ind_cell - Select indices of vectors in cell array of vectors.
%        tools.cell.isempty_cell - Check if each cell element is empty.
%          tools.cell.isnan_cell - Check if cell elemt is NaN.
% tools.cell.remove_cell_element - Remove a list of indices from a cell vector.
%   tools.cell.sort_numeric_cell - sort each row or columns in a cell array of numbers.
%        tools.cell.sprintf2cell - Generate a cell array of string using sprintf.
%  tools.cell.sprintf_concatCell - Concat a multiple cell arrays content into a string
%     tools.cell.strNameDict2ind - Search the first appearance of string in dictionary in another cell.
% tools.cell.unique_cell_grouping - Find unique lines in the cell matrix.
%            tools.cell.unitTest - Package Unit-Test
 help tools.cell.allFunList