% Functions and Classes list for the pipeline.generic package
% Author : autogenerated (Jun 2023)
%    pipeline.generic.allFunList - Functions and Classes list for the pipeline.generic package
% pipeline.generic.imagesSequence2LC - Generate light curves of stationary sources from a sequence of raw images
% pipeline.generic.multiRaw2procCoadd - Basic processing of a multiple raw image, of the same field, into a processed images and coadd image
%     pipeline.generic.procCoadd - Coadd a list of processed images, estimate background and find sources in the coadd images.
% pipeline.generic.procMergeCoadd - Given a list of processed images, merged their catalogs, coadd
% pipeline.generic.singleRaw2proc - Basic processing of a single raw image into a processed image
%      pipeline.generic.unitTest - Package Unit-Test
 help pipeline.generic.allFunList