% Functions and Classes list for the VO.VizieR package
% Author : autogenerated (Jun 2023)
%           VO.VizieR.allFunList - Functions and Classes list for the VO.VizieR package
%      VO.VizieR.catalog_mapping - Mapping of VizieR catalogs columns
%    VO.VizieR.cds_astcat_search - Query a VizieR catalog using the cdsclient tools
%       VO.VizieR.cdsclient_path - Return the path of the local cdsclient directory
% VO.VizieR.cdsclient_prog_names - Return the list of programs in the cdsclient directory
%   VO.VizieR.construct_vizquery - Constrct a query string for the Vizier cdsclient command line
 help VO.VizieR.allFunList