% Functions and Classes list for the tools.math.geometry package
% Author : autogenerated (Jun 2023)
%   tools.math.geometry.Contents - 
% tools.math.geometry.allFunList - Functions and Classes list for the tools.math.geometry package
% tools.math.geometry.boundingCircle - fit the smallest-radius bounding circle to set of X, Y points
% tools.math.geometry.cells_intersect_line - Find cells in 2D grid that intersets a line.
% tools.math.geometry.cross1_fast - Fast version of cross product of two 3-elements vectors
% tools.math.geometry.cross_fast - Fast cross product of two 3-elements matrices
%    tools.math.geometry.curvlen - Calculate the length of a curve numerically.
% tools.math.geometry.dist_box_edge - Distance of points froma rectangular box.
% tools.math.geometry.dist_p2line - Distance between point and a line.
% tools.math.geometry.plane_dist - Distance between points on a 2D plane.
% tools.math.geometry.plane_dist_thresh - Check if the distance between points on a plane is below some value.
%   tools.math.geometry.polysort - Sort the vertices of convex polygon by position angle.
%       tools.math.geometry.rotm - Return a numeric or symbolic 3-D rotation matrix about the X, Y or Z axis
% tools.math.geometry.traj_mindist - Time of minimum distance between two 2-D linear trajetories
% tools.math.geometry.tri_equidist_center - Poistion of circumscribed circle.
%   tools.math.geometry.unitTest - Package Unit-Test
 help tools.math.geometry.allFunList