% Functions and Classes list for the imUtil.image package
% Author : autogenerated (Jun 2023)
%        imUtil.image.allFunList - Functions and Classes list for the imUtil.image package
%         imUtil.image.cube_chi2 - Calculate the sigma-clipped mean of a dataset
%               imUtil.image.fit - Return the chi^2 of a model to an image.
% imUtil.image.fun_binary_withVariance - Applay an operator on an array and its variance.
% imUtil.image.fun_unary_withVariance - Applay an operator on an array and its variance.
%       imUtil.image.images2cube - Store a set of images of the same size in a cube.
%      imUtil.image.ind2sub_fast - ind2sub fast version for 2D matrices
%      imUtil.image.local_maxima - Identify local maxima above a threshold in a 2D image
%      imUtil.image.mean_sigclip - Calculate the sigma-clipped mean of a dataset
%           imUtil.image.moment2 - Calculate 1st, 2nd moments and (weighted) aperture photometry
%        imUtil.image.replaceVal - Search all pixels in image that are equal to some value or in/out of range with a new value.
%       imUtil.image.sparse2full - Resize/extend/magnify an image sampled at some specific very sparse points into a full image.
%         imUtil.image.stackCube - Stack (coadd) a cube of images using various functions
%    imUtil.image.sub2ind3d_fast - sub2ind fast version for 2D matrices
%      imUtil.image.sub2ind_fast - sub2ind fast version for 2D matrices
%          imUtil.image.unitTest - Package Unit-Test
%     imUtil.image.wmean_sigclip - Calculate the sigma-clipped weighted mean of a dataset
 help imUtil.image.allFunList