% Functions and Classes list for the tools.math.fit package
% Author : autogenerated (Jun 2023)
%      tools.math.fit.allFunList - Functions and Classes list for the tools.math.fit package
%      tools.math.fit.fmincon_my - ------------------------------------------------------------------------------
% tools.math.fit.fminsearch_chi2 - ------------------------------------------------------------------------------
%   tools.math.fit.fminsearch_my - ------------------------------------------------------------------------------
%      tools.math.fit.fminunc_my - fminunc.m version in which it is possible to pass additional parameters to the function
%    tools.math.fit.ransacLinear - Fit a linear model Y=a+bX using RANSAC
%  tools.math.fit.ransacLinear2d - RANSAC fitting of 2D data to a 2D linear function
% tools.math.fit.ransacLinearModel - Fit a general linear model using a simplified RANSAC-like scheme
 help tools.math.fit.allFunList