% Functions and Classes list for the tools.math.fit package
% Author : autogenerated (May 2022)
%      tools.math.fit.fmincon_my - ------------------------------------------------------------------------------
% tools.math.fit.fminsearch_chi2 - ------------------------------------------------------------------------------
%   tools.math.fit.fminsearch_my - ------------------------------------------------------------------------------
%      tools.math.fit.fminunc_my - ------------------------------------------------------------------------------
%    tools.math.fit.ransacLinear - Fit a linear model Y=a+bX using RANSAC
%  tools.math.fit.ransacLinear2d - RANSAC fitting of 2D data to a 2D linear function
 help tools.math.fit.allFunList