% Functions and Classes list for the timeSeries package
% Author : autogenerated (Jun 2023)
%          timeSeries.allFunList - Functions and Classes list for the timeSeries package
%     timeSeries.arma.allFunList - Functions and Classes list for the timeSeries.arma package
%      timeSeries.bin.allFunList - Functions and Classes list for the timeSeries.bin package
%         timeSeries.bin.binning - Binning function. Calculate various functions in data bins.
%     timeSeries.bin.binningFast - Bin [X,Y] data and apply functions to Y values in each bin defined by X
% timeSeries.bin.binning_adaptive - Construct list of edges for binning, given some bin size criteria
%     timeSeries.bin.binning_npt - Binning a time series by equal number of sucssesive points
%     timeSeries.bin.binning_old - The old version of the binning function. Use binning instead.
%  timeSeries.detrend.allFunList - Functions and Classes list for the timeSeries.detrend package
%    timeSeries.detrend.polysubs - Fit and subtract polynomials from a time series [T,Y].
%     timeSeries.detrend.runmean - Running mean of un-evenly spaced time series
%    timeSeries.detrend.runmean1 - Running mean on equally spaced 1-D vector
% timeSeries.detrend.sgolayInterp - Savitzky-Golay filter and interpolation for non equally spaced data.
% timeSeries.detrend.subtract_back1d - Subtract background level from a 1-D vector.
%      timeSeries.detrend.sysrem - Apply the Tamuz et al. sysrem decomposition to a matrix of residuals
%      timeSeries.fit.allFunList - Functions and Classes list for the timeSeries.fit package
%       timeSeries.fit.fitPeriod - fit a light curve with an harmonic (sin/cos) series
%      timeSeries.fit.fitPolyHyp - Hypothesis testing between fitting polynomials of various degrees to
%     timeSeries.fold.allFunList - Functions and Classes list for the timeSeries.fold package
%  timeSeries.fold.extract_phase - Extract observations take at some phase range
%        timeSeries.fold.folding - Folding a time series by some period
% timeSeries.fold.folding_solarsys - Folding a time series for a solar system object
%   timeSeries.interp.allFunList - Functions and Classes list for the timeSeries.interp package
%     timeSeries.interp.interpGP - Interpolate a time series using Gaussian processes
% timeSeries.interp.resample_uniform - Uniform resampling of a non-evenly spaced time series.
%    timeSeries.interp.sf_interp - Interpolate a time-series using the structure-function-weighted method
%   timeSeries.obsolete.Contents - 
% timeSeries.obsolete.allFunList - Functions and Classes list for the timeSeries.obsolete package
%        timeSeries.obsolete.arp - Fit autoregression model for evently spaced time series. OBSOLETE - use builtin tools
% timeSeries.obsolete.binFullOverlap - Bin light curve with finite ExpTime using only points fully covering
% timeSeries.obsolete.bin_by_eye - Bin data by define bins interactively. OBSOLETE - need to rewrite
% timeSeries.obsolete.calib_flux_lsq - Best fit zeropoints and mean magnitudes to a matrix of magnitudes.
% timeSeries.obsolete.calib_flux_sum - Normalize (calibrate) a matrix of fluxes using sum of flux in each epoch.
%    timeSeries.obsolete.cosbell - Cosine bell function (Obsolete: use timeseries.taper instead)
% timeSeries.obsolete.fitPolyFiniteExpTime - 
% timeSeries.obsolete.fit_polys_deltachi2 - Fit polynomials of various orders to a time series and calculate chi^2
%      timeSeries.obsolete.fmaxs - Find local maxima by diffrentiation
% timeSeries.obsolete.foldingStat - 
%     timeSeries.obsolete.glsper - Calculates The generalized Lomb-Scargle periodogram (Zechmeister 2009).
% timeSeries.obsolete.matched_filter - Matched filter for 1-D time series
% timeSeries.obsolete.mean_plweighted - Power-law weighted mean of a time series.
% timeSeries.obsolete.period_proper - SHORT DESCRIPTION HERE
% timeSeries.obsolete.phot_event_me - --------------------------------------------------------------------
% timeSeries.obsolete.plot_inspect_lc - plot and inspect light curve and power spectrum
% timeSeries.obsolete.plot_period_folder - ------------------------------------------------------------------------------
% timeSeries.obsolete.ps_whitening - --------------------------------------------------------------------------
% timeSeries.obsolete.removeFluxBeforeT0 - Given a LC, remove baseline flux, and any flux detected before t0.
% timeSeries.obsolete.rmsflux_select - Select points in an flux/mag vs. rms like diagram
% timeSeries.obsolete.simulated_elc - Simulated photons light curve
%    timeSeries.obsolete.specwin - Power spectrum window (use timeseries.period instead)
%      timeSeries.obsolete.taper - Generate a taper function
%   timeSeries.obsolete.unitTest - Package Unit-Test
%   timeSeries.period.allFunList - Functions and Classes list for the timeSeries.period package
%       timeSeries.period.minclp - ------------------------------------------------------------------------------
%          timeSeries.period.pdm - Periodicity search using period dispersion minimization
%     timeSeries.period.pdm_phot - --------------------------------------------------------------------
%       timeSeries.period.period - Periodicity search in a non-equally spaced time series
% timeSeries.period.period_complex - Fourier transform of non equally spaced time series
% timeSeries.period.period_consistent - SHORT DESCRIPTION HERE
% timeSeries.period.period_entropy - Periodogram using information entropy
% timeSeries.period.period_events - -----------------------------------------------------------------------------
%   timeSeries.period.period_fft - Power spectrum of evenly spaced time series using fft
% timeSeries.period.period_fitfourier - Fit a Fourier series to a time series
%    timeSeries.period.period_mi - SHORT DESCRIPTION HERE
% timeSeries.period.period_min_curve_length - Periodicity search using minimum curve length
%  timeSeries.period.period_norm - Normalized power spectrum of non equally spaced time series
% timeSeries.period.period_norm_bootstrap - Run bootstrap normal pertiodogram on a light curve.
% timeSeries.period.period_norm_order2 - 2nd order harmonic power spectrum of non evenly spaced time series
% timeSeries.period.period_norm_solarsys - Normalized power spectrum for a Solar System object
% timeSeries.period.period_normnl - Normzlied power spectrum using no loops (may be faster in some cases)
%    timeSeries.period.period_np - SHORT DESCRIPTION HERE
%   timeSeries.period.period_pdm - SHORT DESCRIPTION HERE
%  timeSeries.period.period_plot - SHORT DESCRIPTION HERE
% timeSeries.period.period_scargle - Scargle power spectrum of non equally spaced time series
% timeSeries.period.period_scarglenl - Scargle power spectrum of non equally spaced time series / no loops
%     timeSeries.period.periodia - Classical power spectrum of non-evenly space time series (OBSOLETE)
%     timeSeries.period.periodis - Scargle periodogram. OBSOLETE: Use period.m instead.
%     timeSeries.period.periodit - Calculate the periodogram as a function of time (will be removed)
% timeSeries.period.periodmulti_norm - Simultanous power spectrum of time series with common times
%     timeSeries.rand.allFunList - Functions and Classes list for the timeSeries.rand package
% timeSeries.rand.random_time_sequence - Generate random times for an astronomical time series.
%     timeSeries.stat.allFunList - Functions and Classes list for the timeSeries.stat package
%       timeSeries.stat.stdfilt1 - Standart deviation filter
% timeSeries.stat.vonNeumannStat - Calculate the unbiased von Neumann statistics for a time series.
%     timeSeries.time.allFunList - Functions and Classes list for the timeSeries.time package
%            timeSeries.time.hjd - JD to heliocentric JD
%     timeSeries.timeDelay.A_hat - A_hat operator (Springer & Ofek 2021b)
% timeSeries.timeDelay.allFunList - Functions and Classes list for the timeSeries.timeDelay package
%   timeSeries.timeDelay.chi2_xF - Return the \chi^2 for fitting astrometric time delay in the time domain
% timeSeries.timeDelay.combined_Ft - Reconstruct the combined light curve from the original light curve
%   timeSeries.timeDelay.content - Content of the +TimeDelay package:
% timeSeries.timeDelay.dft_matrix - Return the discrete Fourier Transform matrix
% timeSeries.timeDelay.end_matching - Apply end-matching to a light curve such that first and last point have the same flux.
% timeSeries.timeDelay.end_matching_xt - Apply end-matching to a center-of-light position consistent with light curve
% timeSeries.timeDelay.equal_diagonals_matrix - Populate a vector along the diagonals of a matrix (Toplitz matrix)
%  timeSeries.timeDelay.fft_freq - Return the frequencies off fft with N points and Delta time step D.
% timeSeries.timeDelay.fit_astrometric_flux - Fit the 2 images astrometric-flux time delay model to observations
% timeSeries.timeDelay.fit_astrometric_flux_UnevenlySpaced - 
% timeSeries.timeDelay.fit_astrometric_flux_simple - Fit 2-D lensed images using the simple flux/astrometry method (no red noise)
%  timeSeries.timeDelay.fit_flux - Fit the 2 images time delay using the flux-only method
% timeSeries.timeDelay.fit_fluxBPL - Fit the power spectrum with broken power-law model
% timeSeries.timeDelay.fit_fluxBPL_TD - 
%    timeSeries.timeDelay.logdet - Calculate the log of the determinant of a matrix
%  timeSeries.timeDelay.logl_BPL - Calculate the log-likelihood for a broken power-law model
%    timeSeries.timeDelay.logl_F - Calculate the log-likelihood of F, Sigma_F, and Sigma_phi (flux only method)
%   timeSeries.timeDelay.logl_xF - Return the -logL of x,F - of the astrometric-flux time-delay method
% timeSeries.timeDelay.logl_x_given_F - Return the -logL of x | F - of the astrometric-flux time-delay method
% timeSeries.timeDelay.plots_for_paperI - Input  : - plot options:
% timeSeries.timeDelay.plots_for_paperII - PLot options:
% timeSeries.timeDelay.power_spectrum_sections - Calculate the power spectrum of unevenly spaced time series with gaps
% timeSeries.timeDelay.rand_lensed - Generate evenly spaced combined ligt curve and position of lensed quasar
% timeSeries.timeDelay.rand_lensed_uneq - unequally spaced lensed quasar light curves and center of light position
%  timeSeries.timeDelay.rand_psd - Generate a random vector with distribution following some power spectrum.
% timeSeries.timeDelay.reconstruct_ft - Reconstruct f(t) of a lensed quasar from the combined light and position
% timeSeries.timeDelay.sigma_phi - Calculate Sigma_phi and Sigma_F
% timeSeries.timeDelay.split2sections - Split a time series to sections in which the gaps have a maximum.
% timeSeries.timeDelay.witt_timedelay_formula - Calculate the time delay for isothermal elliptical potential (Witt formula)
%    timeSeries.xcorr.allFunList - Functions and Classes list for the timeSeries.xcorr package
%           timeSeries.xcorr.ccf - ------------------------------------------------------------------------------
%          timeSeries.xcorr.ccf1 - --------------------------------------------------------------------------
%       timeSeries.xcorr.ccf_fft - Cross correlation function of evenly spaced data using fft
%       timeSeries.xcorr.ccf_old - Cross coorelation between two equally spaced series
%           timeSeries.xcorr.dcf - --------------------------------------------------------------------------
%          timeSeries.xcorr.dcf1 - --------------------------------------------------------------------------
%         timeSeries.xcorr.xcorr - Calculate the \chi2 and cross correlation between two time series.
 help timeSeries.allFunList