% Functions and Classes list for the imUtil.spec.lines package
% Author : autogenerated (Jan 2025)
% imUtil.spec.lines.xcorrLineWidth - Correlation coef. between data and template when the template is convolved with a filter
 help imUtil.spec.lines.allFunList