% Functions and Classes list for the imProc.calib package
% Author : autogenerated (Jan 2025)
%        imProc.calib.allFunList - Functions and Classes list for the imProc.calib package
%  imProc.calib.equaliseLineMean - equalise an image by compensating, line by line, the average of the line
% imProc.calib.fluxAnnulusBack_bias - Estimate and correct the flux-annulus-background bias.
%       imProc.calib.gainCorrect - Divide image by gain and update header.
% imProc.calib.nonlinearityCorrection - Apply a flux non-linearity correction to an AstroImage object.
%     imProc.calib.photometricZP - Calculate an absolute photometric calibration to AstroCatalog
% imProc.calib.selectMainSequenceFromGAIA - Select main sequence stars from GAIA catalog in AstroCatalog object.
%          imProc.calib.unitTest - unitTest for imProc.calib
%       imProc.calib.CalibImages - CalibImages class - A class for storing calibration image, and performs
 help imProc.calib.allFunList