%==========================================================================
% Project     : ULTRASAT SOC
% Filename    : soc_slew_matlab.py
% Author      : Chen Tishler
% Created     : 02/11/2025
% Modified    : 04/11/2025
% Description : MATLAB service to calculate slew time between targets
%==========================================================================

function soc_slew_calc_matlab()
    % SlewCalc App - Main function

    global SOC_PATH;

    % Set LogFile to use monthly log file
	fprintf('soc_slew_calc_matlab started, V1.02 (05/01/2026)\n');
    LF = LogFile.getSingleton('FileName', 'soc_slew_calc_matlab', ...
        'SubFolder', 'slew_calc/matlab', ...
        'UseMonthPrefix', true);
           
    % Link MsgLogger to the LogFile object
    ML = MsgLogger.getSingleton();
    ML.LogF = LF;
    io.msgLog(LogLevel.Info, 'soc_slew_matlab started');    

    % Print some info
    fprintf('getPid: %d\n', tools.os.getPid());
    fprintf('getProcessName: %s\n', tools.os.getProcessName());
    fprintf('getCmdLine: %s\n', tools.os.getCmdLine());

    % Check if deployed (i.e. running as EXE file, generated by mcc, see _build.bat)
    if isdeployed
        fprintf('soc_slew_matlab: isdeployed = TRUE\n');
        locate_externapp = which(fullfile('soc_slew_matlab.exe'));
        fprintf('which: %s\n', locate_externapp);
    end    
    
    if ismcc
        fprintf('soc_slew_matlab: ismcc = TRUE\n');
    end           

    % Set SOC_PATH and load FileMap when deployed (reusable bootstrap)
    % ultrasat.services.runDeployedBootstrap('slew/slew_matlab/AstroPackFileMap_1.mat');


    fprintf('soc_slew_matlab done\n');
end

%==========================================================================

function setup()

end

%==========================================================================

function mainLoop()
    % mainLoop - Blocking function
    global SOC_PATH;

    % Set the log level
    MsgLogger.setLogLevel(LogLevel.Info, 'type', 'file');
    MsgLogger.setLogLevel(LogLevel.Info, 'type', 'disp');            

    % Set the input path
    InputPath = fullfile(SOC_PATH, 'runtime', 'exchange', 'slew_calc', 'input');
    ProcessedPath = fullfile(SOC_PATH, 'runtime', 'exchange', 'slew_calc', 'processed');    

    % Log the start of the main loop
    io.msgLog(LogLevel.Info, '=========== Slew mainLoop started - Input folder: %s', strrep(InputPath, '\', '\\'));

    % Create the FileProcessor object
    fp = FileProcessor('InputPath', InputPath, 'InputMask', '*.json', 'ProcessedPath', ProcessedPath);
    fp.ProcessFileFunc = @fileProcessorCallback;
    fp.EnableDelete = true;
    fp.WatchdogFileName = 'soc_slew_matlab_watchdog.txt';
    fp.WatchdogInterval = 10;
    %fp.MaxRunTime = hours(8);

    % Input loop will call FileProcessorCallback (below) for each input
    % file found in the folder
    % Note: Blocking function
    fp.process('DelaySec', 0.1);
    
    io.msgStyle(LogLevel.Test, '@passed', 'Slew mainLoop passed');                          
    Result = true;
end
