% Functions and Classes list for the tools.git package
% Author : autogenerated (Jan 2025)
%           tools.git.getVersion - Return a string with the branch, tag and commit number for AstroPack git
 help tools.git.allFunList