% Functions and Classes list for the celestial.healpix package
% Author : autogenerated (Jan 2025)
%      celestial.healpix.ang2pix - Convert lon/lat to the index of the nearest healpix pixel.
%   celestial.healpix.coneSearch - cone search for healpix pixels (fast version).
% celestial.healpix.coneSearchRecur - cone search for healpix pixels (recursive search version).
%     celestial.healpix.isInside - Check if a given point (Lon, Lat) is inside a specified HEALPix pixel
% celestial.healpix.latitudeRings - Return a vector of the latitudes of healpix rings, and the number of pixels in each ring.
%         celestial.healpix.nPix - Return the number of pixels in healpix given its Nside.
%        celestial.healpix.nRing - Number of rings in healpix
%     celestial.healpix.nest2xyf - Converted nested pixel index into Face index and X/Y local coordinates in face.
%      celestial.healpix.pix2ang - Return the lon/lat of the centers of the healpix pixels given their index.
% celestial.healpix.pix2uniqueId - Return healpix unique Id from Nside and pixel index.
% celestial.healpix.pixBoundries - Return healpix pixel boundries corners.
%    celestial.healpix.pixRadius - Return the healpix diameter, given its NSide.
% celestial.healpix.pixelSons_nested - Given a nested pixel index, returns the 4 pixels in the next Nside level.
% celestial.healpix.uniqueId2pix - Convert healpix unique Id to Nside and pixel index.
%     celestial.healpix.unitTest - unitTest for celestial.healpix
%     celestial.healpix.xyf2nest - 
 help celestial.healpix.allFunList