% Functions and Classes list for the astro.lensing package
% Author : autogenerated (May 2022)
%  astro.lensing.alpha_kspl_fast - Deflection for softened power law elliptical density
%        astro.lensing.alpha_sis - Gravitational deflection for softend spherical isothermal sphere
%        astro.lensing.alpha_spl - Gravitational deflection of softened power law elliptical potential
%    astro.lensing.beta_minimize - -----------------------------------------------------------------------------
%       astro.lensing.calc_alpha - 1;2cfunction [AlphaX,AlphaY,A_11,A_22,A_12,Phi,Kappa]=calc_alpha(ThetaX,ThetaY,Pars,ModelType);
% astro.lensing.calc_magnification - Magnification from mapping matrix
%        astro.lensing.dls_ds_2z - Given D_ls/D_s ratio, z_l and cosmological parameters, solve for z_s.
% astro.lensing.find_images_regions - -----------------------------------------------------------------------------
% astro.lensing.fit_astrometric_timedelay - SHORT DESCRIPTION HERE
% astro.lensing.generate_timedelay_lc - Generate random power-law power spectrum light curve and its time delays.
% astro.lensing.integrand_jn_ellkappa - -----------------------------------------------------------------------------
%       astro.lensing.iplane_rms - --------------------------------------------------------------------------
%  astro.lensing.iplane_rms_norm - --------------------------------------------------------------------------
% astro.lensing.iplane_rms_smart - --------------------------------------------------------------------------
% astro.lensing.kappa_from_alpha - -----------------------------------------------------------------------------
% astro.lensing.lensmodel_solvenorm - ---------------------------------------------------------------------------
%   astro.lensing.plot_lens_data - -------------------------------------------------------------------------
%   astro.lensing.predict_images - ----------------------------------------------------------------------
%      astro.lensing.s1plane_rms - --------------------------------------------------------------------------
%       astro.lensing.splane_rms - --------------------------------------------------------------------------
%     astro.lensing.splane_rms_n - --------------------------------------------------------------------------
%  astro.lensing.splane_rms_norm - --------------------------------------------------------------------------
% astro.lensing.splane_rms_norm1 - --------------------------------------------------------------------------
%         astro.lensing.unitTest - Package Unit-Test
%        astro.lensing.upsilon_u - -----------------------------------------------------------------------------
 help astro.lensing.allFunList