% Functions and Classes list for the io.fits package
% Author : autogenerated (May 2022)
%        io.fits.dataType2bitpix - Convert class name to BITPIX keyword value number.
%          io.fits.defaultHeader - Generate a default (minimal) FITS header
%   io.fits.generateHeaderBlocks - Given a 3 column cell array of an header, create a string containing
%         io.fits.writeImageData - Write FITS image data matrix to an open file
%        io.fits.writeSimpleFITS - Write a simple (single HDU) FITS file to disk
 help io.fits.allFunList