DROP TABLE IF EXISTS newtable_3;
CREATE TABLE newtable_3 (
RecID VARCHAR NOT NULL,
FDouble1 DOUBLE PRECISION DEFAULT 0,
FInt1 INTEGER DEFAULT 0,
FString1 VARCHAR,
CONSTRAINT newtable3_pkey PRIMARY KEY(RecID));
