% Functions and Classes list for the tools.find package
% Author : autogenerated (Jun 2023)
%          tools.find.allFunList - Functions and Classes list for the tools.find package
%            tools.find.bin_sear - Binary search for a value in a sorted vector.
%           tools.find.bin_sear2 - --------------------------------------------------------------------------
%           tools.find.bin_sear3 - --------------------------------------------------------------------------
% tools.find.find_local_extremum - Use stirling interpolation to find local extremum in vector.
%    tools.find.find_local_zeros - -----------------------------------------------------------------------------
%           tools.find.find_peak - ------------------------------------------------------------------------------
%    tools.find.find_peak_center - --------------------------------------------------------------------------
%       tools.find.fun_binsearch - --------------------------------------------------------------------------
%        tools.find.groupCounter - Group a vector of counters into successive numbers.
%           tools.find.mfind_bin - Binary search on a sorted vector running simolutnously on multiple values.
%            tools.find.unitTest - Package Unit-Test
 help tools.find.allFunList