% Functions and Classes list for the tools.find package
% Author : autogenerated (Jan 2025)
%          tools.find.allFunList - Functions and Classes list for the tools.find package
%            tools.find.bin_sear - Binary search for a value in a sorted vector.
%           tools.find.bin_sear2 - --------------------------------------------------------------------------
%           tools.find.bin_sear3 - --------------------------------------------------------------------------
%        tools.find.binarySearch - call the Avi Ziskind binarySearch function, but clean all the NaNs prior to the operation
% tools.find.findGroupOfConsecutiveVals - in vector A find Mth group of N consecutive values of Val
% tools.find.findListsOfConsecutiveTrue - Given a vector of logicals, return a cell array of all lists of consecutive true
% tools.find.find_local_extremum - Use stirling interpolation to find local extremum in vector.
%    tools.find.find_local_zeros - -----------------------------------------------------------------------------
%           tools.find.find_peak - ------------------------------------------------------------------------------
%    tools.find.find_peak_center - --------------------------------------------------------------------------
%       tools.find.fun_binsearch - --------------------------------------------------------------------------
%        tools.find.groupCounter - Group a vector of counters into successive numbers.
%           tools.find.mfind_bin - Binary search on a sorted vector running simolutnously on multiple values.
%            tools.find.unitTest - unitTest for package: tools.find
%       tools.find.mex.findEqual - Find values in an array (fast mex version of find)
% tools.find.mex.findLargerFirst - Find the index of the first element in an array which is larger then some value (fast mex).
% tools.find.mex.findSmallerFirst - Find the index of the first element in an array which is smaller then some value (fast mex).
 help tools.find.allFunList