%==========================================================================
% Project     : ULTRASAT SOC
% Filename    : soc_slew_matlab.py
% Author      : Chen Tishler
% Created     : 02/11/2025
% Modified    : 04/11/2025
% Description : MATLAB service to calculate slew time between targets
%==========================================================================

function soc_slew_calc_matlab()
    % SlewCalc App - Main function

    global SOC_PATH;

    % Set LogFile to use monthly log file
	fprintf('soc_slew_calc_matlab started, V1.02 (05/01/2026)\n');
    LF = LogFile.getSingleton('FileName', 'soc_slew_calc_matlab', ...
        'SubFolder', 'slew_calc/matlab', ...
        'UseMonthPrefix', true);
           
    % Link MsgLogger to the LogFile object
    ML = MsgLogger.getSingleton();
    ML.LogF = LF;
    io.msgLog(LogLevel.Info, 'soc_slew_matlab started');    

    % Print some info
    fprintf('getPid: %d\n', tools.os.getPid());
    fprintf('getProcessName: %s\n', tools.os.getProcessName());
    fprintf('getCmdLine: %s\n', tools.os.getCmdLine());

    % Check if deployed (i.e. running as EXE file, generated by mcc, see _build.bat)
    if isdeployed
        fprintf('soc_slew_matlab: isdeployed = TRUE\n');
        locate_externapp = which(fullfile('soc_slew_matlab.exe'));
        fprintf('which: %s\n', locate_externapp);
    end    
    
    if ismcc
        fprintf('soc_slew_matlab: ismcc = TRUE\n');
    end           

    % Set SOC_PATH and load FileMap when deployed (reusable bootstrap)
    ultrasat.services.runDeployedBootstrap('slew/slew_matlab/AstroPackFileMap_1.mat');

    % Create component to trigger Config loading
    fprintf('Creating Comp\n');
    Comp = Component();
    fprintf('Config.Path: %s\n', Comp.Config.Path);
    fprintf('Comp.Config.Data.MsgLogger.FileName: %s\n', Comp.Config.Data.MsgLogger.FileName);

    % Call UltrasatPerf() to force the mcc compiler linking this class and
    % its related sources. Otherwise we will get this error:
    %     09:50:58.133 [DBG] doProcessSnr: creating UltrasatPerf2GUI
    %     09:50:58.176 [DBG] UltrasatPerf2GUI: UltrasatPerf2GUI:load: c:\soc\snr\snr_matlab\P90_UP_test_60_ZP_Var_Cern_21.mat
    %     Warning: Variable 'UP' originally saved as a UltrasatPerf cannot be instantiated as an object and will be read in as a uint32.    
    fprintf('Calling: Perf = UltrasatPerf(Init, false);\n');    
    Perf = UltrasatPerf('Init', false);
    fprintf('UltrasatPerf done\n');
    
    fprintf('Calling JsonFileIpc run\n');
    global SOC_PATH;
    InputPath = fullfile(SOC_PATH, 'runtime', 'exchange', 'slew_calc', 'input');
    ProcessedPath = fullfile(SOC_PATH, 'runtime', 'exchange', 'slew_calc', 'processed');
    ipc = ultrasat.services.common.JsonFileIpc( ...
        'InputPath', InputPath, ...
        'ProcessedPath', ProcessedPath, ...
        'Handler', @ultrasat.services.slew_calc.processRequest, ...
        'WatchdogFileName', 'soc_slew_matlab_watchdog.txt', ...
        'WatchdogInterval', 10, ...
        'DelaySec', 0.1);
    ipc.run();
    fprintf('Returned from JsonFileIpc run\n');

    fprintf('soc_slew_matlab done\n');
end
