% Functions and Classes list for the telescope.sn package
% Author : autogenerated (Jun 2023)
%        telescope.sn.allFunList - Functions and Classes list for the telescope.sn package
%         telescope.sn.back_comp - Get spectra of background components
% telescope.sn.optimal_phot_aperture - Optimal aperture radius for aperture photometry of a Gaussian PSF.
%           telescope.sn.sn_calc - A signal-to-noise calculator for astronomical telescopes.
%     telescope.sn.sn_det2signal - Convert detection S/N of a Gaussian PSF to signal
%        telescope.sn.sn_det_psf - Calculate S/N for detection of a Gaussian PSF
%    telescope.sn.sn_phot2signal - Convert photometry S/N of a Gaussian source to signal
%      telescope.sn.sn_phot_aper - Calculate the aperture photometry S/N for a Gaussain source
%       telescope.sn.sn_phot_psf - Calculate photometry S/N of a Gaussian PSF
%      telescope.sn.sn_phot_psfn - Calculate photometry S/N of a numerical PSF
%           telescope.sn.sn_spec - S/N calculator for long-slit spectra
%               telescope.sn.snr - Signal-to-Noise ratio calculator using full spectral components.
%          telescope.sn.snr_chen - 
%      telescope.sn.spec2photons - Spectrum to photon counts in band.
%          telescope.sn.unitTest - telescope.sn Unit-Test
% telescope.sn.volumetric_rate_sn - SHORT DESCRIPTION HERE
 help telescope.sn.allFunList