% Functions and Classes list for the astro.extinction package
% Author : autogenerated (Jan 2025)
%    astro.extinction.extinction - Given the E_{B-V} and the wavelength or filter name calculate the extinction in magnitudes
% astro.extinction.extinctionGrid - Make a grid of extinction (A_lam) values for a given sky grid and filter (or frequency)
%       astro.extinction.sky_ebv - Get Galactic extinction for a list of coordinates
 help astro.extinction.allFunList