% Functions and Classes list for the tools.math.stat package
% Author : autogenerated (Jan 2025)
%       tools.math.stat.Contents - 
%     tools.math.stat.allFunList - Functions and Classes list for the tools.math.stat package
%           tools.math.stat.bc_a - ------------------------------------------------------------------------------
%       tools.math.stat.bin2dFun - 2-D binning and apply functions to bins
%  tools.math.stat.bootstrap_std - --------------------------------------------------------------------------
%    tools.math.stat.cel_coo_rnd - ------------------------------------------------------------------------------
%    tools.math.stat.cell2d_stat - Given [X,Y,Val], calculate statistics of Val's in X/Y bins
%      tools.math.stat.cell_stat - ----------------------------------------------------------------------------
%   tools.math.stat.centermass2d - ------------------------------------------------------------------------------
% tools.math.stat.confint_probdist - ------------------------------------------------------------------------------
%        tools.math.stat.corrsim - Correlation between two vectors and confidence region using bootstrap
%    tools.math.stat.corrsim_cov - Correlation matrix between N columns and bootstrap estimation of errors.
%       tools.math.stat.distCorr - Calculate the distance correaltaion and covariance (independeny test)
%         tools.math.stat.err_cl - Numerical estimate of percentiles.
% tools.math.stat.error2ensemble - --------------------------------------------------------------------------
%     tools.math.stat.fab_counts - -------------------------------------------------------------------------
%         tools.math.stat.hist2d - calculate the 2-D histogram of 2-D data set.
%        tools.math.stat.iqrFast - A fast iqr (inter quantile range) function (without interpolation)
%      tools.math.stat.jackknife - Given an estimator, calculate the Jacknife StD.
%       tools.math.stat.lognlogs - ---------------------------------------------------------------------------
% tools.math.stat.max_likelihood - Likelihood from observations and numerical probability distribution.
%          tools.math.stat.maxnd - ------------------------------------------------------------------------------
%     tools.math.stat.mean_error - Calculate the error on the mean using std/sqrt(N).
%         tools.math.stat.meannd - ------------------------------------------------------------------------------
%   tools.math.stat.medianSparse - Calculate the median of an array using only a sub-sample of the points.
%       tools.math.stat.mediannd - ------------------------------------------------------------------------------
%          tools.math.stat.minnd - ------------------------------------------------------------------------------
%       tools.math.stat.mode_bin - --------------------------------------------------------------------------
%   tools.math.stat.mode_density - Calculate the mode by estimating the density of points
%       tools.math.stat.mode_fit - Estimate the mode of an array by fitting a Gaussian to its histogram.
%       tools.math.stat.mode_vec - Mode and variance of a distribution
%      tools.math.stat.moment_2d - ------------------------------------------------------------------------------
%    tools.math.stat.mutual_info - Calculate the mutual information of two vectors (degree of independency)
%        tools.math.stat.nanmean - faster version of nanmean using the 'omitnan' option.
%      tools.math.stat.nanmedian - faster version of nanmedian using the 'omitnan' option.
%        tools.math.stat.nanrstd - Robust nanstd.
%         tools.math.stat.nanstd - faster version of nanstd using the 'omitnan' option.
%         tools.math.stat.noiser - --------------------------------------------------------------------------
%      tools.math.stat.poissconf - Upper/lower confidence intervals on N events assuming Poisson statistics
%  tools.math.stat.prob2find_inr - ------------------------------------------------------------------------------
%         tools.math.stat.psigma - --------------------------------------------------------------------------
%   tools.math.stat.quantileFast - A fast quantile function (without interpolation)
%    tools.math.stat.rand_circle - ------------------------------------------------------------------------------
%        tools.math.stat.rand_ps - Generate a random time series with a given power spectrum.
%     tools.math.stat.rand_range - --------------------------------------------------------------------------
%        tools.math.stat.randgen - Random numbers generator for arbitrary  distribution.
%  tools.math.stat.randinpolygon - Generate random positions inside a polygon
%        tools.math.stat.rangend - ------------------------------------------------------------------------------
%       tools.math.stat.realhist - Calculate histogram for a dataset in a given range.
%          tools.math.stat.rmean - Calculate the rubust mean over one of the dimensions.
%           tools.math.stat.rstd - Robust std calculated from the 50  inner percentile of the data.
%    tools.math.stat.sphere_conv - --------------------------------------------------------------------------
%    tools.math.stat.stat_in_htm - SHORT DESCRIPTION HERE
%     tools.math.stat.stdBias_c4 - Return the c4 bias in the expecteny value of the std due to finte sample size
%        tools.math.stat.std_mad - Std using the mean absolute deviation (mad) function
%   tools.math.stat.std_outlier1 - Std with a single outlier removal if found outside the expected range.
%          tools.math.stat.std_w - --------------------------------------------------------------------------
%          tools.math.stat.stdnd - Return the global StD of a N-D matrix.
%          tools.math.stat.sumnd - ------------------------------------------------------------------------------
%       tools.math.stat.unitTest - unitTest for tools.math.stat package
%          tools.math.stat.wmean - Calculate the weighted mean of a sample.
%        tools.math.stat.wmedian - Weighted median for a vector.
%     tools.math.stat.wmedian_im - --------------------------------------------------------------------------
% tools.math.stat.mex.meanStdSum_2Dcols_IgnoreNaN - Calculate mean std, and sum of a 2D matrix, over first dimensions ignoring NaNs (fast mex).
% tools.math.stat.mex.meanStdSum_AllDim_IgnoreNaN - Calculate mean std, and sum of an array, over all dimensions, ignoring NaNs (fast mex).
%    tools.math.stat.mex.median1 - Fast median of a vector without ignoring NaNs, using mex.
%     tools.math.stat.mex.minmax - Calculate the min and max of an array of any dimension in one pass (fast mex)
% tools.math.stat.mex.squeezeStdCube_Dim12 - Fast mex for squeeze(mean(A,[1 2],'omitnan')) and squeeze(std(A,0,[1 2],'omitnan'))
 help tools.math.stat.allFunList