% Functions and Classes list for the db.util package
% Author : autogenerated (Jan 2025)
% db.util.insertHealpixIndex2table - Use RA, Dec to add healpix indices to table
% db.util.insertIntegerTime2table - Insert time or creation time in integer format to table or vector.
%            db.util.prepRecords - convert a stack of AI/AH/AC into a struct of DB records for bulk injection
%   db.util.read_xls2tableFormat - Read xls file containing DB table definitions and prepare structre
 help db.util.allFunList