function prep_data_dir(varargin)
% Prepare interface functions for the catalogs in the data directory
% Package: VO.search
% Description: Prepare interface functions for the catalogs in the data directory
% Input  : * Arbitrary number of pairs if ...,keyword,value,...
%            The possible keywords are possible:
%            'Dir' - Directory in which the data catalogs resides.
%                    The directory tree should be stored like a package.
%                    each directory start with "+".
%                    Default is '~/matlab/data/+datacats/';
%            'Exten' - Cell array of file extensions to map.
%                    Default is {'mat'}.
% Output : null
% License: GNU general public license version 3
%     By : Eran O. Ofek                    Feb 2017
%    URL : http://weizmann.ac.il/home/eofek/matlab/
% Example: VO.search.prep_data_dir
% Reliable: 2
%--------------------------------------------------------------------------

DefV.Dir             = '~/matlab/data/+cats/';
DefV.Exten           = {'mat','fits'};
InPar = InArg.populate_keyval(DefV,varargin,mfilename);


Next  = numel(InPar.Exten);

% Generated interface functions must not embed the absolute path of the
% machine they were created on - resolve it at call time instead.
DataPath = tools.os.getAstroPackDataPath();

PWD = pwd;

for Iext=1:1:Next
    cd(InPar.Dir);
    List = io.files.rdir(sprintf('*.%s',InPar.Exten{Iext}));

    for If=1:1:numel(List)
        cd(List(If).folder);
        [RelFolder, IsRel] = relative_to_data_path(List(If).folder, DataPath);

        %--- Generate the interface file ---
        ProgName = regexprep(List(If).name,InPar.Exten{Iext},'m');
        FunName  = regexprep(ProgName,'.m','');
        % print status to screen
        fprintf('Generating function %s\n',FunName);
        
        switch lower(InPar.Exten{Iext})
            case 'mat'
                % create and write function
                FID=fopen(ProgName,'w');
                fprintf(FID,'function varargout=%s(varargin)\n',FunName);
                fprintf(FID,'%% Interface function for catalog: %s\n',FunName);
                fprintf(FID,'%% Auto generated by %s\n',mfilename);
                fprintf(FID,'\n');
                fprintf(FID,'Nout = nargout;\n');
                if IsRel
                    fprintf(FID,'[varargout{1:Nout}]=VO.search.catalog_interface(''%s'',fullfile(tools.os.getAstroPackDataPath(),''%s''),varargin{:});\n',List(If).name,RelFolder);
                else
                    fprintf(FID,'[varargout{1:Nout}]=VO.search.catalog_interface(''%s'',''%s'',varargin{:});\n',List(If).name,List(If).folder);
                end
                fclose(FID);
            case 'fits'
                % create and write FITS read function
                FID=fopen(ProgName,'w');
                fprintf(FID,'function varargout=%s(varargin)\n',FunName);
                fprintf(FID,'%% Interface function for FITS file: %s\n',FunName);
                fprintf(FID,'%% Auto generated by %s\n',mfilename);
                fprintf(FID,'\n');
                fprintf(FID,'Nout = nargout;\n');
                if IsRel
                    fprintf(FID,'[varargout{1:Nout}]=FITS.read1(fullfile(tools.os.getAstroPackDataPath(),''%s'',''%s''),varargin{:});\n',RelFolder,List(If).name);
                else
                    fprintf(FID,'[varargout{1:Nout}]=FITS.read1(''%s%s%s'',varargin{:});\n',List(If).folder,filesep,List(If).name);
                end
               
                fclose(FID);
                
            otherwise
                error('Unknown Extension option');
        end
        
    end
end
cd(PWD);

end

function [RelFolder, IsRel] = relative_to_data_path(Folder, DataPath)
    % Express a folder relative to the AstroPack data directory.
    % Input  : - An absolute folder name.
    %          - The AstroPack data directory.
    % Output : - The folder relative to the data directory, or the input
    %            folder unchanged if it is not under it.
    %          - A logical, true if the folder is under the data directory.

    RelFolder = Folder;
    IsRel     = false;
    if isempty(DataPath)
        return
    end
    % compare with forward slashes so that paths written on either platform match
    Folder   = strrep(Folder,'\','/');
    DataPath = regexprep(strrep(DataPath,'\','/'),'/+$','');
    if strncmp(Folder,[DataPath,'/'],numel(DataPath)+1)
        RelFolder = Folder(numel(DataPath)+2:end);
        IsRel     = true;
    end
end
