InstallationLocation : '~/matlab/data'
# The following are cell arrays of entry per dataset
DataName             : 'EarthGravity'
SubDir               : 'SolarSystem/EarthGravity'
URL                  : ['https://euler1.weizmann.ac.il/archive/AstroPack/data/SolarSystem/EarthGravity.tar']
Size                 : 32
SearchFile           : ''
Description          : 'Earth Gravity Models'
