InstallationLocation : '~/matlab/data'
# The following are cell arrays of entry per dataset
DataName             : 'SpecGalQSO'
SubDir               : 'spec/SpecGalQSO'
URL                  : ['https://euler1.weizmann.ac.il/archive/AstroPack/data/spec/SpecGalQSO.tar']
Size                 : 2.7
SearchFile           : ''
Description          : 'Galaxy + Quasar template spectra'
