% Functions and Classes list for the astro.mag package
% Author : autogenerated (Jan 2025)
%           astro.mag.allFunList - Functions and Classes list for the astro.mag package
%              astro.mag.magVega - Return the Vega magnitude adopted by GAIA (0.023\pm0.008)
% astro.mag.meanPhotonWeightedFlux - Calculate the mean flux (photon-weighted) multiplied by the response.
%       astro.mag.photonIntegral - Calculate the number of photons from a spectrum given transmission.
%           astro.mag.spec2ABmag - Convert spectrum + transmission to AB magnitude
%             astro.mag.specVega - Return the Vega (Alpha Lyr) standar spectrum for Vega mag calculations
%            astro.mag.survey_ZP - return zero points of different surveys
%               astro.mag.synMag - Calculate the synthetic magnitude of a spectrum and transmission
%  astro.mag.transmissionEffWave - Calculate the effective wavelength of a transmission function
% astro.mag.transmissionMeanWave - Calculate the mean wavelength of a transmission function
% astro.mag.transmissionPivotWave - Calculate the Pivot wavelength of a transmission function
%             astro.mag.unitTest - Package Unit-Test
 help astro.mag.allFunList