% Functions and Classes list for the celestial.coo package
% Author : autogenerated (Jan 2025)
%  celestial.coo.test_aberration - Unit tests for the aberration function, which calculates the
% celestial.coo.test_area_sphere_polygon - Unit tests for the area_sphere_polygon function, which calculates the area of a polygon on a sphere.
% celestial.coo.test_convert_coo - Unit tests for the celestial.coo.convert_coo function, which converts
%  celestial.coo.test_convertdms - Unit tests for the celestial.coo.convertdms function, which converts
%     celestial.coo.test_coo2box - Unit tests for the celestial.coo.coo2box function, which calculates
% celestial.coo.test_coo_resolver - Unit tests for the celestial.coo.coo_resolver function, which converts
%     celestial.coo.test_cosined - Unit tests for the cosined function, which converts between
% celestial.coo.test_cosined2coo - Unit tests for the cosined2coo function, which converts from
% celestial.coo.test_proper_motion - Unit tests for the proper_motion function, which applies proper motion
% celestial.coo.test_radec2azalt - Unit tests for the radec2azalt function
%  celestial.coo.test_refraction - Unit tests for the refraction function, which estimates atmospheric
% celestial.coo.test_sky_area_above_am - Unit tests for the sky_area_above_am function in AstroPack
% celestial.coo.test_sphere_dist - Unit tests for the sphere_dist function in celestial.coo
% celestial.coo.test_sphere_dist_cosd - Unit tests for the sphere_dist_cosd function in celestial.coo
% celestial.coo.test_sphere_dist_fast - Unit tests for the sphere_dist_fast function
% celestial.coo.test_sphere_dist_fastSmall - Unit tests for the sphere_dist_fastSmall function
% celestial.coo.test_sphere_dist_fastThresh - Unit tests for the sphere_dist_fastThresh function
% celestial.coo.test_sphere_dist_fast_thresh - Unit tests for the sphere_dist_fast_thresh function
% celestial.coo.test_sphere_dist_fast_threshDist - Unit tests for the sphere_dist_fast_threshDist function
% celestial.coo.test_sphere_dist_thresh - Unit tests for the sphere_dist_thresh function, which checks whether points are within
% celestial.coo.test_sphere_move - Unit tests for the sphere_move function, which applies offsets to RA and Dec coordinates.
% celestial.coo.test_sphere_offset - Unit tests for the sphere_offset function, which calculates the offset needed
% celestial.coo.test_spherical_tri_area - Unit tests for the spherical_tri_area function in AstroPack
% celestial.coo.test_spherical_triangle_circum_circle - Unit tests for the spherical_triangle_circum_circle function in AstroPack
 help celestial.coo.allFunList