function Result = unitTest()
    % ImagePath.unitTest        
    

    % This function is not supported any more
    
    if 1==0
         % genPath
         ip = ImagePath();
         [ExpectedPath, ExpectedFileName] = ip.setTestData();
         ip.Level = 'proc';
         ip.SubDir = 'subdir';
         Path = ip.genPath('Time', ip.Time);
         disp(Path);
         %assert(strcmp(Path, ExpectedPath), 'parsed Path and expected Path are different');

         Full = ip.genFile('Time', ip.Time, 'FullPath', true);
         ExpectedFull = [ExpectedPath, ExpectedFileName];
         %assert(strcmp(Full, ExpectedFull), 'parsed FullPath and expected FullPath are different');



        %----------------------------------------------------------------------

        % genFile: Test all parameters         
        FileName1 = ip.genFile(...
                    'ProjName', 'MyProjName', ...
                    'Time', ip.Time, ...
                    'Filter', 'clear', ...
                    'FieldID', '', ...
                    'Counter', 123, ...
                    'CCDID', 456, ...
                    'CropID',789, ...
                    'Type', 'sci', ...
                    'Level', 'proc', ...
                    'SubLevel', '', ...
                    'Product', 'Image', ...
                    'Version', 111, ...
                    'FileType', 'fits', ...
                    'TimeZone', 2, ...
                    'Area', 'MyArea', ...
                    'FullPath', false, ...
                    'FormatFieldID', '%04d', ...
                    'FormatCounter', '%04d', ...
                    'FormatCCDID', '%04d', ...
                    'FormatCropID', '%04d', ...
                    'FormatVersion', '%04d');

        disp(FileName1);
        assert(~strcmp(FileName1, ''));



        % genFile: Test all parameters         
        FileName2 = ip.genFile(...
                    'ProjName', 'MyProjName', ...
                    'Time', ip.Time, ...
                    'Filter', 'clear', ...
                    'FieldID', '', ...
                    'Counter', '0123', ...
                    'CCDID', '0456', ...
                    'CropID', '0789', ...
                    'Type', 'sci', ...
                    'Level', 'proc', ...
                    'SubLevel', '', ...
                    'Product', 'Image', ...
                    'Version', '0111', ...
                    'FileType', 'fits', ...
                    'TimeZone', 2, ...
                    'Area', 'MyArea', ...
                    'FullPath', false, ...
                    'FormatFieldID', '', ...
                    'FormatCounter', '', ...
                    'FormatCCDID', '', ...
                    'FormatCropID', '', ...
                    'FormatVersion', '');

        disp(FileName2);
        assert(~strcmp(FileName2, ''));
        assert(strcmp(FileName1, FileName2));

        %----------------------------------------------------------------------                 

    %     % writeToStruct not implemented yet
    %     IP = ImagePath();
    %     FileName = IP.makeFileName();
    %     assert(~isempty(FileName));
    %     IP.setTestData();
    %     s = IP.writeToStruct();
    %     disp(s);

        %----------------------------------------------------------------------
        testProjName     = {'LAST','USAT','USAT','USAT','USAT','USAT','USAT','USAT','USAT','USAT','USAT','USAT','USAT'};
        testTime         = {'2021-09-09T12:34:56.789'};
        testTimeZone     = {2};
        testFilter       = {'clear'};

        % The input of these fields can both char or numeric    
        % Note: Currently only the first value is used (char), tests should be
        % extended to iterate also numeric values @Dan
        testFieldID      = {'fld', 1};
        testCounter      = {'cnt', 1};
        testCCDID        = {'ccdid', 1};
        testCropID       = {'crop', 1};

        % char only
        testType         = {'sci','sci','sci','sci','domeflat','twflat','bias','dark','skyflat','fringe','sci','sci','sci'};
        testLevel        = {'raw','log','proc','stacked','ref','coadd','calib','calib','calib','calib','proc','proc','proc'};
        testSubLevel     = {'','n','s','sp','d','t','r','m','Fn','Rn','Ln','Gn','Hn','n'};
        testProduct      = {'Image','Back','Var','Image','Exp','Nim','PSF','Cat','Spec','Image','Image','Image','Image'};
        testVersion      = {'1', 1};
        testFileType     = {'fits','hdf5','fits.gz','fits','fits','fits','fits','fits','fits','fits','fits','fits','fits'};
        testSubDir       = {'subdir'};

        testBasePath     = {'/home/last'};
        testDataDir      = {'data'};

        testExpectedPath     = {...
            '/home/last/data/2021/09/09/raw/subdir/',...
            '/home/last/data/2021/09/09/log/subdir/',...
            '/home/last/data/2021/09/09/proc/subdir/',...
            '/home/last/data/2021/09/09/stacked/subdir/',...
            '/home/last/data/ref/1/subdir/',...
            '/home/last/data/coadd/1/subdir/',...
            '/home/last/data/calib/r/subdir/',...
            '/home/last/data/calib/m/subdir/',...
            '/home/last/data/calib/Fn/subdir/',...
            '/home/last/data/calib/Rn/subdir/',...
            '/home/last/data/2021/09/09/proc/subdir/',...
            '/home/last/data/2021/09/09/proc/subdir/',...
            '/home/last/data/2021/09/09/proc/subdir/',...
        };

        testExpectedFileName = {...
            'LAST_20210909.123456.789_clear_fld_cnt_ccdid_crop_sci_raw_Image_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_sci_log.n_Back_1.hdf5',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_sci_proc.s_Var_1.fits.gz',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_sci_stacked.sp_Image_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_domeflat_ref.d_Exp_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_twflat_coadd.t_Nim_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_bias_calib.r_PSF_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_dark_calib.m_Cat_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_skyflat_calib.Fn_Spec_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_fringe_calib.Rn_Image_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_sci_proc.Ln_Image_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_sci_proc.Gn_Image_1.fits',...
            'USAT_20210909.123456.789_clear_fld_cnt_ccdid_crop_sci_proc.Hn_Image_1.fits',...
        };

        % Note that this loop currently iterates only testExpectedPath
        for i=1:length(testExpectedPath)
            ip = ImagePath();

            ip.ProjName        = testProjName{i};
            ip.Time            = testTime{1}; 
            ip.TimeZone        = testTimeZone{1}; 
            ip.Filter          = testFilter{1}; 
            ip.FieldID         = testFieldID{1}; 
            ip.Counter         = testCounter{1}; 
            ip.CCDID           = testCCDID{1}; 
            ip.CropID          = testCropID{1}; 
            ip.Type            = testType{i};           %
            ip.Level           = testLevel{i};          %
            ip.SubLevel        = testSubLevel{i};       %
            ip.Product         = testProduct{i};        %
            ip.Version         = testVersion{1};        %
            ip.FileType        = testFileType{i};       %
            ip.SubDir          = testSubDir{1};        
            ip.BasePath        = testBasePath{1};
            ip.DataDir         = testDataDir{1};

            ExpectedFileName   = testExpectedFileName{i};
            ExpectedPath       = testExpectedPath{i};
            ExpectedFull       = strcat(ExpectedPath, ExpectedFileName);

            FileName = ip.genFile('FullPath', false);
            assert(strcmp(FileName, ExpectedFileName), 'parsed FileName and expected FileName are different: %s -- %s', FileName, ExpectedFileName);

            Path = ip.genPath();
            assert(strcmp(Path, ExpectedPath), 'parsed Path and expected Path are different: %s -- %s', FileName, ExpectedFileName);

            Full = ip.genFile('FullPath', true);
            assert(strcmp(Full, ExpectedFull), 'parsed FullPath and expected FullPath are different: %s -- %s', FileName, ExpectedFileName);
        end
    end
    
    % Done
    %io.msgStyle(LogLevel.Test, '@passed', 'ImagePath test passed')
    
    Result = true;
end

