CREATE TABLE last.diff_src
(
    `id_diff_src` Int64,
    `id_uniq_src` Int64,
    `id_cat_src` Int64,
    `id_ref_im` Int64,
    `id_new_im` Int64,
    `upix_partition` UInt64,
    `upix_low` UInt64,
    `upix_high` UInt64,
    `is_forced` UInt8,
    `score` Float32,
    `s_corr` Float32,
    `s2` Float32,
    `s2_sig` Nullable(Float32),
    `s2_aic` Float32,
    `z2` Float32,
    `z2_sig` Nullable(Float32),
    `z2_aic` Float32,
    `n_sn` Float32,
    `n_flux_psf` Float32,
    `n_psf_chi2dof` Float32,
    `n_fluxerr_psf` Float32,
    `n_mag_psf` Float32,
    `n_magerr_psf` Float32,
    `r_sn` Float32,
    `r_flux_psf` Float32,
    `r_psf_chi2dof` Float32,
    `r_fluxerr_psf` Float32,
    `r_mag_psf` Float32,
    `r_magerr_psf` Float32,
    `peak_dist` Float32,
    `pv_dist` Float32,
    `n_flags` UInt64,
    `r_flags` UInt64,
    `sn_gabor` Float32,
    `n_neigh` Int32,
    `flags_transient` UInt64,
    `r_jd` Float32,
    `n_fwhm` Float32,
    `r_fwhm` Float32,
    `n_limmag` Float32,
    `r_limmag` Float32,
    `n_zp` Float32,
    `r_zp` Float32,
    `n_ph_col1` Float32,
    `r_ph_col1` Float32,
    `n_exptime` Float32,
    `r_exptime` Float32,
    `n_distmp` Nullable(Float32),
    `n_magmp` Nullable(Float32),
    `r_distmp` Nullable(Float32),
    `r_magmp` Nullable(Float32),
    `class_id` Int32,
    `jd` Float64,
    `bjd` Float64,
    `baryvel` Float64,
    `ra` Float64,
    `dec` Float64,
    `xpeak` Int16,
    `ypeak` Int16,
    `x` Float32,
    `y` Float32,
    `x1` Float32,
    `y1` Float32,
    `flags` UInt32,
    `n_x2` Float32,
    `n_y2` Float32,
    `n_xy` Float32,
    `sn` Float32,
    `sn_ext1` Float32,
    `sn_ext2` Float32,
    `sn_delta` Float32,
    `flux_aper_1` Float32,
    `fluxerr_aper_1` Float32,
    `mag_aper_1` Float32,
    `magerr_aper_1` Float32,
    `flux_aper_2` Float32,
    `fluxerr_aper_2` Float32,
    `mag_aper_2` Float32,
    `magerr_aper_2` Float32,
    `flux_aper_3` Float32,
    `fluxerr_aper_3` Float32,
    `mag_aper_3` Float32,
    `magerr_aper_3` Float32,
    `flux_psf` Float32,
    `fluxerr_psf` Float32,
    `mag_psf` Float32,
    `magerr_psf` Float32,
    `back_im` Float32,
    `var_im` Float32,
    `back_annulus` Float32,
    `std_annulus` Float32,
    `mergedcat` UInt32,
    `gal_n` Int32,
    `gal_dist` Nullable(Float32),
    `star_n` Int32,
    `star_dist` Nullable(Float32),
    `object` Int32,
    `nodenumb` Int32,
    `mountnum` Int32,
    `camnum` Int32,
    `cropid` Int32,
    `zp` Float32,
    `report_jd` Nullable(Float32) DEFAULT NULL,
    `x2` Float32 DEFAULT nan,
    `y2` Float32 DEFAULT nan,
    `xy` Float32 DEFAULT nan,
    `gdircvar` Float32 DEFAULT nan,
    `gdirerror` Float32 DEFAULT nan,
    `ingestion_time_jd` Float64 DEFAULT nan,
    `r_x2` Float32 DEFAULT nan,
    `r_y2` Float32 DEFAULT nan,
    `r_xy` Float32 DEFAULT nan,
    `limmag` Float32 DEFAULT nan,
    `density` Float32 DEFAULT nan,
    `r_psf_chi2dof_med` Float32 DEFAULT nan,
    `n_psf_chi2dof_med` Float32 DEFAULT nan,
    `dsdf` Float32 DEFAULT nan,
    `flux_contam` Float32 DEFAULT nan,
    `gaia_bp` Float32 DEFAULT nan,
    `gaia_rp` Float32 DEFAULT nan,
    `star_prob` Float32 DEFAULT nan,
    `gal_prob` Float32 DEFAULT nan,
    INDEX idx_id_diff_src id_diff_src TYPE minmax GRANULARITY 16,
    INDEX idx_id_uniq_src id_uniq_src TYPE minmax GRANULARITY 16,
    INDEX idx_id_cat_src id_cat_src TYPE minmax GRANULARITY 16,
    INDEX idx_id_ref_im id_ref_im TYPE minmax GRANULARITY 16,
    INDEX idx_id_new_im id_new_im TYPE minmax GRANULARITY 16,
    INDEX idx_upix_low upix_low TYPE minmax GRANULARITY 16,
    INDEX idx_upix_high upix_high TYPE minmax GRANULARITY 16,
    INDEX idx_is_forced is_forced TYPE minmax GRANULARITY 16,
    INDEX idx_jd jd TYPE minmax GRANULARITY 16,
    INDEX idx_ra ra TYPE minmax GRANULARITY 16,
    INDEX idx_dec dec TYPE minmax GRANULARITY 16,
    INDEX idx_sn sn TYPE minmax GRANULARITY 16,
    INDEX idx_mag_aper_3 mag_aper_3 TYPE minmax GRANULARITY 16,
    INDEX idx_mag_psf mag_psf TYPE minmax GRANULARITY 16
)
ENGINE = MergeTree
PARTITION BY upix_partition
ORDER BY upix_high
SETTINGS index_granularity = 8192
