% Functions and Classes list for the timeSeries.period package
% Author : autogenerated (Jun 2023)
%   timeSeries.period.allFunList - Functions and Classes list for the timeSeries.period package
%       timeSeries.period.minclp - ------------------------------------------------------------------------------
%          timeSeries.period.pdm - Periodicity search using period dispersion minimization
%     timeSeries.period.pdm_phot - --------------------------------------------------------------------
%       timeSeries.period.period - Periodicity search in a non-equally spaced time series
% timeSeries.period.period_complex - Fourier transform of non equally spaced time series
% timeSeries.period.period_consistent - SHORT DESCRIPTION HERE
% timeSeries.period.period_entropy - Periodogram using information entropy
% timeSeries.period.period_events - -----------------------------------------------------------------------------
%   timeSeries.period.period_fft - Power spectrum of evenly spaced time series using fft
% timeSeries.period.period_fitfourier - Fit a Fourier series to a time series
%    timeSeries.period.period_mi - SHORT DESCRIPTION HERE
% timeSeries.period.period_min_curve_length - Periodicity search using minimum curve length
%  timeSeries.period.period_norm - Normalized power spectrum of non equally spaced time series
% timeSeries.period.period_norm_bootstrap - Run bootstrap normal pertiodogram on a light curve.
% timeSeries.period.period_norm_order2 - 2nd order harmonic power spectrum of non evenly spaced time series
% timeSeries.period.period_norm_solarsys - Normalized power spectrum for a Solar System object
% timeSeries.period.period_normnl - Normzlied power spectrum using no loops (may be faster in some cases)
%    timeSeries.period.period_np - SHORT DESCRIPTION HERE
%   timeSeries.period.period_pdm - SHORT DESCRIPTION HERE
%  timeSeries.period.period_plot - SHORT DESCRIPTION HERE
% timeSeries.period.period_scargle - Scargle power spectrum of non equally spaced time series
% timeSeries.period.period_scarglenl - Scargle power spectrum of non equally spaced time series / no loops
%     timeSeries.period.periodia - Classical power spectrum of non-evenly space time series (OBSOLETE)
%     timeSeries.period.periodis - Scargle periodogram. OBSOLETE: Use period.m instead.
%     timeSeries.period.periodit - Calculate the periodogram as a function of time (will be removed)
% timeSeries.period.periodmulti_norm - Simultanous power spectrum of time series with common times
 help timeSeries.period.allFunList