% Functions and Classes list for the VO.Swift package
% Author : autogenerated (Apr 2023)
%            VO.Swift.getGRB_cat - get and read the Swift online GRB catalog
%             VO.Swift.getXRT_LC - get Swift/XRT light curve of a GRB from the Swift UK database
 help VO.Swift.allFunList