function [T] = swiftXRT_wget(RA, Dec, Args)
    % Search Swift/XRT observations by coordinates and wget the obsid files
    %   The files of each obsid will be downloaded to the local dir under
    %   /YYYY_MM/obsid/ path.
    % Input  : - J2000 RA [deg]. See celestial.convert.cooResolve for
    %            options. Alternatively, if table, assume this is the main
    %            output table of VO.Swift.swiftXRT_obs rom which to
    %            construct the obsid links.
    %          - J2000 Dec [deg]. Default is [].
    %          * ...,key,val,...
    %            'SearchRadius' - Search radius [deg]. Default is 1.
    %            'swiftXRT_obsArgs' - A cell array of additional arguments
    %                   to pass to VO.Swift.swiftXRT_obs.
    %                   Default is {'UseTap',false}
    %            'MatchFiles' - Reg. exp. of files to download.
    %                   Default is '.gz'.
    %            'MaxGet' - www.pwget MaxGet parameter.
    %                   Default is 5.
    %            'SkipIfFolderExist' - Skip wget if folder already exist.
    %                   Default is true.
    % Output : - The table of obsid as generated by:
    %            VO.Swift.swiftXRT_obs.
    % Author : Eran Ofek (2025 Nov) 
    % Example: VO.Swift.swiftXRT_wget(210.75, 54.3, 'searchRadius', 1);
    %          VO.Swift.swiftXRT_wget(T);

    arguments
        RA
        Dec                    = [];
        Args.SearchRadius      = 1;  % [deg]
        Args.swiftXRT_obsArgs  = {'UseTap',false};
        Args.MatchFiles        = '.gz';
        Args.MaxGet            = 5;
        
        Args.SkipIfFolderExist = true;
    end
    PWD = pwd;

    if istable(RA)
        DU = VO.Swift.swiftXRT_table2link(RA,true);
        T  = RA;
    else
        [T,DU]  = VO.Swift.swiftXRT_obs(RA, Dec, Args.SearchRadius, Args.swiftXRT_obsArgs{:});
    end

    Ndu = numel(DU);
    for Idu=1:1:Ndu
        URL = www.find_urls(DU{Idu},'match',Args.MatchFiles);
        
        TmpSp = split(URL{1},'/');
        RelPath = sprintf('%s%s%s',TmpSp{8}, filesep, TmpSp{9});
        if Args.SkipIfFolderExist && isfolder(RelPath)
            Skip = true;
        else
            Skip = false;
        end
        if ~Skip
            mkdir(RelPath);
            cd(RelPath)
            www.pwget(URL,'',Args.MaxGet);
            cd(PWD);
        end
    end

end
