% Functions and Classes list for the celestial.proj package
% Author : autogenerated (Jun 2023)
%      celestial.proj.allFunList - Functions and Classes list for the celestial.proj package
%       celestial.proj.pr_aitoff - Project coordinates using equal area Aitoff projection
%       celestial.proj.pr_albers - Albers Equal-Area projection.
% celestial.proj.pr_azimuthal_equidist - Azimuthal equidistant projection.
%        celestial.proj.pr_bonne - Bonne projection.
%      celestial.proj.pr_cassini - Cassini projection.
%        celestial.proj.pr_conic - Conic projection.
%  celestial.proj.pr_cylindrical - Project coordinates (longitude and latitude) using a general cylindrical projection.
%     celestial.proj.pr_gnomonic - Project coordinates (longitude and latitude) using the Gnomonic non conformal projection
%       celestial.proj.pr_hammer - Project coordinates (longitude and latitude) using the Hammer projection.
% celestial.proj.pr_hammer_aitoff - Project coordinates (longitude and latitude) using equal area Hammer-Aitoff projection
%    celestial.proj.pr_ignomonic - roject coordinates using the inverse Gnomonic non conformal projection
% celestial.proj.pr_ihammer_aitoff - Project coordinates (longitude and latitude) using the inverse of the equal area Hammer-Aitoff projection
%     celestial.proj.pr_mercator - Project coordinates (longitude and latitude) using the Mercator projection.
%    celestial.proj.pr_mollweide - Project coordinates (longitude and latitude) using the equal area Mollweide projection.
%    celestial.proj.pr_parabolic - Project coordinates (longitude and latitude) using the Parabolic projection.
%       celestial.proj.pr_planis - planisphere projection.
%        celestial.proj.pr_polar - Project coordinates (longitude and latitude) using the polar projection (from north pole).
%          celestial.proj.pr_sin - Slant ortographic (SIN) projection
%   celestial.proj.pr_sinusoidal - Project coordinates (longitude and latitude) using the Sinusoidal projection.
% celestial.proj.pr_stereographic - Project coordinates (longitude and latitude) using the Stereographic projection.
% celestial.proj.pr_stereographic_polar - Project coordinates using the Stereographic polar projection
%           celestial.proj.pr_xy - X-Y projection (no transformation).
%      celestial.proj.projectcoo - Project coordinates from longitude and latitude to X/Y
%        celestial.proj.unitTest - Package Unit-Test
 help celestial.proj.allFunList