% Functions and Classes list for the mex package
% Author : autogenerated (Jun 2023)
%                 mex.allFunList - Functions and Classes list for the mex package
%       mex.test_mex_readmatrix1 - 
%       mex.test_mex_readmatrix2 - 
%             mex.test_phonebook - 
 help mex.allFunList