%==========================================================================
% ULTRASAT 
%
% File:   ultrasat.MissionClientBase.m
% Author: Chen Tishler
% Created: 01/12/2024
% Updated: 16/02/2025
%
%==========================================================================

classdef MissionClientBase < handle
    % MissionClientBase - Interface class for mission control API clients
    %
    % This class serves as an interface between MissionClient/MissionClientSim and uplanner,
    % providing a common set of methods for interacting with the mission control API.
    % It handles authentication, session management, and various API operations.
    %
    % The class is designed to be extended by:
    %   - MissionClient: For real API communication with the backend server
    %   - MissionClientSim: For simulation and testing purposes
    %
    % Key Features:
    %   - Authentication and session management
    %   - Key-value store operations
    %   - Plan management (CRUD operations)
    %   - Target and exposure data retrieval
    %   - Plan validation and submission
    %
    % Available Functions:
    %   Data Conversion:
    %     convertPlanTableToSubmitData - Converts uplanner.Plan table to submission format
    %     convertPlanTimesToUtc - Converts plan time fields to UTC format
    %
    %   Utility:
    %     msglog - Logs formatted messages to console
    %
    % Properties:
    %   User - Currently logged-in user name
    %   SessionId - Unique session identifier
    %   SessionKey - Authentication key for current session
    %   ApiUrl - Base URL of the mission control API
    %   LogFileName - Path to the log file
    %   PlanData - Instance of ultrasat.api.PlanData containing current plan information
    %   ApprovedTargetsStartTime - Start time for approved targets
    %   ApprovedTargetsEndTime - End time for approved targets
    %
    % Notes:
    %   - This class is abstract and should not be instantiated directly
    %   - All API calls are logged to the specified log file
    %   - Session management is handled automatically
    %   - Error handling is consistent across all methods
    %   - PlanData property is maintained for backward compatibility with uplanner
    %   - Time conversions are handled automatically (UTC format)

    
    properties
        User            % Currently logged-in user name
        SessionId       % Unique session identifier, generated by the client
        SessionKey      % Authentication key for the current session
        ApiUrl          % Base URL of the mission control API
        LogFileName     % Path to the log file for storing client operations

    end


    methods
        function obj = MissionClientBase(Args)
            % Constructor for the MissionClientBase class.
            % 
            % Parameters:
            %   Args.SubUrl (string) - Endpoint path to append to the base API URL (default: '/mission')
            %   Args.LogFileName (string) - Path to log file (default: same folder as this file)
            %
            % Returns:
            %   obj - Initialized MissionClientBase object            
            arguments          
                Args.SubUrl = '/mission';  % planner_backend
                Args.LogFileName = []
            end

            if isempty(Args.LogFileName)
                srcFile = mfilename('fullpath');  srcFolder = fileparts(srcFile);  
                obj.LogFileName = fullfile(srcFolder, [mfilename, '.log']);
            else
                obj.LogFileName = Args.LogFileName;
            end 

            % Call parent class constructor
            %ArgsCell = namedargs2cell(Args);
            %obj@api.ClientBase(ArgsCell{:});  % Args);  % , 'SubUrl', '/mission');
        end        
        

        % -------------------------------------------------------------------

        function response = login(obj, Params)
            % Authenticates a user with the mission control API.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.LoginParams containing:
            %     .user (string) - User name for authentication
            %     .password (string) - Password for authentication
            %
            % Returns:
            %   response - Structure containing authentication result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false)
            %     .user - (if successful) User information structure
            arguments
                obj
                Params
            end
            
            usersFile = fullfile(obj.DbPath, 'users.json');
            currentUserFile = fullfile(obj.DbPath, 'current_user.json');
            response = struct();
        
            % Load users from JSON
            users = obj.readFile(usersFile);
            if isempty(fieldnames(users))
                response.status = 'error';
                response.message = 'Users database not found.';
                response.ok = false;
                return;
            end
        
            % Find user and verify password
            user = [];
            for i = 1:numel(users)
                if strcmp(users(i).UserName, Params.user) && strcmp(users(i).Password, Params.password)
                    user = users(i);
                    break;
                end
            end
        
            if isempty(user)
                obj.msglog('login: Invalid username or password for user=%s', Params.user);
                response.status = 'error';
                response.message = 'Invalid username or password.';
                response.ok = false;
            else
                obj.msglog('login: User %s logged in successfully.', Params.user);
                response.status = 'ok';
                response.user = user;
        
                % Update current_user.json
                currentUser = struct('UserName', Params.user, 'Role', user.Role);
                fid = fopen(currentUserFile, 'w');
                fwrite(fid, jsonencode(currentUser, 'PrettyPrint', true), 'char');
                fclose(fid);
        
                response.ok = true;
            end
        end


        function response = logout(obj, Params)
            % Logs out the current user from the mission control API.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.LogoutParams containing:
            %     .user (string) - Currently logged-in user name to verify
            %
            % Returns:
            %   response - Structure containing logout result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false) 
            arguments
                obj
                Params
            end
            
            currentUserFile = fullfile(obj.DbPath, 'current_user.json');
            response = struct();
        
            % Load current user and verify
            currentUser = obj.readFile(currentUserFile);
            if isempty(fieldnames(currentUser))
                obj.msglog('logout: Current user file not found at %s', currentUserFile);
                response.status = 'error';
                response.message = 'No user currently logged in.';
                response.ok = false;
                return;
            end
        
            if ~strcmp(currentUser.UserName, Params.user)
                obj.msglog('logout: User %s is not currently logged in.', Params.user);
                response.status = 'error';
                response.message = 'User not logged in.';
                response.ok = false;
                return;
            end
        
            % Clear current user
            fid = fopen(currentUserFile, 'w');
            fwrite(fid, jsonencode(struct('UserName', '', 'Role', ''), 'PrettyPrint', true), 'char');
            fclose(fid);
        
            obj.msglog('logout: User %s logged out successfully.', Params.user);
            response.status = 'ok';
            response.ok = true;
        end

        % -------------------------------------------------------------------

        function response = getKeyValue(obj, Params)
            % Retrieves a value from a key-value store on the server.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.GetKeyValueParams containing:
            %     .store (string) - Name of the store to access
            %     .key (string) - Key to retrieve
            %     .default - Default value to return if key not found
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .value - Retrieved value or default value if not found
            %     .ok - Boolean indicating success (true) or failure (false)
            arguments
                obj
                Params
            end
            
            obj.msglog('getKeyValue: store=%s, key=%s', Params.store, Params.key);
            dbFile = fullfile(obj.DbPath, 'key_value_db.json');
            response = struct();
        
            % Read and parse the JSON file
            db = obj.readFile(dbFile);
            if isempty(fieldnames(db))
                obj.msglog('Database file not found, returning default value.');
                response.value = Params.default;
                response.status = 'ok';
                response.ok = true;
                return;
            end
        
            if isfield(db, Params.store) && isfield(db.(Params.store), Params.key)
                response.value = db.(Params.store).(Params.key);
                response.status = 'ok';
                response.ok = true;
            else
                obj.msglog('Key not found, returning default value.');
                response.value = Params.default;
                response.status = 'ok';
                response.ok = true;
            end
        end


        function response = setKeyValue(obj, Params)
            % Stores a value in a key-value store on the server.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.SetKeyValueParams containing:
            %     .store (string) - Name of the store to access
            %     .key (string) - Key to set
            %     .value - Value to store
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false) 
            arguments
                obj
                Params
            end
            
            obj.msglog('setKeyValue: store=%s, key=%s, value=%s', Params.store, Params.key, Params.value);
            dbFile = fullfile(obj.DbPath, 'key_value_db.json');
            response = struct();
        
            % Load existing data
            db = obj.readFile(dbFile);
        
            if ~isfield(db, Params.store)
                db.(Params.store) = struct();
            end
            db.(Params.store).(Params.key) = Params.value;
        
            % Write updated data to the JSON file
            fid = fopen(dbFile, 'w');
            fwrite(fid, jsonencode(db, 'PrettyPrint', true), 'char');
            fclose(fid);
        
            response.status = 'ok';
            response.ok = true;
        end

        % =================================================================
        function response = getApprovedTargets(obj, Params)
            % Retrieves the list of approved observation targets within a time range.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.GetApprovedTargetsParams containing:
            %     .start_time (datetime) - Start time for filtering targets
            %     .end_time (datetime) - End time for filtering targets
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message (if error)
            %     .targets - Array of target structures (if successful)
            %     .ok - Boolean indicating success (true) or failure (false)
            %
            % Notes:
            %   This method updates the ApprovedTargetsStartTime and 
            %   ApprovedTargetsEndTime properties.
            arguments
                obj
                Params
            end
        end


        function response = validatePlan(obj, Params)
            % Validates an observation plan against mission constraints.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.ValidateParams containing:
            %     .targets - Array of structs containing observation data
            %
            % Returns:
            %   response - Structure containing validation result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false)
            %     .validations - Detailed validation results (if available)
            %
            % Notes:
            %   Called from uplanner, Plan is array of struct
            arguments
                obj
                Params
            end
        end        


        function response = submitPlan(obj, Params)
            % Submits an observation plan to the mission control system.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.SubmitParams containing:
            %     .plan - Array of structs containing observation data
            %
            % Returns:
            %   response - Structure containing submission result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false)
            %
            % Notes:
            %   Called from uplanner
            arguments
                obj
                Params
            end
        end        


        function response = retractPlan(obj, Params)
            % Retracts a previously submitted observation plan.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.RetractParams containing:
            %     .plan_pk (integer) - ID of the plan to retract
            %
            % Returns:
            %   response - Structure containing retraction result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false)
            %
            % Notes:
            %   Called from uplanner
            arguments
                obj
                Params
            end
        end
        
        
        function response = getExposure(obj, Params)
            % Retrieves exposure data for specified healpix indices and time range.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.ExposureParams containing:
            %     .table_name (string) - Name of the exposure data table
            %     .healpix_indices (array) - Array of healpix indices to filter by
            %     .start_timestamp (datetime) - Start time for filtering exposures
            %     .end_timestamp (datetime) - End time for filtering exposures
            %     .select_all (logical) - If true, returns all records regardless of filters
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message (if error)
            %     .data - Array of exposure data structures (if successful)
            %     .ok - Boolean indicating success (true) or failure (false)
            arguments
                obj
                Params
            end
        end
        
        % =================================================================
        %                       Plans Table CRUD
        % =================================================================        

        function response = getPlansList(obj, Params)
            % Retrieves a list of all observation plans from the server.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.GetPlansListParams containing:
            %     .user_name (string) - Optional filter by user name
            %     .title (string) - Optional filter by plan title
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message (if error)
            %     .plans - Array of plan summary structures (if successful)
            %     .ok - Boolean indicating success (true) or failure (false)
            arguments
                obj
                Params
            end
        end


        function response = loadPlan(obj, Params)
            % Loads a specific observation plan by its primary key.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.LoadPlanParams containing:
            %     .plan_pk (integer) - Primary key of the plan to load
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .plan - Complete plan data structure (if successful)
            %     .ok - Boolean indicating success (true) or failure (false)
            arguments
                obj
                Params
            end
        end


        function response = savePlan(obj, Params)
            % Saves an observation plan to the server.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.SavePlanParams containing:
            %     .plan - Array of structs containing observation data
            %     .plan_name (string) - Optional name for the plan
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .plan_id - ID of the saved plan (if successful)
            %     .ok - Boolean indicating success (true) or failure (false)
            arguments
                obj
                Params
            end
        end


        function response = deletePlan(obj, Params)
            % Deletes a specific observation plan by its primary key.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.DeletePlanParams containing:
            %     .plan_pk (integer) - Primary key of the plan to delete
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false)
            arguments
                obj
                Params
            end
        end


        function response = getPlanStatus(obj, Params)
            % Retrieves the current status of a specific observation plan.
            %
            % Parameters:
            %   Params - Instance of MissionApiModels.GetPlanStatusParams containing:
            %     .plan_pk (integer) - Primary key of the plan to check
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message (if error)
            %     .data - Structure with plan status information (if successful)
            %     .ok - Boolean indicating success (true) or failure (false)
            arguments
                obj
                Params
            end
        end             

        % =================================================================

        % =================================================================        

        function submitData = convertPlanTableToSubmitData(obj, Plan)
            % Converts the uplanner.Plan table to a list of structs for submission.
            %
            % Parameters:
            %   Plan - MATLAB table containing observation plan data.
            %
            % Returns:
            %   submitData - Array of structs with only the required fields for submission.
            %
            % Notes:
            %   This method extracts specific fields needed for the submission API and
            %   performs necessary data type conversions.
        
            % Initialize the output
            submitData = [];
        
            % Loop through each row of the table
            for i = 1:height(Plan)
                % Extract required fields and store in a struct
                rowStruct = struct(...
                    'coord_ra', Plan.RA(i), ...
                    'coord_dec', Plan.Dec(i), ...
                    'tiles', Plan.Tiles(i), ...
                    'exposure', seconds(Plan.ExpTime(i)), ... % Convert duration to seconds
                    'image_count', Plan.Nexposures(i), ...
                    'start_time', datestr(Plan.Tstart(i), 'yyyy-mm-ddTHH:MM:SS.FFFZ') ...
                );
                % Append to the list
                submitData = [submitData; rowStruct];
            end
        end
        

        function Plan = convertPlanTimesToUtc(obj, Plan)
            % Converts start_time and end_time fields of each plan entry to UTC.
            %
            % Parameters:
            %   Plan - Array of structs containing plan data with time fields
            %
            % Returns:
            %   Plan - Same array with time fields converted to UTC format
            %
            % Notes:
            %   This is used to ensure consistent time format for API communication
            for i = 1:numel(Plan)
                Plan(i).start_time = ultrasat.api.MissionModels.toUtc(Plan(i).start_time);
                Plan(i).end_time = ultrasat.api.MissionModels.toUtc(Plan(i).end_time);
            end
        end
        
        % -------------------------------------------------------------------

        function msglog(obj, varargin)
            % Logs a formatted message to the console.
            %
            % Parameters:
            %   varargin - Variable arguments for fprintf-style formatting
            %
            % Notes:
            %   This method adds a 'Client: ' prefix to all log messages
            
            fprintf('Client: ');
            fprintf(varargin{:});
            fprintf('\n');
        end

        function data = readFile(obj, filename)
            % Reads and parses a JSON file.
            %
            % Parameters:
            %   filename - Full path to the JSON file to read
            %
            % Returns:
            %   data - Parsed JSON data as MATLAB structure
            %
            % Notes:
            %   - Returns empty struct if file doesn't exist
            %   - Logs errors to console
            if ~isfile(filename)
                obj.msglog('readFile: File not found at %s', filename);
                data = struct();
                return;
            end
            
            try
                fid = fopen(filename, 'r');
                raw = fread(fid, inf, 'char');
                fclose(fid);
                data = jsondecode(char(raw'));
            catch ME
                obj.msglog('readFile: Error reading file %s: %s', filename, ME.message);
                data = struct();
            end
        end

    end
end
