%==========================================================================
% ULTRASAT 
%
% File:   ultrasat.MissionClientBase.m
% Author: Chen Tishler
% Created: 01/12/2024
% Updated: 16/02/2025
%
%==========================================================================

classdef MissionClientBase < handle
    % Base class for Mission client API calls.
    % Related files:
    %
    % Base API Client:
    %   - api.ClientBase        - matlab/util/+api/ClientBase.m
    %   - api.ModelBase         - matlab/util/+api/ModelBase.m
    %   - api.ModelFactoryBase  - matlab/util/+api/ModelFactoryBase.m
    %
    % Mission Control API Client
    %
    %   - ultrasat.api.MissionClientBase  - matlab/astro/+ultrasat/+api/MissionClientBase.m
    %   - ultrasat.api.MissionModels      - matlab/astro/+ultrasat/+api/MissionModels.m
    %   - ultrasat.api.MissionApiModels   - matlab/astro/+ultrasat/+api/MissionApiModels.m
    %   - ultrasat.api.MissionClientBase  - matlab/astro/+ultrasat/+api/MissionClientBase.m

    
    properties
        User            % Logged-in user name
        SessionId       % Unique session Id, generated by the client
        SessionKey      %
        ApiUrl          %
        PlanData        % instance of ultrasat.api.PlanData
        LogFileName
    end


    methods
        function obj = MissionClientBase(Args)
            arguments          
                Args.SubUrl = '/mission';  % planner_backend
                Args.LogFileName 
            end

            if isempty(Args.LogFileName)
                srcFile = mfilename('fullpath');  srcFolder = fileparts(srcFile);  
                obj.LogFileName = fullfile(srcFolder, [mfilename, '.log']);
            else
                obj.LogFileName = Args.LogFileName;
            end 

            % Call parent class constructor
            %ArgsCell = namedargs2cell(Args);
            %obj@api.ClientBase(ArgsCell{:});  % Args);  % , 'SubUrl', '/mission');
        end        
        

        % -------------------------------------------------------------------

        function response = login(obj, UserName, Password)
            % 
        end


        function response = logout(obj, UserName)
            % 
        end        

        % -------------------------------------------------------------------

        function response = getKeyValue(obj, Store, Key, Default)
            % 
        end


        function response = setKeyValue(obj, Store, Key, Value)
            % 
        end        

        % -------------------------------------------------------------------

        function response = getApprovedTargets(obj, start_time, end_time)
            % 
        end


        function response = validatePlan(obj, Plan)
            % Called from uplanner, Plan is array of struct
        end        



        function response = submitPlan(obj, Plan)
            % Called from uplanner
        end        


        function response = retractPlan(obj, Plan)
            % Called from uplanner
        end                
        
        
        function response = getExposure(obj, table_name, healpix_indices, start_timestamp, end_timestamp, select_all)
            %
        end
        
        % -------------------------------------------------------------------

        function response = getPlansList(obj)
            % 
        end


        function response = loadPlan(obj, plan_pk)
            % 
        end


        function response = savePlan(obj)
            % 
        end


        function response = deletePlan(obj, plan_pk)
            % 
        end


        function response = getPlanStatus(obj, plan_pk)
            % 
        end             

        % -------------------------------------------------------------------

        function submitData = convertPlanTableToSubmitData(obj, Plan)
            % Converts the uplanner.Plan table to a list of structs for submission.
            %
            % :param Plan: MATLAB table containing observation plan data.
            % :return: Array of structs with only the required fields for submission.
        
            % Initialize the output
            submitData = [];
        
            % Loop through each row of the table
            for i = 1:height(Plan)
                % Extract required fields and store in a struct
                rowStruct = struct(...
                    'coord_ra', Plan.RA(i), ...
                    'coord_dec', Plan.Dec(i), ...
                    'tiles', Plan.Tiles(i), ...
                    'exposure', seconds(Plan.ExpTime(i)), ... % Convert duration to seconds
                    'image_count', Plan.Nexposures(i), ...
                    'start_time', datestr(Plan.Tstart(i), 'yyyy-mm-ddTHH:MM:SS.FFFZ') ...
                );
                % Append to the list
                submitData = [submitData; rowStruct];
            end
        end
        

        function Plan = convertPlanTimesToUtc(obj, Plan)
            % Converts start_time and end_time fields of each plan entry to UTC.
            for i = 1:numel(Plan)
                Plan(i).start_time = ultrasat.api.MissionModels.toUtc(Plan(i).start_time);
                Plan(i).end_time = ultrasat.api.MissionModels.toUtc(Plan(i).end_time);
            end
        end
        
        % -------------------------------------------------------------------

        function msglog(obj, varargin)
            % Logs a formatted message to the console.
            %
            % :param varargin: Formatted message arguments.
            
            fprintf('Client: ');
            fprintf(varargin{:});
            fprintf('\n');
        end

    end
end

