%==========================================================================
% ULTRASAT 
%
% File:   ultrasat.UserManagerBase.m
% Author: Chen Tishler
% Created: 14/09/2025
% Updated: 14/09/2025
%
%==========================================================================

classdef UserManagerBase < ultrasat.api.Loggable
    % Base class for user management
    
    properties
        User            % Currently logged-in user name
        SessionId       % Unique session identifier, generated by the client
        SessionKey      % Authentication key for the current session
        ApiUrl          % Base URL of the mission control API
        PlanData        % Instance of ultrasat.api.PlanData containing current plan information
        LogFileName     % Path to the log file for storing client operations
        NamespaceId     %
        
        % (11/09/2025)
        Roles           % roles.json parsed
        Permissions     % permissions.json parsed
        RolesData       % roles.json as-is
        Sessions        % sessions.json
        IsLoggedIn      % boolean flag
        DeviceId        %
        Message         % Message to be displayed to the user
    end


    methods
        function obj = UserManagerBase() %Args)
            % Constructor for the UserManagerBase class.
            % 
            % Parameters:
            %
            % Returns:
            %   obj - Initialized MissionClientBase object            
            %arguments          
            %end

            obj@ultrasat.api.Loggable();
            obj.msglog('UserManagerBase constructor started');           

            obj.LogPrefix = 'UserManagerBase';
            obj.DeviceId = obj.getDeviceId();
        end        
        
        % -------------------------------------------------------------------

        function response = login(obj, UserName, Password, Namespace)
            % Authenticates a user with the mission control API.
            %
            % Parameters:
            %   UserName (string) - User name for authentication
            %   Password (string) - Password for authentication
            %
            % Returns:
            %   response - Structure containing authentication result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false)
            %     .user - (if successful) User information structure
        end


        function response = logout(obj, UserName)
            % Logs out the current user from the mission control API.
            %
            % Parameters:
            %   UserName (string) - Currently logged-in user name to verify
            %
            % Returns:
            %   response - Structure containing logout result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false) 
        end        

        % -------------------------------------------------------------------

        function deviceID = getDeviceId(obj)
            % Returns a string that identifies the current device by hostname
        
            [~, hostname] = system('hostname');
            deviceID = ['matlab-' strtrim(hostname)];           
        end      

        % -------------------------------------------------------------------

        function response = getKeyValue(obj, Store, Key, Default)
            % Retrieves a value from a key-value store on the server.
            %
            % Parameters:
            %   Store (string) - Name of the store to access
            %   Key (string) - Key to retrieve
            %   Default - Default value to return if key not found
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .value - Retrieved value or default value if not found
            %     .ok - Boolean indicating success (true) or failure (false)
        end


        function response = setKeyValue(obj, Store, Key, Value)
            % Stores a value in a key-value store on the server.
            %
            % Parameters:
            %   Store (string) - Name of the store to access
            %   Key (string) - Key to set
            %   Value - Value to store
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false) 
        end        

    end


    methods (Access = public)

        function mergedParams = MergeParams(~, baseParams, overrideParams)
            % Merges two structs, with the second struct's fields overwriting the first's.
            mergedParams = baseParams;
            if isempty(overrideParams)
                return;
            end
            
            fields = fieldnames(overrideParams);
            for i = 1:numel(fields)
                key = fields{i};
                mergedParams.(key) = overrideParams.(key);
            end
        end

        
        function isMatch = MatchParams(~, required, effective)
            % Checks if the 'effective' struct satisfies the conditions in the 'required' struct.
            isMatch = false; % Default to false
            
            reqFields = fieldnames(required);
            for i = 1:numel(reqFields)
                key = reqFields{i};
                
                % The effective parameters MUST have the required key
                if ~isfield(effective, key)
                    return; % Match fails
                end
                
                reqValues = required.(key);   % This must be a cell array of allowed values
                effValue = effective.(key); % This is the single value to check
                
                % The effective value must be a member of the required values array
                if ~ismember(effValue, reqValues)
                    return; % Match fails
                end
            end
            
            % If all required keys were found and all values matched, the match is successful
            isMatch = true;
        end


        function isMatch = matchMask(~, str, mask)
            % Compares a string against a mask with wildcards ('*', '?').
            %   This is a MATLAB implementation of a wildcard mask match.
            isMatch = false; % Default to false
            
            % Convert the simple wildcard mask to a regular expression
            % 1. Escape any special regex characters in the mask itself
            regex_mask = regexptranslate('escape', mask);
            % 2. Replace the escaped wildcards with their regex equivalents
            regex_mask = strrep(regex_mask, '\*', '.*'); % '*' -> '.*' (zero or more chars)
            regex_mask = strrep(regex_mask, '\?', '.');  % '?' -> '.' (any single char)
            
            % Anchor the expression to ensure it matches the whole string
            regex_mask = ['^' regex_mask '$'];
            
            % Use regexp to check for a match
            if ~isempty(regexp(str, regex_mask, 'once'))
                isMatch = true;
            end
        end
    end

end

