%==========================================================================
% ULTRASAT 
%
% File:   ultrasat.UserManagerBase.m
% Author: Chen Tishler
% Created: 14/09/2025
% Updated: 14/09/2025
%
%==========================================================================

classdef UserManagerBase < ultrasat.api.Loggable
    % Base class for user management
    
    properties
        User            % Currently logged-in user name
        SessionId       % Unique session identifier, generated by the client
        SessionKey      % Authentication key for the current session
        ApiUrl          % Base URL of the mission control API
        PlanData        % Instance of ultrasat.api.PlanData containing current plan information
        LogFileName     % Path to the log file for storing client operations
        NamespaceId     %
        
        % (11/09/2025)
        Roles           % roles.json parsed
        Permissions     % permissions.json parsed
        RolesData       % roles.json as-is
        Sessions        % sessions.json
        IsLoggedIn      % boolean flag
        DeviceId        %
    end


    methods
        function obj = UserManagerBase(Args)
            % Constructor for the UserManagerBase class.
            % 
            % Parameters:
            %   Args.SubUrl (string) - Endpoint path to append to the base API URL (default: '/mission')
            %   Args.LogFileName (string) - Path to log file (default: same folder as this file)
            %
            % Returns:
            %   obj - Initialized MissionClientBase object            
            arguments          
                Args.SubUrl = '/mission';  % planner_backend
                Args.LogFileName = []
            end

            if isempty(Args.LogFileName)
                srcFile = mfilename('fullpath');  srcFolder = fileparts(srcFile);  
                obj.LogFileName = fullfile(srcFolder, [mfilename, '.log']);
            else
                obj.LogFileName = Args.LogFileName;
            end 

            obj.DeviceId = obj.getDeviceId();

            % Call parent class constructor
            %ArgsCell = namedargs2cell(Args);
            %obj@api.ClientBase(ArgsCell{:});  % Args);  % , 'SubUrl', '/mission');
        end        
        

        % -------------------------------------------------------------------

        function response = login(obj, UserName, Password, Namespace)
            % Authenticates a user with the mission control API.
            %
            % Parameters:
            %   UserName (string) - User name for authentication
            %   Password (string) - Password for authentication
            %
            % Returns:
            %   response - Structure containing authentication result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false)
            %     .user - (if successful) User information structure
        end


        function response = logout(obj, UserName)
            % Logs out the current user from the mission control API.
            %
            % Parameters:
            %   UserName (string) - Currently logged-in user name to verify
            %
            % Returns:
            %   response - Structure containing logout result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false) 
        end        

        % -------------------------------------------------------------------

        function deviceID = getDeviceId(obj)
            % Returns a string that identifies the current device by hostname
        
            [~, hostname] = system('hostname');
            deviceID = ['matlab-' strtrim(hostname)];
            %deviceID = strtrim(hostname);  % Remove any trailing newline or spaces        
        end

        % -------------------------------------------------------------------

        function response = getKeyValue(obj, Store, Key, Default)
            % Retrieves a value from a key-value store on the server.
            %
            % Parameters:
            %   Store (string) - Name of the store to access
            %   Key (string) - Key to retrieve
            %   Default - Default value to return if key not found
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .value - Retrieved value or default value if not found
            %     .ok - Boolean indicating success (true) or failure (false)
        end


        function response = setKeyValue(obj, Store, Key, Value)
            % Stores a value in a key-value store on the server.
            %
            % Parameters:
            %   Store (string) - Name of the store to access
            %   Key (string) - Key to set
            %   Value - Value to store
            %
            % Returns:
            %   response - Structure containing result with fields:
            %     .status - Status of the operation ('ok' or 'error')
            %     .message - Description message
            %     .ok - Boolean indicating success (true) or failure (false) 
        end        
     

    end
end

